/** Каталог, часть C — стратегии, симуляторы, уютные, семейные, спортивные, мобильные. */
export const PART_C = [
  {
    t: 'Factorio', y: 2020, dev: 'Wube Software', gr: ['simulator', 'strategy', 'sandbox'],
    tg: ['automation', 'management', 'endless', 'grind', 'coopfocused', 'lowsysreq', 'mods', 'hardcoresim', 'puzzles'],
    md: ['solo', 'coopOnline'], pl: [1, 8], pf: ['pc', 'switch'], pr: 'mid', pv: 1900,
    len: [40, 1000], dif: 4, pace: 3, rat: 96, mood: ['create', 'think', 'progress'], coopQ: 10,
    desc: { ru: 'Фабрика, которая растёт сама: «оптимизирую один конвейер» превращается в 300 часов и ночь за окном.', en: 'A factory that grows itself: optimizing one belt turns into 300 hours and sunrise outside.' },
  },
  {
    t: 'Satisfactory', y: 2024, dev: 'Coffee Stain', gr: ['simulator', 'sandbox', 'strategy'],
    tg: ['automation', 'coopfocused', 'exploration', 'management', 'long', 'epic', 'colorful', 'gpuheavy'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc'], pr: 'mid', pv: 1990,
    len: [60, 600], dif: 4, pace: 3, rat: 92, mood: ['create', 'progress', 'explore'], coopQ: 9,
    desc: { ru: 'Та же фабрика, но от первого лица и с видом на инопланетные водопады.', en: 'The same factory, now first-person with alien waterfalls on the horizon.' },
  },
  {
    t: 'RimWorld', y: 2018, dev: 'Ludeon Studios', gr: ['simulator', 'strategy', 'survival'],
    tg: ['colony', 'procedural', 'management', 'hardcoresim', 'storyrich', 'long', 'mods', 'dark', 'funny', 'pixelart'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1500,
    len: [30, 1000], dif: 4, pace: 2, rat: 93, mood: ['create', 'progress', 'story'],
    desc: { ru: 'Генератор историй про колонию: каннибалы, органные фермы и питомец, который спас всех.', en: 'A colony story generator: cannibals, organ farms and a pet that saved everyone.' },
  },
  {
    t: 'Dwarf Fortress', y: 2022, dev: 'Bay 12 Games', gr: ['simulator', 'strategy'],
    tg: ['colony', 'procedural', 'hardcoresim', 'long', 'funny', 'learn', 'epic', 'pixelart'],
    md: ['solo'], pl: [1, 1], pf: ['pc'], pr: 'mid', pv: 1900,
    len: [30, 2000], dif: 5, pace: 1, rat: 90, mood: ['create', 'think', 'story'],
    desc: { ru: 'Симуляция мира вплоть до формы ушей дварфов: «проигрывать весело» — это отсюда.', en: 'A world simulation down to ear shapes: losing is fun, and that idea started here.' },
  },
  {
    t: 'Oxygen Not Included', y: 2019, dev: 'Klei', gr: ['simulator', 'strategy', 'sandbox'],
    tg: ['colony', 'management', 'puzzles', 'hardcoresim', 'cute', 'long', 'automation', 'puzzles'],
    md: ['solo'], pl: [1, 1], pf: ['pc'], pr: 'mid', pv: 1500,
    len: [30, 300], dif: 4, pace: 2, rat: 88, mood: ['think', 'create', 'progress'],
    desc: { ru: 'Космическая колония, где физика воды, тепла и газов вас обязательно убьёт.', en: 'A space colony where the physics of water, heat and gas will definitely kill you.' },
  },
  {
    t: 'Cities: Skylines II', y: 2023, dev: 'Colossal Order', gr: ['simulator', 'strategy', 'building'],
    tg: ['management', 'relaxing', 'endless', 'tycoon', 'gpuheavy'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [20, 1000], dif: 3, pace: 1, rat: 71, mood: ['create', 'relax', 'progress'],
    desc: { ru: 'Строить город, ломать трафик и потом три часа его чинить — лучший градостроительный песочница.', en: 'Build a city, wreck the traffic, spend three hours fixing it: the best city sandbox.' },
  },
  {
    t: 'Frostpunk', y: 2018, dev: '11 bit studios', gr: ['strategy', 'survival', 'simulator'],
    tg: ['management', 'dark', 'tense', 'choices', 'short', 'philosophical', 'sad', 'hardcoresim'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1500,
    len: [12, 40], dif: 4, pace: 3, rat: 88, mood: ['think', 'feel', 'story', 'tense'],
    desc: { ru: 'Последний город на замёрзшей Земле: каждый закон — это моральный выбор, а дети работают в шахте.', en: 'The last city on a frozen Earth: every law is a moral choice and children work the mines.' },
  },
  {
    t: 'Crusader Kings III', y: 2020, dev: 'Paradox', gr: ['strategy', 'rpg', 'simulator'],
    tg: ['grandstrategy', 'historical', 'management', 'long', 'social', 'choices', 'dialogheavy', 'mods'],
    md: ['solo', 'pvpOnline'], pl: [1, 12], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [40, 1000], dif: 4, pace: 2, rat: 91, mood: ['think', 'story', 'progress'],
    desc: { ru: 'Игра про династию, а не про карту: интриги, браки и убийство двоюродного брата ради трона.', en: 'A dynasty game, not a map game: intrigue, marriages and murdering a cousin for a throne.' },
  },
  {
    t: 'Stellaris', y: 2016, dev: 'Paradox', gr: ['strategy', 'simulator'],
    tg: ['grandstrategy', 'x4', 'scifi', 'space', 'management', 'long', 'exploration', 'epic', 'mods'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 16], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [40, 500], dif: 4, pace: 2, rat: 87, mood: ['explore', 'think', 'progress'], coopQ: 7,
    desc: { ru: 'Галактика на старте, выбор этики и первый контакт: 4X, где истории пишет сама симуляция.', en: 'A galaxy at the start, an ethic to choose and a first contact: 4X where the sim writes the stories.' },
  },
  {
    t: 'Sid Meier\u2019s Civilization VII', y: 2025, dev: 'Firaxis', gr: ['strategy'],
    tg: ['tbs', 'x4', 'historical', 'management', 'replayable', 'long', 'endlessloop'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 8], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'full', pv: 3990,
    len: [30, 500], dif: 3, pace: 2, rat: 74, mood: ['think', 'progress', 'create'], coopQ: 7,
    desc: { ru: 'Ещё один ход в три ночи: классическая стратегия, где цивилизация меняется по эпохам.', en: 'One more turn at 3 am: the classic strategy game where your civilization changes by era.' },
  },
  {
    t: 'XCOM 2', y: 2016, dev: 'Firaxis', gr: ['strategy', 'tactics'],
    tg: ['tbs', 'scifi', 'difficult', 'permadeath', 'squad', 'replayable', 'loot', 'tense'],
    md: ['solo', 'pvpOnline'], pl: [1, 2], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1500,
    len: [40, 120], dif: 5, pace: 2, rat: 88, mood: ['think', 'adrenaline', 'progress'],
    desc: { ru: 'Смерть напарника — навсегда: самая нервная пошаговая тактика про вторжение пришельцев.', en: 'A squadmate dies for good: the most nerve-wracking turn-based alien invasion.' },
  },
  {
    t: 'Total War: Warhammer III', y: 2022, dev: 'Creative Assembly', gr: ['strategy', 'tactics'],
    tg: ['rts', 'tbs', 'fantasy', 'epic', 'long', 'squad', 'replayable', 'grind'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 8], pf: ['pc'], pr: 'full', pv: 3990,
    len: [40, 300], dif: 4, pace: 4, rat: 86, mood: ['adrenaline', 'progress', 'create'], coopQ: 8,
    desc: { ru: 'Магия, драконы и осадные линии: стратегия, где битвы смотришь как кино.', en: 'Magic, dragons and siege lines: strategy where battles play out like cinema.' },
  },
  {
    t: 'Age of Empires IV', y: 2021, dev: 'Relic', gr: ['strategy'],
    tg: ['rts', 'historical', 'coopfocused', 'pvpfocused', 'replayable', 'easytolearn', 'squad', 'voicechat'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 8], pf: ['pc', 'xbox'], pr: 'mid', pv: 2490,
    len: [20, 300], dif: 4, pace: 4, rat: 84, mood: ['compete', 'progress', 'laugh'], coopQ: 9, gp: 1,
    desc: { ru: 'Классическая RTS с понятным входом: кампания для сюжета, а с друзьями — против ИИ или людей.', en: 'A classic RTS that is easy to enter: campaigns for story, friends for versus or co-op AI.' },
  },
  {
    t: 'Company of Heroes 3', y: 2023, dev: 'Relic', gr: ['strategy', 'tactics'],
    tg: ['rts', 'historical', 'difficult', 'squad', 'realistic', 'tense'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 8], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [25, 200], dif: 4, pace: 4, rat: 76, mood: ['think', 'adrenaline'], coopQ: 8,
    desc: { ru: 'Вторая мировая с укрытиями и подавлением: тактика, где важна каждая секунда боя.', en: 'WWII with cover and suppression: tactics where every second of a fight counts.' },
  },
  {
    t: 'Into the Breach', y: 2018, dev: 'Subset Games', gr: ['strategy', 'tactics', 'puzzle'],
    tg: ['tbs', 'replayable', 'puzzles', 'scifi', 'short', 'pixelart', 'lowsysreq', 'difficult', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'switch', 'mobile'], pr: 'cheap', pv: 700,
    len: [10, 100], dif: 4, pace: 2, rat: 89, mood: ['think', 'progress'],
    desc: { ru: 'Шахматы против гигантских жуков: ходы видны заранее, ошибок не прощают.', en: 'Chess against giant bugs: moves are visible in advance and mistakes are punished.' },
  },
  {
    t: 'Inscryption', y: 2021, dev: 'Daniel Mullins', gr: ['card', 'horror', 'puzzle'],
    tg: ['deckbuilding', 'tense', 'short', 'dark', 'pixelart', 'storyrich', 'puzzles'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'switch'], pr: 'mid', pv: 1100,
    len: [8, 20], dif: 3, pace: 2, rat: 87, mood: ['scare', 'think', 'story'],
    desc: { ru: 'Карточный рогалик, который притворяется чем-то другим: не читайте спойлеры.', en: 'A card roguelike pretending to be something else: avoid spoilers.' },
  },
  {
    t: 'Vampire Survivors', y: 2022, dev: 'poncle', gr: ['roguelike', 'action'],
    tg: ['easytolearn', 'endlessloop', 'bullethell', 'coopfocused', 'short', 'pixelart', 'lowsysreq', 'collect', 'replayable', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 400,
    len: [10, 200], dif: 1, pace: 5, rat: 88, mood: ['relax', 'progress', 'adrenaline'], coopQ: 8,
    desc: { ru: 'Тысячи врагов на экране и одна кнопка движения: идеальный «фоновый» рогалик.', en: 'Thousands of enemies on screen and one movement button: the perfect background roguelike.' },
  },
  {
    t: 'The Sims 4', y: 2014, dev: 'Maxis', gr: ['simulator', 'sandbox'],
    tg: ['social', 'endless', 'relaxing', 'colorful', 'funny', 'cozy', 'mods', 'lowsysreq', 'family'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'mobile'], pr: 'free', pv: 0,
    len: [20, 2000], dif: 1, pace: 1, rat: 70, mood: ['create', 'relax', 'laugh'],
    desc: { ru: 'Кукольный домик для взрослых: строить дом, ломать жизни и смотреть, что будет.', en: 'A dollhouse for adults: build a house, ruin lives and watch what happens.' },
  },
  {
    t: 'Animal Crossing: New Horizons', y: 2020, dev: 'Nintendo', gr: ['simulator', 'sandbox'],
    tg: ['cozy', 'relaxing', 'family', 'social', 'endless', 'cute', 'colorful', 'collect'],
    md: ['solo', 'coopLocal', 'coopOnline'], pl: [1, 8], pf: ['switch'], pr: 'full', pv: 4990,
    len: [60, 1000], dif: 1, pace: 1, rat: 90, mood: ['relax', 'create', 'collect'], coopQ: 7,
    desc: { ru: 'Остров, где время идёт по-настоящему: лучшее лекарство от тревоги и лучший подарок ребёнку.', en: 'An island where time runs for real: the best antidote to anxiety and the best gift for a kid.' },
  },
  {
    t: 'Disney Dreamlight Valley', y: 2023, dev: 'Gameloft', gr: ['simulator', 'adventure', 'sandbox'],
    tg: ['cozy', 'relaxing', 'cute', 'colorful', 'social', 'family', 'collect', 'endless', 'farming'],
    md: ['solo', 'coopOnline'], pl: [1, 2], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 2490,
    len: [30, 300], dif: 1, pace: 1, rat: 78, mood: ['relax', 'collect', 'create'], coopQ: 6,
    desc: { ru: 'Жизнь в деревне с диснеевскими персонажами: без насилия, идеально для семьи.', en: 'Village life with Disney characters: no violence, perfect for families.' },
  },
  {
    t: 'My Time at Sandrock', y: 2023, dev: 'Pathea', gr: ['simulator', 'rpg', 'sandbox'],
    tg: ['farming', 'cozy', 'crafting', 'social', 'long', 'relaxing', 'colorful', 'storyrich', 'coopfocused'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [40, 150], dif: 2, pace: 2, rat: 85, mood: ['create', 'relax', 'story'], coopQ: 8,
    desc: { ru: 'Мастерская в пустынном городке и романтика: Stardew с бóльшим упором на стройку.', en: 'A workshop in a desert town with romance: Stardew with a stronger building focus.' },
  },
  {
    t: 'PowerWash Simulator', y: 2022, dev: 'FuturLab', gr: ['simulator'],
    tg: ['relaxing', 'coopfocused', 'cozy', 'family', 'easytolearn', 'short', 'nonviolent', 'endless'],
    md: ['solo', 'coopOnline'], pl: [1, 6], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1200,
    len: [15, 200], dif: 1, pace: 1, rat: 87, mood: ['relax', 'create'], coopQ: 9, gp: 1,
    desc: { ru: 'Смывать грязь до блеска: медитация, ASMR и внезапно самая успокаивающая игра в списке.', en: 'Washing grime away: meditation, ASMR and suddenly the most soothing game here.' },
  },
  {
    t: 'Euro Truck Simulator 2', y: 2012, dev: 'SCS Software', gr: ['simulator'],
    tg: ['driving', 'relaxing', 'slow', 'endless', 'realistic', 'coopfocused', 'mods', 'lowsysreq', 'collect'],
    md: ['solo', 'coopOnline'], pl: [1, 8], pf: ['pc'], pr: 'mid', pv: 1100,
    len: [30, 2000], dif: 2, pace: 1, rat: 93, mood: ['relax', 'escape', 'progress'], coopQ: 8,
    desc: { ru: 'Ночная трасса, радио и груз из Гамбурга в Мадрид: лучший способ отключить голову.', en: 'A night highway, radio and cargo from Hamburg to Madrid: the best way to switch off.' },
  },
  {
    t: 'Farming Simulator 25', y: 2024, dev: 'Giants Software', gr: ['simulator', 'strategy'],
    tg: ['farming', 'management', 'relaxing', 'coopfocused', 'realistic', 'endless', 'mods', 'tycoon'],
    md: ['solo', 'coopOnline'], pl: [1, 16], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [40, 1000], dif: 3, pace: 1, rat: 76, mood: ['create', 'relax', 'progress'], coopQ: 8,
    desc: { ru: 'Настоящая техника, поля и логистика: кооп на 16 человек для тех, кто любит тракторы.', en: 'Real machinery, fields and logistics: 16-player co-op for tractor lovers.' },
  },
  {
    t: 'Microsoft Flight Simulator', y: 2020, dev: 'Asobo', gr: ['simulator'],
    tg: ['realistic', 'relaxing', 'exploration', 'learn', 'vr', 'slow', 'gpuheavy', 'endless', 'photomode'],
    md: ['solo', 'coopOnline'], pl: [1, 16], pf: ['pc', 'xbox'], pr: 'full', pv: 3990,
    len: [30, 1000], dif: 5, pace: 1, rat: 89, mood: ['relax', 'explore', 'learn'], coopQ: 6,
    desc: { ru: 'Вся Земля в реальном масштабе: можно учить навигацию, а можно просто лететь вдоль Альп.', en: 'The whole Earth at real scale: learn navigation, or just fly along the Alps.' },
  },
  {
    t: 'Forza Horizon 5', y: 2021, dev: 'Playground Games', gr: ['racing', 'sports'],
    tg: ['openworld', 'colorful', 'coopfocused', 'pvpfocused', 'easytolearn', 'photomode', 'relaxing', 'collect', 'crosplay'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 12], pf: ['pc', 'xbox'], pr: 'full', pv: 3990,
    len: [20, 300], dif: 2, pace: 4, rat: 92, mood: ['adrenaline', 'relax', 'collect'], coopQ: 9, gp: 1,
    desc: { ru: 'Мексика, 700 машин и гонки, где можно просто кататься с друзьями по красоте.', en: 'Mexico, 700 cars and races you can ignore to just cruise with friends.' },
  },
  {
    t: 'Gran Turismo 7', y: 2022, dev: 'Polyphony Digital', gr: ['racing', 'simulator'],
    tg: ['realistic', 'collect', 'photomode', 'pvpfocused', 'slow', 'long', 'vr', 'difficult'],
    md: ['solo', 'pvpOnline', 'coopLocal'], pl: [1, 2], pf: ['ps'], pr: 'full', pv: 4990,
    len: [30, 500], dif: 4, pace: 3, rat: 87, mood: ['progress', 'collect', 'compete'],
    desc: { ru: 'Автомобильная религия: лицензии, тюнинг и коллекция из 400+ машин с настоящей физикой.', en: 'Car religion: licenses, tuning and a 400+ car collection with real physics.' },
  },
  {
    t: 'EA Sports FC 26', y: 2025, dev: 'EA Vancouver', gr: ['sports'],
    tg: ['pvpfocused', 'coopfocused', 'easytolearn', 'crosplay', 'realistic', 'grind', 'collect', 'splitscreen'],
    md: ['solo', 'coopOnline', 'coopLocal', 'pvpOnline', 'pvpLocal'], pl: [1, 22], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'full', pv: 4990,
    len: [20, 500], dif: 3, pace: 4, rat: 71, mood: ['compete', 'progress', 'laugh'], coopQ: 9,
    desc: { ru: 'Футбол на диване или в клубе с друзьями: режим карьеры и Ultimate Team на сотни часов.', en: 'Football on the couch or with a club of friends: career and Ultimate Team for hundreds of hours.' },
  },
  {
    t: 'Football Manager 2024', y: 2023, dev: 'Sports Interactive', gr: ['simulator', 'strategy', 'sports'],
    tg: ['management', 'tycoon', 'long', 'grind', 'realistic', 'collect', 'learn', 'slow', 'mods'],
    md: ['solo', 'coopOnline'], pl: [1, 30], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'full', pv: 3990,
    len: [50, 2000], dif: 4, pace: 1, rat: 86, mood: ['progress', 'think', 'create'], coopQ: 6,
    desc: { ru: 'Таблицы, трансферы и «ещё один сезон»: самая глубокая игра про управление клубом.', en: 'Spreadsheets, transfers and one more season: the deepest club management game.' },
  },
  {
    t: 'Two Point Museum', y: 2025, dev: 'Two Point Studios', gr: ['simulator', 'strategy', 'building'],
    tg: ['tycoon', 'management', 'funny', 'relaxing', 'colorful', 'easytolearn', 'endless', 'cute'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 2990,
    len: [20, 200], dif: 2, pace: 2, rat: 84, mood: ['create', 'laugh', 'relax'],
    desc: { ru: 'Свой музей с ворами, школьниками и динозавром: тёплый менеджмент с британским юмором.', en: 'Your own museum with thieves, school trips and a dinosaur: warm management with British humour.' },
  },
  {
    t: 'Planet Zoo', y: 2019, dev: 'Frontier', gr: ['simulator', 'strategy', 'building'],
    tg: ['tycoon', 'management', 'cute', 'relaxing', 'learn', 'endless', 'colorful'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [30, 500], dif: 3, pace: 1, rat: 84, mood: ['create', 'relax', 'learn'],
    desc: { ru: 'Зоопарк, где у каждого животного свои потребности, а у вас — сотня часов стройки.', en: 'A zoo where every animal has needs and you have a hundred hours of building ahead.' },
  },
  {
    t: 'Among Us', y: 2018, dev: 'Innersloth', gr: ['party'],
    tg: ['social', 'funny', 'voicechat', 'easytolearn', 'crosplay', 'lobbybig', 'coopfocused', 'lowsysreq', 'cute'],
    md: ['coopOnline', 'coopLocal'], pl: [4, 15], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 300,
    len: [3, 200], dif: 1, pace: 3, rat: 85, mood: ['laugh', 'compete'], coopQ: 10,
    desc: { ru: 'Предатель среди друзей и допросы в голосовом чате: лучшая игра для компании от 4 человек.', en: 'A traitor among friends and interrogations on voice chat: the best game for groups of four or more.' },
  },
  {
    t: 'Minecraft Dungeons', y: 2020, dev: 'Mojang', gr: ['action', 'rpg'],
    tg: ['coopfocused', 'family', 'easytolearn', 'loot', 'cute', 'splitscreen', 'short', 'colorful', 'lobby4'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [10, 60], dif: 2, pace: 4, rat: 78, mood: ['laugh', 'progress'], coopQ: 9, gp: 1,
    desc: { ru: 'Диаблоид для всей семьи: просто, красочно и играется вчетвером на одном диване.', en: 'A family-friendly dungeon crawler: simple, colorful and great for four on one couch.' },
  },
  {
    t: 'LEGO Star Wars: The Skywalker Saga', y: 2022, dev: 'TT Games', gr: ['action', 'adventure', 'platformer'],
    tg: ['family', 'funny', 'coopfocused', 'splitscreen', 'easytolearn', 'collect', 'colorful', 'epic'],
    md: ['solo', 'coopLocal'], pl: [1, 2], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 2490,
    len: [30, 100], dif: 1, pace: 3, rat: 80, mood: ['laugh', 'story', 'collect'], coopQ: 9,
    desc: { ru: 'Все девять эпизодов LEGO: идеальная игра для родителей и детей, где шутки работают на обоих.', en: 'All nine episodes in LEGO: the ideal parent-and-child game where the jokes land for both.' },
  },
  {
    t: 'Mario Kart 8 Deluxe', y: 2017, dev: 'Nintendo', gr: ['racing', 'party'],
    tg: ['splitscreen', 'family', 'colorful', 'easytolearn', 'pvpfocused', 'lobbybig', 'cute', 'replayable'],
    md: ['solo', 'coopLocal', 'coopOnline', 'pvpLocal', 'pvpOnline'], pl: [1, 12], pf: ['switch'], pr: 'full', pv: 4990,
    len: [10, 500], dif: 2, pace: 4, rat: 92, mood: ['laugh', 'compete', 'adrenaline'], coopQ: 10,
    desc: { ru: 'Гонки, в которые играют все: побеждать умеют даже те, кто впервые взял геймпад.', en: 'Racing everyone plays: even first-time controller holders can win.' },
  },
  {
    t: 'Genshin Impact', y: 2020, dev: 'HoYoverse', gr: ['rpg', 'action', 'adventure'],
    tg: ['gacha', 'anime', 'openworld', 'colorful', 'exploration', 'coopfocused', 'long', 'grind', 'crosplay', 'collect'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'mobile'], pr: 'free', pv: 0,
    len: [80, 1000], dif: 2, pace: 3, rat: 84, mood: ['explore', 'collect', 'escape'], coopQ: 7,
    desc: { ru: 'Бесплатный открытый мир с аниме-боями и элементами: можно не платить ни рубля и играть сотни часов.', en: 'A free open world with anime combat and elements: hundreds of hours without paying a ruble.' },
  },
  {
    t: 'Honkai: Star Rail', y: 2023, dev: 'HoYoverse', gr: ['rpg', 'adventure'],
    tg: ['gacha', 'anime', 'tbs', 'storyrich', 'scifi', 'space', 'collect', 'crosplay', 'relaxing'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'mobile'], pr: 'free', pv: 0,
    len: [60, 500], dif: 2, pace: 2, rat: 83, mood: ['story', 'collect', 'relax'],
    desc: { ru: 'Космический поезд, отличные диалоги и пошаговые бои — самая «спокойная» гача из больших.', en: 'A space train, sharp dialogue and turn-based battles: the calmest big-budget gacha.' },
  },
  {
    t: 'Brawl Stars', y: 2018, dev: 'Supercell', gr: ['action', 'shooter', 'party'],
    tg: ['pvpfocused', 'easytolearn', 'short', 'cute', 'colorful', 'squad', 'lobby4', 'collect', 'crosplay'],
    md: ['coopOnline', 'pvpOnline'], pl: [1, 6], pf: ['mobile'], pr: 'free', pv: 0,
    len: [5, 500], dif: 3, pace: 5, rat: 79, mood: ['adrenaline', 'compete', 'laugh'], coopQ: 8,
    desc: { ru: 'Трёхминутные матчи на телефоне: идеально, когда есть 5 свободных минут и друг рядом.', en: 'Three-minute matches on your phone: perfect for a spare five minutes with a friend.' },
  },
  {
    t: 'Roblox', y: 2006, dev: 'Roblox Corporation', gr: ['sandbox', 'party'],
    tg: ['social', 'endless', 'collect', 'family', 'coopfocused', 'lobbybig', 'colorful', 'crosplay', 'easytolearn'],
    md: ['solo', 'coopOnline', 'pvpOnline', 'mmo'], pl: [1, 100], pf: ['pc', 'ps', 'xbox', 'mobile'], pr: 'free', pv: 0,
    len: [10, 5000], dif: 1, pace: 3, rat: 72, mood: ['create', 'laugh', 'escape'], coopQ: 9,
    desc: { ru: 'Тысячи игр внутри одной платформы: тут и паркур, и симуляторы, и целые сообщества.', en: 'Thousands of games inside one platform: parkour, simulators and whole communities.' },
  },
  {
    t: 'Fortnite', y: 2017, dev: 'Epic Games', gr: ['shooter', 'party', 'sandbox'],
    tg: ['pvpfocused', 'coopfocused', 'squad', 'colorful', 'easytolearn', 'crosplay', 'social', 'endlessloop', 'collect'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 100], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'free', pv: 0,
    len: [10, 1000], dif: 3, pace: 5, rat: 80, mood: ['adrenaline', 'laugh', 'compete'], coopQ: 9,
    desc: { ru: 'Королевская битва, которая стала платформой: концерты, LEGO-режимы и вечный сезонный движ.', en: 'The battle royale that became a platform: concerts, LEGO modes and endless seasons.' },
  },
  {
    t: 'Monster Hunter Wilds', y: 2025, dev: 'Capcom', gr: ['action', 'rpg', 'adventure'],
    tg: ['coopfocused', 'epic', 'loot', 'grind', 'openworld', 'exploration', 'difficult', 'photomode', 'gpuheavy'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 4990,
    len: [40, 400], dif: 4, pace: 3, rat: 86, mood: ['adrenaline', 'progress', 'explore'], coopQ: 9,
    desc: { ru: 'Живой мир, песчаные бури и охота на драконов с друзьями на 100+ часов.', en: 'A living world, sandstorms and dragon hunts with friends for 100+ hours.' },
  },
  {
    t: 'Dune: Awakening', y: 2025, dev: 'Funcom', gr: ['survival', 'mmo', 'action'],
    tg: ['openworld', 'scifi', 'crafting', 'basebuilding', 'coopfocused', 'mmosocial', 'grind', 'epic', 'long'],
    md: ['solo', 'coopOnline', 'mmo', 'pvpOnline'], pl: [1, 40], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [50, 500], dif: 4, pace: 3, rat: 72, mood: ['explore', 'create', 'escape'], coopQ: 8,
    desc: { ru: 'Арракис, черви и вода дороже золота: MMO-выживание, где гильдии делят специи.', en: 'Arrakis, worms and water worth more than gold: an MMO survival where guilds fight over spice.' },
  },
];
