/**
 * Каталог, часть I — тонкие жанры: файтинги, гонки, спорт, визуальные новеллы,
 * детективы, стелс, мобильные идлы и проверенная классика до 2010 года.
 * Формат: см. js/catalog/dsl.js
 */
import { g } from './dsl.js';

export const PART_I = [
  /* ----------------------------- классика до 2010 ----------------------------- */
  g('Half-Life', 1998, 'Valve', ['shooter', 'adventure'], ['storyrich', 'scifi', 'linear', 'nostalgia', 'tense', 'puzzles'], ['solo'], [1, 1], ['pc', 'ps'], 'cheap', 300, [12, 16], 4, 3, 96, ['adrenaline', 'story', 'nostalgia'], { ru: 'Игра, которая научила шутеры рассказывать историю без катсцен.', en: 'The game that taught shooters to tell stories without cutscenes.' }),
  g("Baldur's Gate II: Enhanced Edition", 2013, 'Beamdog', ['rpg', 'adventure'], ['storyrich', 'dialogheavy', 'fantasy', 'choices', 'long', 'nostalgia', 'tbs'], ['solo', 'coopOnline'], [1, 6], ['pc', 'ps', 'xbox', 'switch', 'mobile'], 'cheap', 700, [60, 150], 4, 2, 95, ['story', 'think', 'nostalgia'], { ru: 'Джон Айреникус и золотой век RPG: текста много, но он того стоит.', en: 'Jon Irenicus and the golden age of RPGs: lots of text, all worth it.' }, { coopQ: 7 }),
  g('Heroes of Might and Magic III', 1999, 'New World Computing', ['strategy', 'tactics'], ['tbs', 'fantasy', 'nostalgia', 'long', 'replayable', 'mods', 'coopfocused'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal'], [1, 8], ['pc', 'mobile'], 'cheap', 300, [40, 500], 3, 2, 94, ['think', 'progress', 'nostalgia', 'learn'], { ru: '«Ещё один ход» до утра: пошаговая классика, живая благодаря фанатам.', en: 'One more turn until sunrise: a turn-based classic kept alive by fans.' }, { coopQ: 8 }),
  g('Age of Empires II: The Age of Kings', 1999, 'Ensemble Studios', ['strategy'], ['rts', 'historical', 'nostalgia', 'long', 'tbs'], ['solo', 'coopOnline', 'pvpOnline'], [1, 8], ['pc', 'ps'], 'cheap', 300, [30, 200], 3, 3, 92, ['progress', 'nostalgia', 'compete', 'learn'], { ru: 'Та самая стратегия из детства: 40 минут на партию и вечный «wololo».', en: 'The strategy game from childhood: forty minutes a match and eternal wololo.' }),
  g('Diablo II: Resurrected', 2021, 'Blizzard', ['rpg', 'action'], ['loot', 'grind', 'dark', 'nostalgia', 'long', 'coopfocused', 'demons'], ['solo', 'coopOnline'], [1, 8], ['pc', 'ps', 'xbox', 'switch'], 'mid', 1990, [25, 300], 3, 3, 89, ['progress', 'adrenaline', 'nostalgia'], { ru: 'Мясорубка из Кликера и Мясника: лучший лут-цикл в жанре.', en: 'A slaughterhouse of Clicker and Butcher: the best loot loop in the genre.' }, { coopQ: 8 }),
  g('Warcraft III: Reforged', 2020, 'Blizzard', ['strategy', 'rpg'], ['rts', 'fantasy', 'nostalgia', 'storyrich', 'mods'], ['solo', 'coopOnline', 'pvpOnline'], [1, 8], ['pc'], 'mid', 1500, [30, 200], 3, 3, 68, ['story', 'nostalgia', 'compete'], { ru: 'Кампания про Артаса и карты, из которых выросла целая MOBA-культура.', en: 'Arthas\u2019 campaign and the custom maps that birthed MOBA culture.' }, { coopQ: 7 }),
  g('Star Wars: Battlefront II (2005)', 2005, 'Pandemic Studios', ['shooter', 'action'], ['scifi', 'space', 'nostalgia', 'war', 'coopfocused'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal'], [1, 64], ['pc', 'ps', 'xbox'], 'cheap', 300, [10, 60], 3, 4, 88, ['adrenaline', 'nostalgia'], { ru: 'Джедаи, клоны и космические бои — эталон «Звёздных войн» для фанатов.', en: 'Jedi, clones and space battles: the fan-favourite Star Wars sandbox.' }, { coopQ: 8 }),
  g('Stronghold Crusader', 2002, 'Firefly Studios', ['strategy', 'simulator', 'building'], ['historical', 'management', 'nostalgia', 'tbs', 'coopfocused'], ['solo', 'coopOnline', 'pvpOnline'], [1, 8], ['pc'], 'cheap', 300, [30, 200], 3, 2, 88, ['create', 'think', 'nostalgia', 'learn'], { ru: 'Замок, рвы, крестоносцы и налоги: градостроительная классика с осадой.', en: 'Castles, moats, crusaders and taxes: a classic builder with sieges.' }, { coopQ: 7 }),
  g('Dead Space (2008)', 2008, 'EA Redwood Shores', ['horror', 'shooter', 'adventure'], ['tense', 'scifi', 'space', 'dark', 'cthulhu', 'cinematic', 'nostalgia'], ['solo'], [1, 1], ['pc', 'ps', 'xbox'], 'cheap', 500, [12, 18], 4, 3, 89, ['scare', 'adrenaline', 'story'], { ru: 'Ишимура, «Искра» и некроморфы: космический хоррор без передышки.', en: 'Ishimura, the Ishimura and necromorphs: non-stop space horror.' }),
  g('The Elder Scrolls IV: Oblivion', 2006, 'Bethesda', ['rpg', 'adventure'], ['openworld', 'fantasy', 'mods', 'nostalgia', 'long', 'exploration', 'choices'], ['solo'], [1, 1], ['pc', 'ps', 'xbox'], 'cheap', 700, [30, 200], 3, 2, 94, ['explore', 'story', 'nostalgia'], { ru: 'Забытые врата и «Остановись, преступник!»: уютный абсурд и свобода.', en: 'Oblivion gates and “Stop right there, criminal scum!”: cosy absurd freedom.' }),
  g('Prince of Persia: The Sands of Time', 2003, 'Ubisoft Montreal', ['action', 'platformer', 'adventure'], ['parkour', 'fantasy', 'storyrich', 'nostalgia', 'puzzles'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch'], 'cheap', 400, [10, 15], 3, 3, 92, ['adrenaline', 'story', 'nostalgia'], { ru: 'Отматывать время назад и прыгать по стенам — до сих пор приятно.', en: 'Rewinding time and wall-running still feels wonderful.' }),
  g('Beyond Good & Evil', 2003, 'Ubisoft', ['action', 'adventure', 'stealth'], ['storyrich', 'scifi', 'puzzles', 'nostalgia', 'photomode'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch'], 'cheap', 400, [10, 15], 3, 2, 86, ['story', 'explore', 'nostalgia'], { ru: 'Фоторепортаж, заговор и Джад: культовая странность Ubisoft.', en: 'Photojournalism, conspiracy and Jade: Ubisoft’s cult oddity.' }),
  g('Sid Meier’s Civilization IV', 2005, 'Firaxis', ['strategy'], ['grandstrategy', 'tbs', 'historical', 'long', 'nostalgia', 'mods', 'philosophical'], ['solo', 'coopOnline', 'pvpOnline'], [1, 12], ['pc'], 'cheap', 400, [40, 500], 4, 1, 93, ['think', 'progress', 'nostalgia', 'learn'], { ru: '«Баба создал компартию» и бесконечные ночи на карте: классика 4X.', en: 'Endless nights on the map: the 4X classic that shaped the genre.' }, { coopQ: 7 }),
  g('Command & Conquer: Red Alert 2', 2000, 'Westwood', ['strategy'], ['rts', 'scifi', 'nostalgia', 'war', 'funny', 'coopfocused'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal'], [1, 8], ['pc'], 'cheap', 300, [15, 60], 3, 3, 89, ['nostalgia', 'compete', 'laugh'], { ru: 'Советская кампания, хроносфера и арт-стиль, который до сих пор копируют.', en: 'Soviet campaign, chronosphere and an art style people still copy.' }, { coopQ: 8 }),
  g('Silent Hill 2', 2001, 'Team Silent', ['horror', 'adventure'], ['tense', 'dark', 'surreal', 'storyrich', 'philosophical', 'sad', 'puzzles', 'nostalgia'], ['solo'], [1, 1], ['pc', 'ps', 'xbox'], 'cheap', 500, [8, 12], 4, 1, 95, ['scare', 'story', 'feel'], { ru: 'Пирамидоголовый, туман и вина: эталон психологического хоррора.', en: 'Pyramid Head, fog and guilt: the gold standard of psychological horror.' }),

  /* ----------------------------- визуальные новеллы ----------------------------- */
  g('Steins;Gate', 2009, '5pb.', ['visual', 'adventure'], ['storyrich', 'scifi', 'timeloop', 'timetravel', 'dialogheavy', 'sad', 'anime', 'soundtrack', 'nostalgia'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch', 'mobile'], 'mid', 1500, [30, 60], 2, 1, 93, ['story', 'feel', 'think'], { ru: 'Микроволновка, меняющая прошлое, и лучший таймлуп в играх.', en: 'A microwave that rewrites the past and the best time loop in gaming.' }),
  g('Doki Doki Literature Club', 2017, 'Team Salvato', ['visual', 'horror'], ['surreal', 'anime', 'tense', 'storyrich', 'short'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch'], 'free', 0, [4, 8], 1, 1, 89, ['scare', 'story', 'feel'], { ru: 'Клуб литераторов, который ломает четвёртую стену очень неприятным способом.', en: 'A literature club that breaks the fourth wall in a very nasty way.' }),
  g('The House in Fata Morgana', 2012, 'Novectacle', ['visual', 'adventure'], ['storyrich', 'sad', 'dark', 'historical', 'dialogheavy', 'philosophical', 'soundtrack'], ['solo'], [1, 1], ['pc', 'ps', 'switch', 'mobile'], 'mid', 1500, [30, 60], 2, 1, 92, ['story', 'feel'], { ru: 'Проклятый особняк и несколько веков историй: самая красивая печальная новелла.', en: 'A cursed mansion and centuries of stories: the most beautiful sad novel.' }),
  g('Va-11 Hall-A: Second Round', 2026, 'Sukeban Games', ['visual', 'simulator'], ['dialogheavy', 'cyberpunk', 'soundtrack', 'cozy', 'pixelart', 'philosophical'], ['solo'], [1, 1], ['pc'], 'mid', 1990, [12, 25], 1, 2, 85, ['story', 'relax'], { ru: 'Продолжение барменской классики: те же коктейли, новые судьбы.', en: 'The bartending classic returns: same cocktails, new fates.' }),
  g('Project Sekai: Colorful Stage!', 2020, 'Sega', ['rhythm', 'visual'], ['soundtrack', 'anime', 'touch', 'gacha', 'social', 'colorful', 'cute'], ['solo', 'coopOnline'], [1, 5], ['mobile'], 'free', 0, [10, 1000], 3, 4, 82, ['laugh', 'adrenaline', 'progress'], { ru: 'Вокалоиды, ритм-бои и кооп на пять человек прямо в телефоне.', en: 'Vocaloids, rhythm battles and five-player co-op on your phone.' }, { coopQ: 8 }),

  /* ----------------------------- метроидвании ----------------------------- */
  g('Castlevania: Symphony of the Night', 1997, 'Konami', ['metroidvania', 'action', 'platformer'], ['pixelart', 'fantasy', 'exploration', 'nostalgia', 'soundtrack', 'vampires'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'mobile'], 'cheap', 300, [8, 15], 3, 3, 93, ['explore', 'nostalgia', 'adrenaline'], { ru: 'Замок Дракулы, «перевёрнутый замок» и рождение жанра метроидвания.', en: 'Dracula’s castle, the inverted castle and the birth of metroidvania.' }),
  g('Ender Lilies: Quietus of the Knights', 2021, 'Live Wire', ['metroidvania', 'action', 'rpg'], ['pixelart', 'dark', 'sad', 'soundtrack', 'exploration', 'difficult'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch'], 'cheap', 1100, [15, 30], 4, 3, 86, ['explore', 'feel', 'adrenaline'], { ru: 'Белая жрица и призраки рыцарей: меланхоличная метроидвания с отличным звуком.', en: 'A white priestess and ghost knights: a melancholy metroidvania with great sound.' }),
  g('Afterimage', 2023, 'Aurogon', ['metroidvania', 'action', 'rpg'], ['handdrawn', 'fantasy', 'exploration', 'long', 'colorful', 'soundtrack'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch'], 'cheap', 1100, [20, 40], 3, 3, 79, ['explore', 'adrenaline'], { ru: 'Огромные нарисованные от руки уровни и десятки боссов.', en: 'Huge hand-painted levels and dozens of bosses.' }),
  g('Metroid Dread', 2021, 'MercurySteam', ['metroidvania', 'action', 'shooter'], ['scifi', 'tense', 'difficult', 'exploration', 'cinematic'], ['solo'], [1, 1], ['switch'], 'full', 4990, [10, 20], 4, 4, 88, ['adrenaline', 'explore', 'tense'], { ru: 'Самус против неубиваемых роботов E.M.M.I.: лучший экшен-платформинг Nintendo.', en: 'Samus versus unkillable E.M.M.I. robots: Nintendo’s best action platforming.' }),

  /* ----------------------------- ритм-игры ----------------------------- */
  g('Hatsune Miku: Project DIVA Mega Mix+', 2022, 'Sega', ['rhythm'], ['soundtrack', 'anime', 'colorful', 'cute', 'replayable', 'nostalgia'], ['solo', 'coopLocal'], [1, 2], ['pc', 'switch'], 'full', 3990, [10, 200], 3, 4, 85, ['adrenaline', 'laugh', 'nostalgia'], { ru: 'Вокалоидные клипы, в которые нужно попадать пальцами в такт.', en: 'Vocaloid videos you have to hit in time with your fingers.' }),
  g('Rhythm Doctor', 2021, '7th Beat Games', ['rhythm'], ['soundtrack', 'easytolearn', 'wacky', 'short', 'replayable', 'offline'], ['solo', 'coopLocal'], [1, 2], ['pc', 'switch'], 'cheap', 700, [3, 15], 4, 4, 92, ['adrenaline', 'laugh'], { ru: 'Одна кнопка, седьмой бит и десятки трюков: гениальная ритм-игра за копейки.', en: 'One button, the seventh beat and dozens of tricks: genius for pocket change.' }),
  g('Muse Dash', 2018, 'PeroPeroGames', ['rhythm', 'action'], ['anime', 'colorful', 'cute', 'soundtrack', 'touch', 'replayable'], ['solo'], [1, 1], ['pc', 'switch', 'mobile'], 'cheap', 400, [5, 100], 3, 4, 88, ['adrenaline', 'laugh', 'progress'], { ru: 'Две кнопки, аниме-девочки и музыка, от которой не оторваться.', en: 'Two buttons, anime girls and music you cannot put down.' }),
  g('Trombone Champ', 2022, 'Holy Wow', ['rhythm', 'party'], ['funny', 'wacky', 'soundtrack', 'easytolearn', 'short'], ['solo', 'coopLocal', 'pvpLocal'], [1, 4], ['pc', 'switch'], 'cheap', 700, [2, 10], 2, 3, 80, ['laugh', 'relax'], { ru: 'Играть на тромбоне настолько плохо, насколько получится: идеально для компании.', en: 'Honk a trombone as badly as possible: perfect for a party.' }),

  /* ----------------------------- файтинги ----------------------------- */
  g('Tekken 8', 2024, 'Bandai Namco', ['fighting', 'action'], ['pvpfocused', 'squad', 'cinematic', 'anime', 'difficult', 'arena', 'epic'], ['solo', 'pvpOnline', 'pvpLocal', 'coopOnline'], [1, 2], ['pc', 'ps', 'xbox'], 'full', 4990, [8, 1000], 5, 5, 89, ['compete', 'adrenaline', 'progress'], { ru: 'Турнир «Король железного кулака» и лучший онбординг среди файтингов.', en: 'The King of Iron Fist tournament with the friendliest fighting-game onboarding.' }, { coopQ: 5 }),
  g('Street Fighter 6', 2023, 'Capcom', ['fighting', 'action'], ['pvpfocused', 'squad', 'colorful', 'easytolearn', 'difficult', 'modern'], ['solo', 'pvpOnline', 'pvpLocal'], [1, 2], ['pc', 'ps', 'xbox'], 'full', 4990, [8, 1000], 4, 5, 92, ['compete', 'adrenaline', 'progress'], { ru: 'Мир-тур с открытым городом и файтинг, в который наконец можно зайти новичку.', en: 'A World Tour hub and a fighting game newcomers can finally enter.' }),
  g('Guilty Gear Strive', 2021, 'Arc System Works', ['fighting', 'action'], ['anime', 'soundtrack', 'cinematic', 'difficult', 'pvpfocused', 'handdrawn', 'epic'], ['solo', 'pvpOnline', 'pvpLocal'], [1, 2], ['pc', 'ps', 'xbox'], 'mid', 3990, [6, 1000], 5, 5, 87, ['compete', 'adrenaline'], { ru: 'Аниме-файтинг с лучшей картинкой и рок-саундтреком, который поют фанаты.', en: 'The anime fighter with the best visuals and a rock soundtrack fans sing.' }),
  g('Mortal Kombat 11', 2019, 'NetherRealm', ['fighting', 'action'], ['cinematic', 'dark', 'storyrich', 'pvpfocused', 'difficult', 'fantasy'], ['solo', 'pvpOnline', 'pvpLocal'], [1, 2], ['pc', 'ps', 'xbox', 'switch'], 'mid', 2490, [8, 200], 4, 5, 83, ['adrenaline', 'story', 'compete'], { ru: 'Фаталити, тайм-лайн и постановочная кампания: файтинг для тех, кто пришёл за сюжетом.', en: 'Fatalities, timelines and a cinematic campaign: a fighter for story people.' }),
  g('Super Smash Bros. Ultimate', 2018, 'Bandai Namco', ['fighting', 'party'], ['pvpfocused', 'splitscreen', 'colorful', 'family', 'coopfocused', 'lobbybig', 'nostalgia'], ['solo', 'coopLocal', 'pvpLocal', 'pvpOnline'], [1, 8], ['switch'], 'full', 4990, [10, 1000], 3, 4, 93, ['laugh', 'compete', 'nostalgia'], { ru: 'Все герои Nintendo (и не только) в одной игре: лучший домашний файтинг.', en: 'Every Nintendo hero (and more) in one game: the best couch fighter.' }, { coopQ: 9 }),
  g('MultiVersus', 2024, 'Player First Games', ['fighting', 'party'], ['superhero', 'funny', 'coopfocused', 'pvpfocused', 'crosplay', 'colorful'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal'], [1, 4], ['pc', 'ps', 'xbox'], 'free', 0, [5, 300], 3, 4, 74, ['laugh', 'compete'], { ru: 'Бэтмен против Шэгги: бесплатный платформенный файтинг с коопом 2×2.', en: 'Batman versus Shaggy: a free platform fighter with 2v2 co-op.' }, { coopQ: 9 }),

  /* ----------------------------- гонки ----------------------------- */
  g('BeamNG.drive', 2015, 'BeamNG', ['racing', 'simulator', 'sandbox'], ['physics', 'driving', 'hardcoresim', 'mods', 'wacky', 'endless'], ['solo'], [1, 1], ['pc'], 'mid', 1990, [10, 2000], 4, 3, 94, ['laugh', 'create', 'adrenaline'], { ru: 'Самые честные деформации в играх: бить машины здесь приятно.', en: 'The most honest car deformation in games: crashing here feels great.' }),
  g('Trackmania Nations', 2006, 'Nadeo', ['racing'], ['driving', 'easytolearn', 'difficult', 'replayable', 'lowsysreq', 'nostalgia'], ['solo', 'pvpOnline', 'coopLocal'], [1, 100], ['pc'], 'free', 0, [5, 2000], 5, 5, 90, ['adrenaline', 'compete', 'nostalgia'], { ru: 'Идеальный круг за 30 секунд и вечное «ещё раз»: аркада для перфекционистов.', en: 'A perfect lap in thirty seconds and eternal retries: arcade for perfectionists.' }, { coopQ: 7 }),
  g('Art of Rally', 2020, 'Funselektor', ['racing', 'simulator'], ['driving', 'relaxing', 'nostalgia', 'colorful', 'soundtrack', 'slow'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch', 'mobile'], 'cheap', 900, [8, 40], 4, 3, 84, ['relax', 'nostalgia', 'adrenaline'], { ru: 'Минималистичное ралли 80-х: скользить по гравию под спокойную музыку.', en: 'Minimalist eighties rally: sliding on gravel to calm music.' }),
  g('Hot Wheels Unleashed 2', 2023, 'Milestone', ['racing', 'party'], ['driving', 'colorful', 'coopfocused', 'splitscreen', 'family', 'collect'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal', 'pvpLocal'], [1, 12], ['pc', 'ps', 'xbox', 'switch'], 'mid', 2490, [8, 100], 3, 4, 78, ['adrenaline', 'laugh', 'collect'], { ru: 'Машинки с петлями по квартире: детская радость и очень злые трассы.', en: 'Loop-the-loop toy cars in a flat: childhood joy and vicious tracks.' }, { coopQ: 9 }),

  /* ----------------------------- спорт ----------------------------- */
  g('EA Sports FC 25', 2024, 'EA Vancouver', ['sports', 'simulator'], ['realistic', 'pvpfocused', 'coopfocused', 'timegate', 'mtx'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal'], [1, 22], ['pc', 'ps', 'xbox', 'switch'], 'full', 5490, [20, 1000], 3, 3, 71, ['compete', 'progress'], { ru: 'Футбол раз в год: карьера, Ultimate Team и вечный спор про физику мяча.', en: 'Football every year: career, Ultimate Team and the eternal ball physics debate.' }, { coopQ: 8 }),
  g('Tony Hawk’s Pro Skater 1 + 2', 2020, 'Vicarious Visions', ['sports', 'action'], ['soundtrack', 'nostalgia', 'replayable', 'parkour', 'colorful'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal', 'pvpLocal'], [1, 8], ['pc', 'ps', 'xbox', 'switch'], 'mid', 2490, [8, 60], 3, 4, 89, ['adrenaline', 'nostalgia', 'progress'], { ru: 'Панк-саундтрек, комбо на миллион и бесконечные рестарты трюка.', en: 'Punk soundtrack, million-point combos and endless trick restarts.' }, { coopQ: 8 }),
  g('WWE 2K24', 2024, 'Visual Concepts', ['sports', 'fighting'], ['cinematic', 'coopfocused', 'splitscreen', 'wacky', 'storyrich'], ['solo', 'coopLocal', 'pvpLocal', 'pvpOnline'], [1, 6], ['pc', 'ps', 'xbox'], 'full', 5490, [15, 200], 3, 3, 76, ['laugh', 'adrenaline', 'create'], { ru: 'Рестлинг-шоу, редактор персонажей и самое весёлое совместное безумие.', en: 'A wrestling show, a character editor and gloriously silly shared chaos.' }, { coopQ: 9 }),
  g('Golf It!', 2017, 'Pirate Software', ['sports', 'party'], ['funny', 'coopfocused', 'lobbybig', 'physics', 'mods', 'lowsysreq'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal'], [1, 12], ['pc'], 'cheap', 500, [3, 100], 2, 2, 82, ['laugh', 'relax'], { ru: 'Гольф, который портится друзьями: карты создают сами игроки.', en: 'Golf ruined by your friends: the community builds the courses.' }, { coopQ: 9 }),

  /* ----------------------------- стелс и детективы ----------------------------- */
  g('Splinter Cell: Chaos Theory', 2005, 'Ubisoft', ['stealth', 'action'], ['espionage', 'tense', 'storyrich', 'coopfocused', 'nostalgia', 'difficult'], ['solo', 'coopOnline'], [1, 4], ['pc', 'ps', 'xbox'], 'cheap', 400, [10, 20], 4, 3, 92, ['think', 'tense', 'nostalgia'], { ru: 'Сэм Фишер в лучшей форме: свет, шум и идеальный кооп из двух агентов.', en: 'Sam Fisher at his best: light, noise and a superb two-agent co-op.' }, { coopQ: 9 }),
  g('Hitman: Blood Money', 2006, 'IO Interactive', ['stealth', 'action', 'simulator', 'sandbox'], ['crime', 'funny', 'replayable', 'nostalgia'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch', 'mobile'], 'cheap', 500, [10, 30], 4, 3, 90, ['think', 'laugh', 'nostalgia'], { ru: 'Убийства как искусство импровизации: газеты потом напишут о ваших ошибках.', en: 'Assassination as improvisation: newspapers will report your mistakes.' }),
  g('Shadow Tactics: Blades of the Shogun', 2016, 'Mimimi Games', ['stealth', 'strategy', 'tactics'], ['tbs', 'historical', 'difficult', 'squad', 'puzzles'], ['solo'], [1, 1], ['pc', 'ps', 'xbox'], 'mid', 1990, [20, 40], 5, 2, 88, ['think', 'tense'], { ru: 'Пять персонажей, одна ошибка и перезагрузка: тактический стелс без права на шум.', en: 'Five characters, one mistake and a reload: tactical stealth with no room for noise.' }),
  g('Her Story', 2015, 'Sam Barlow', ['mystery', 'visual', 'puzzle'], ['dialogheavy', 'short', 'storyrich', 'philosophical', 'crime'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch', 'mobile'], 'cheap', 700, [3, 6], 4, 1, 82, ['think', 'story', 'feel'], { ru: 'Искать слова в полицейских допросах и собирать правду из фрагментов.', en: 'Search keywords in police interviews and rebuild the truth from fragments.' }),
  g('Paradise Killer', 2020, 'Kaizen Game Works', ['mystery', 'adventure'], ['surreal', 'soundtrack', 'openworld', 'surreal', 'colorful', 'crime'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch'], 'cheap', 900, [8, 15], 3, 1, 84, ['think', 'explore', 'laugh'], { ru: 'Убийство на острове богов и вапора-саундтрек десятилетия.', en: 'A murder on an island of gods and a decade-defining vapourwave soundtrack.' }),
  g('Case of the Golden Idol', 2022, 'Color Gray Games', ['mystery', 'puzzle'], ['puzzles', 'pixelart', 'historical', 'dark', 'short', 'philosophical'], ['solo'], [1, 1], ['pc', 'ps', 'xbox', 'switch', 'mobile'], 'cheap', 900, [6, 12], 4, 1, 88, ['think', 'story'], { ru: 'Двенадцать смертей и одна монета: самая умная дедукция последних лет.', en: 'Twelve deaths and one coin: the cleverest deduction game in years.' }),

  /* ----------------------------- MOBA, королевские битвы, идлы ----------------------------- */
  g('PUBG Mobile', 2018, 'Tencent', ['battle', 'shooter'], ['battleroyale', 'touch', 'coopfocused', 'crosplay', 'lowsysreq', 'voicechat'], ['pvpOnline', 'coopOnline'], [1, 100], ['mobile'], 'free', 0, [15, 2000], 3, 5, 76, ['adrenaline', 'compete', 'laugh'], { ru: 'Королевская битва в кармане: сотня игроков и одна кастрюля на всю команду.', en: 'Battle royale in your pocket: a hundred players and one frying pan for the team.' }, { coopQ: 9 }),
  g('Melvor Idle', 2021, 'Games by Malcs', ['idle', 'rpg'], ['offline', 'endless', 'grind', 'lowsysreq', 'learn'], ['solo'], [1, 1], ['pc', 'mobile'], 'cheap', 900, [50, 5000], 1, 1, 85, ['progress', 'relax', 'think', 'learn'], { ru: 'RuneScape без кликов: прогресс идёт в фоне и не отпускает.', en: 'RuneScape without clicking: background progress that will not let go.' }),
  g('Cookie Clicker', 2013, 'Orteil', ['idle', 'simulator'], ['endlessloop', 'funny', 'wacky', 'timegate', 'collect'], ['solo'], [1, 1], ['pc', 'mobile'], 'free', 0, [5, 5000], 1, 1, 82, ['progress', 'laugh'], { ru: 'Печенье, бабушки и метафизика: родоначальник жанра и ловушка на годы.', en: 'Cookies, grandmas and metaphysics: the genre founder and a years-long trap.' }),

  /* ----------------------------- настольные и вечеринки ----------------------------- */
  g('Tabletop Simulator', 2015, 'Berserk Games', ['boardgame', 'simulator', 'party', 'sandbox'], ['mods', 'voicechat', 'lobbybig'], ['solo', 'coopOnline', 'pvpOnline'], [1, 10], ['pc'], 'mid', 1990, [10, 1000], 2, 1, 89, ['laugh', 'create', 'learn'], { ru: 'Мастерская со всеми настолками мира: физика, моды и вечный хаос.', en: 'A workshop with every board game on earth: physics, mods and eternal chaos.' }, { coopQ: 9 }),
  g('Gloomhaven', 2022, 'Flaming Fowl Studios', ['boardgame', 'tactics', 'rpg'], ['tbs', 'fantasy', 'coopfocused', 'long', 'difficult', 'deckbuilding'], ['solo', 'coopOnline'], [1, 4], ['pc', 'ps', 'xbox', 'switch'], 'mid', 2490, [50, 200], 4, 2, 82, ['think', 'progress', 'story'], { ru: 'Легендарная настольная кампания в цифре: сценарии, карты и решения на годы.', en: 'The legendary tabletop campaign digitised: scenarios, cards and years of decisions.' }, { coopQ: 9 }),
  g('Ticket to Ride', 2004, 'Days of Wonder', ['boardgame', 'strategy'], ['easytolearn', 'family', 'colorful', 'relaxing', 'touch'], ['solo', 'coopOnline', 'pvpOnline', 'coopLocal'], [1, 5], ['pc', 'ps', 'xbox', 'switch', 'mobile'], 'cheap', 700, [1, 100], 2, 1, 84, ['relax', 'think', 'compete'], { ru: 'Поезда, маршруты и мягкая борьба за длинные перегоны: классика настолок.', en: 'Trains, routes and gentle fights over long stretches: a board-game classic.' }, { coopQ: 9 }),
  g('Codenames', 2015, 'CGE Digital', ['boardgame', 'party'], ['social', 'voicechat', 'easytolearn', 'lobbybig', 'family'], ['coopOnline', 'coopLocal', 'pvpOnline'], [2, 8], ['pc', 'mobile'], 'cheap', 400, [1, 50], 2, 2, 82, ['laugh', 'think'], { ru: 'Ассоциации, которые обязаны быть понятны своей команде и никому больше.', en: 'Clues that must make sense to your team and nobody else.' }, { coopQ: 10 }),

  /* ----------------------------- MMO ----------------------------- */
  g('The Elder Scrolls Online', 2014, 'ZeniMax Online', ['mmo', 'rpg'], ['mmosocial', 'openworld', 'fantasy', 'long', 'coopfocused', 'crafting', 'endless'], ['solo', 'coopOnline', 'mmo', 'pvpOnline'], [1, 500], ['pc', 'ps', 'xbox'], 'subscription', 1200, [100, 3000], 3, 3, 84, ['explore', 'story', 'progress'], { ru: 'Весь Тамриэль без подписки: сюжетные линии лучше, чем ждёшь от MMO.', en: 'All of Tamriel without a subscription: questlines better than MMO norm.' }, { coopQ: 9 }),
  g('Black Desert Online', 2016, 'Pearl Abyss', ['mmo', 'rpg', 'action'], ['mmosocial', 'grind', 'openworld', 'crafting', 'trading', 'colorful', 'endless'], ['solo', 'coopOnline', 'mmo', 'pvpOnline'], [1, 300], ['pc', 'ps', 'xbox'], 'cheap', 500, [100, 5000], 3, 4, 76, ['progress', 'create', 'adrenaline'], { ru: 'Лучшая боевая система в MMO и глубочайшая система жизни: рыбачьте или сражайтесь.', en: 'The best MMO combat and the deepest life-skills system: fish or fight.' }, { coopQ: 8 }),
  g('Star Wars: The Old Republic', 2011, 'BioWare', ['mmo', 'rpg'], ['storyrich', 'scifi', 'space', 'choices', 'dialogheavy', 'mmosocial'], ['solo', 'coopOnline', 'mmo'], [1, 500], ['pc'], 'free', 0, [60, 1000], 3, 3, 81, ['story', 'progress', 'escape'], { ru: 'Восемь классовых сюжетов с полноценной озвучкой: MMO, где пришли за историей.', en: 'Eight fully voiced class stories: an MMO you play for the story.' }, { coopQ: 8 }),
  g('Path of Exile', 2013, 'Grinding Gear Games', ['rpg', 'mmo', 'action'], ['loot', 'grind', 'hardcoresim', 'endless', 'trading', 'dark'], ['solo', 'coopOnline', 'pvpOnline'], [1, 100], ['pc', 'ps', 'xbox'], 'free', 0, [30, 3000], 5, 4, 86, ['progress', 'think', 'adrenaline'], { ru: 'Дерево талантов размером с постер и сезоны, которые затягивают на годы.', en: 'A skill tree the size of a poster and seasons that swallow years.' }, { coopQ: 8 }),

  /* ----------------------------- мобильные и облако ----------------------------- */
  g('Monopoly GO!', 2023, 'Scopely', ['boardgame', 'idle'], ['touch', 'timegate', 'mtx', 'easytolearn', 'social', 'colorful'], ['solo', 'pvpOnline'], [1, 100], ['mobile'], 'free', 0, [5, 1000], 1, 2, 70, ['laugh', 'progress', 'compete'], { ru: 'Монополия за пять минут и ограбления друзей: залипательно и беспощадно.', en: 'Monopoly in five minutes and robbing your friends: addictive and merciless.' }),
  g('Asphalt Legends Unite', 2019, 'Gameloft', ['racing'], ['driving', 'touch', 'colorful', 'pvpfocused', 'crosplay'], ['solo', 'pvpOnline', 'coopOnline'], [1, 8], ['mobile', 'pc', 'switch'], 'free', 0, [5, 1000], 3, 5, 74, ['adrenaline', 'compete'], { ru: 'Суперкары, трюки и мультиплеер на восемь человек прямо на телефоне.', en: 'Supercars, stunts and eight-player multiplayer right on your phone.' }, { coopQ: 7 }),
];
