/** Каталог, часть B — одиночные игры: сюжет, атмосфера, хардкор, хоррор. */
export const PART_B = [
  {
    t: 'Baldur\u2019s Gate 3', y: 2023, dev: 'Larian Studios', gr: ['rpg', 'tactics', 'adventure'],
    tg: ['storyrich', 'choices', 'tbs', 'fantasy', 'dialogheavy', 'squad', 'long', 'replayable', 'coopfocused', 'cinematic', 'cutscenes', 'social'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [80, 400], dif: 3, pace: 2, rat: 96, mood: ['story', 'think', 'escape'], coopQ: 9,
    desc: { ru: 'Эталонная RPG с выборами, которые реально меняют мир, и коопом на четверых с той же свободой.', en: 'The benchmark RPG where choices really change the world, with four-player co-op that keeps all the freedom.' },
  },
  {
    t: 'The Witcher 3: Wild Hunt', y: 2015, dev: 'CD Projekt Red', gr: ['rpg', 'action', 'adventure'],
    tg: ['storyrich', 'openworld', 'fantasy', 'dark', 'exploration', 'long', 'cinematic', 'cutscenes', 'dialogheavy', 'choices', 'epic', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [60, 200], dif: 3, pace: 3, rat: 93, mood: ['story', 'explore', 'escape'],
    desc: { ru: 'Охота на ведьмака по огромному континенту: лучшие побочные квесты в жанре и морально серые решения.', en: 'Witcher work across a vast continent: the best side quests in the genre and morally grey decisions.' },
  },
  {
    t: 'Cyberpunk 2077', y: 2020, dev: 'CD Projekt Red', gr: ['rpg', 'action', 'shooter'],
    tg: ['cyberpunk', 'openworld', 'storyrich', 'epic', 'photomode', 'cutscenes', 'choices', 'modern', 'gpuheavy', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [50, 150], dif: 3, pace: 4, rat: 88, mood: ['story', 'adrenaline', 'escape'],
    desc: { ru: 'Найт-Сити, имплантаты и долг перед Киану Ривзом — самая стильная RPG про будущее.', en: 'Night City, implants and a debt to Keanu Reeves: the most stylish RPG of the future.' },
  },
  {
    t: 'Elden Ring', y: 2022, dev: 'FromSoftware', gr: ['rpg', 'action'],
    tg: ['soulslike', 'difficult', 'openworld', 'dark', 'fantasy', 'exploration', 'epic', 'long', 'coopfocused', 'photomode', 'philosophical'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [60, 200], dif: 5, pace: 3, rat: 94, mood: ['adrenaline', 'explore', 'progress'], coopQ: 7,
    desc: { ru: 'Открытый фэнтези-мир, который не ведёт за руку: награда за любопытство и за терпение к смерти.', en: 'An open fantasy world that never holds your hand: rewards curiosity and patience with death.' },
  },
  {
    t: 'Dark Souls III', y: 2016, dev: 'FromSoftware', gr: ['rpg', 'action'],
    tg: ['soulslike', 'difficult', 'dark', 'fantasy', 'linear', 'epic', 'coopfocused', 'tense'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 6], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [30, 120], dif: 5, pace: 4, rat: 91, mood: ['adrenaline', 'escape'], coopQ: 7,
    desc: { ru: 'Пепел угасает, а вы снова умираете: классический соулслайк с плотнейшей боевой системой.', en: 'The fire fades and you die again: the classic soulslike with the tightest combat system.' },
  },
  {
    t: 'Sekiro: Shadows Die Twice', y: 2019, dev: 'FromSoftware', gr: ['action', 'adventure'],
    tg: ['soulslike', 'difficult', 'historical', 'linear', 'cinematic', 'epic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [30, 60], dif: 5, pace: 5, rat: 91, mood: ['adrenaline', 'story'],
    desc: { ru: 'Фехтование по ритму, шиноби в Сэнгоку и никакой прокачки уровня — чистая честная сложность.', en: 'Rhythm-based swordplay, a Sengoku shinobi and no level grinding: pure, honest difficulty.' },
  },
  {
    t: 'Bloodborne', y: 2015, dev: 'FromSoftware', gr: ['action', 'rpg', 'horror'],
    tg: ['soulslike', 'difficult', 'dark', 'tense', 'epic', 'mythology'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 3], pf: ['ps'], pr: 'mid', pv: 2490,
    len: [35, 90], dif: 5, pace: 5, rat: 92, mood: ['adrenaline', 'scare'], coopQ: 6,
    desc: { ru: 'Викторианский кошмар Лавкрафта: страх как механика и агрессивный бой без щитов.', en: 'A Victorian Lovecraftian nightmare: fear as a mechanic and aggressive combat without shields.' },
  },
  {
    t: 'Lies of P', y: 2023, dev: 'Round8', gr: ['action', 'rpg'],
    tg: ['soulslike', 'difficult', 'dark', 'linear', 'cinematic', 'soundtrack', 'epic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [30, 60], dif: 5, pace: 4, rat: 82, mood: ['adrenaline', 'story'], gp: 1,
    desc: { ru: 'Пиноккио-соулслайк в стиле Belle Époque: красиво, жёстко и с отличными боссами.', en: 'A Pinocchio soulslike in Belle Époque style: gorgeous, brutal and full of great bosses.' },
  },
  {
    t: 'Black Myth: Wukong', y: 2024, dev: 'Game Science', gr: ['action', 'rpg'],
    tg: ['mythology', 'difficult', 'epic', 'photomode', 'cinematic', 'fantasy', 'epic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [30, 60], dif: 4, pace: 5, rat: 82, mood: ['adrenaline', 'story'],
    desc: { ru: 'Китайская мифология и бои на посохах против 70+ боссов — зрелищный экшен про Царя обезьян.', en: 'Chinese mythology and staff combat against 70+ bosses: a spectacular Monkey King action game.' },
  },
  {
    t: 'God of War (2018)', y: 2018, dev: 'Santa Monica Studio', gr: ['action', 'adventure'],
    tg: ['storyrich', 'mythology', 'epic', 'cinematic', 'cutscenes', 'photomode', 'dark', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 2490,
    len: [25, 60], dif: 4, pace: 4, rat: 94, mood: ['story', 'adrenaline'],
    desc: { ru: 'Кратос взрослеет вместе с сыном: один непрерывный кадр, топор, что возвращается, и скандинавские мифы.', en: 'Kratos grows up alongside his son: one continuous shot, a returning axe and Norse myth.' },
  },
  {
    t: 'God of War Ragnar\u00f6k', y: 2022, dev: 'Santa Monica Studio', gr: ['action', 'adventure'],
    tg: ['storyrich', 'mythology', 'epic', 'cinematic', 'cutscenes', 'photomode', 'long'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [35, 80], dif: 4, pace: 4, rat: 92, mood: ['story', 'adrenaline'],
    desc: { ru: 'Все девять миров на грани Рагнарёка, а Кратос пытается не повторить свою судьбу.', en: 'All nine realms on the brink of Ragnarok while Kratos tries not to repeat his own fate.' },
  },
  {
    t: 'The Last of Us Part I', y: 2022, dev: 'Naughty Dog', gr: ['action', 'adventure', 'horror'],
    tg: ['storyrich', 'sad', 'zombie', 'tense', 'linear', 'cinematic', 'cutscenes', 'epic', 'photomode'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [15, 25], dif: 3, pace: 4, rat: 89, mood: ['story', 'feel', 'tense'],
    desc: { ru: 'Джоэл и Элли идут через погибший мир: лучший пример, как игра может рассказать историю.', en: 'Joel and Ellie cross a dead world: the best example of games telling a story.' },
  },
  {
    t: 'The Last of Us Part II Remastered', y: 2024, dev: 'Naughty Dog', gr: ['action', 'adventure', 'horror'],
    tg: ['storyrich', 'sad', 'zombie', 'tense', 'cinematic', 'cutscenes', 'epic', 'difficult', 'photomode'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [25, 40], dif: 4, pace: 4, rat: 89, mood: ['story', 'feel', 'tense'],
    desc: { ru: 'Месть, которая никого не делает счастливым: технически безупречный и эмоционально тяжёлый опыт.', en: 'Revenge that makes nobody happy: technically flawless and emotionally brutal.' },
  },
  {
    t: 'Red Dead Redemption 2', y: 2018, dev: 'Rockstar Games', gr: ['action', 'adventure'],
    tg: ['openworld', 'storyrich', 'historical', 'slow', 'epic', 'long', 'cinematic', 'photomode', 'realistic', 'soundtrack'],
    md: ['solo', 'pvpOnline'], pl: [1, 32], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [60, 250], dif: 3, pace: 2, rat: 94, mood: ['story', 'explore', 'escape'],
    desc: { ru: 'Закат эпохи бандитов на Диком Западе: медленно, красиво и очень больно к финалу.', en: 'The sunset of the outlaw era in the Wild West: slow, beautiful and deeply painful by the end.' },
  },
  {
    t: 'Grand Theft Auto V', y: 2013, dev: 'Rockstar Games', gr: ['action', 'adventure'],
    tg: ['openworld', 'modern', 'funny', 'epic', 'grind', 'long', 'mmosocial', 'replayable', 'coopfocused'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 30], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [30, 300], dif: 2, pace: 4, rat: 92, mood: ['laugh', 'adrenaline', 'escape'], coopQ: 8,
    desc: { ru: 'Три бандита, один город и Online, где каждый вечер находится новая авантюра с друзьями.', en: 'Three criminals, one city, and an Online mode with a fresh scheme every evening with friends.' },
  },
  {
    t: 'Uncharted 4: A Thief\u2019s End', y: 2016, dev: 'Naughty Dog', gr: ['action', 'adventure'],
    tg: ['storyrich', 'epic', 'cinematic', 'linear', 'exploration', 'cutscenes', 'funny', 'photomode'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 1990,
    len: [15, 35], dif: 3, pace: 4, rat: 90, mood: ['story', 'adrenaline', 'explore'],
    desc: { ru: 'Приключение в духе Индианы Джонса: обвалы, джунгли и братья, которым есть что делить.', en: 'Indiana Jones in game form: collapses, jungles and brothers with history between them.' },
  },
  {
    t: 'Marvel\u2019s Spider-Man 2', y: 2023, dev: 'Insomniac Games', gr: ['action', 'adventure'],
    tg: ['openworld', 'epic', 'cinematic', 'easytolearn', 'modern', 'photomode', 'storyrich', 'colorful'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [20, 45], dif: 2, pace: 5, rat: 88, mood: ['adrenaline', 'story', 'laugh'],
    desc: { ru: 'Полёты между небоскрёбами как лучшая механика в супергероике, плюс двое пауков сразу.', en: 'Web-swinging between skyscrapers is the best superhero mechanic, now with two Spider-Men.' },
  },
  {
    t: 'Batman: Arkham Knight', y: 2015, dev: 'Rocksteady', gr: ['action', 'adventure'],
    tg: ['openworld', 'dark', 'cinematic', 'epic', 'photomode', 'modern'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1500,
    len: [20, 50], dif: 3, pace: 4, rat: 87, mood: ['adrenaline', 'story'],
    desc: { ru: 'Бэтмобиль, масса свободной боевой системы и лучший силуэт Готэма ночью.', en: 'The Batmobile, a massively free-flow combat system and Gotham\u2019s best night silhouette.' },
  },
  {
    t: 'Ghost of Tsushima', y: 2020, dev: 'Sucker Punch', gr: ['action', 'adventure'],
    tg: ['openworld', 'historical', 'epic', 'photomode', 'exploration', 'cinematic', 'soundtrack'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [30, 70], dif: 3, pace: 4, rat: 89, mood: ['explore', 'story', 'adrenaline'], coopQ: 7,
    desc: { ru: 'Самурай против монгольского нашествия: ветер вместо маркеров и самый красивый исследуемый остров.', en: 'A samurai against the Mongol invasion: wind instead of markers and the most beautiful island to explore.' },
  },
  {
    t: 'Horizon Forbidden West', y: 2022, dev: 'Guerilla Games', gr: ['action', 'rpg', 'adventure'],
    tg: ['openworld', 'scifi', 'exploration', 'photomode', 'storyrich', 'epic', 'long', 'colorful'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [30, 80], dif: 3, pace: 4, rat: 89, mood: ['explore', 'story', 'adrenaline'],
    desc: { ru: 'Роботизированные динозавры и луки: исследование постапокалиптического Золотого Запада.', en: 'Robot dinosaurs and bows: exploring the post-apocalyptic frontier.' },
  },
  {
    t: 'Death Stranding', y: 2019, dev: 'Kojima Productions', gr: ['adventure', 'simulator'],
    tg: ['walkingsim', 'scifi', 'philosophical', 'slow', 'relaxing', 'long', 'photomode', 'social', 'epic'],
    md: ['solo', 'async'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 2490,
    len: [40, 100], dif: 3, pace: 1, rat: 84, mood: ['relax', 'explore', 'story'],
    desc: { ru: 'Курьер через опустевшую Америку: медитативная логистика, страннейший сюжет и лестницы от других игроков.', en: 'A courier across an empty America: meditative logistics, a bizarre plot and ladders from other players.' },
  },
  {
    t: 'Control', y: 2019, dev: 'Remedy', gr: ['action', 'adventure', 'shooter'],
    tg: ['scifi', 'tense', 'epic', 'photomode', 'philosophical', 'dark', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1500,
    len: [15, 30], dif: 3, pace: 4, rat: 85, mood: ['story', 'adrenaline'],
    desc: { ru: 'Брутализм, телекинез и здание, которое меняет геометрию — самый странный экшен Remedy.', en: 'Brutalism, telekinesis and a building that shifts geometry: Remedy at their strangest.' },
  },
  {
    t: 'Alan Wake 2', y: 2023, dev: 'Remedy', gr: ['horror', 'adventure', 'shooter'],
    tg: ['storyrich', 'dark', 'tense', 'cinematic', 'photomode', 'epic', 'choices', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [20, 30], dif: 3, pace: 3, rat: 88, mood: ['story', 'scare', 'think'],
    desc: { ru: 'Детектив и писатель распутывают одну историю: FMV-сцены, мюзикл и настоящий северный хоррор.', en: 'A detective and a writer untangle one story: FMV scenes, a musical and genuine Nordic horror.' },
  },
  {
    t: 'Resident Evil 4 Remake', y: 2023, dev: 'Capcom', gr: ['horror', 'shooter', 'action'],
    tg: ['tense', 'epic', 'replayable', 'cinematic', 'difficult', 'zombie', 'loot'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [15, 40], dif: 4, pace: 5, rat: 93, mood: ['adrenaline', 'scare'], gp: 1,
    desc: { ru: 'Сельская Испания, топор в спину и чемоданы инвентаря: эталонный ремейк классики.', en: 'Rural Spain, an axe in your back and attache-case inventory: the gold standard remake.' },
  },
  {
    t: 'Resident Evil 2 Remake', y: 2019, dev: 'Capcom', gr: ['horror', 'survival'],
    tg: ['tense', 'zombie', 'dark', 'difficult', 'replayable', 'linear', 'puzzles'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [10, 30], dif: 4, pace: 4, rat: 91, mood: ['scare', 'think'],
    desc: { ru: 'Раккун-Сити, полицейский участок и мистер X, который не перестаёт идти за вами.', en: 'Raccoon City, the police station and Mr. X, who never stops walking after you.' },
  },
  {
    t: 'Silent Hill 2 (2024)', y: 2024, dev: 'Bloober Team', gr: ['horror', 'adventure'],
    tg: ['storyrich', 'sad', 'dark', 'tense', 'philosophical', 'cinematic', 'slow'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [15, 25], dif: 3, pace: 2, rat: 87, mood: ['scare', 'feel', 'story', 'think'],
    desc: { ru: 'Туман, письмо от жены и монстры, которые говорят о вашей вине: ремейк главного психологического хоррора.', en: 'Fog, a letter from your wife and monsters that speak of your guilt: a remake of the definitive psychological horror.' },
  },
  {
    t: 'Alien: Isolation', y: 2014, dev: 'Creative Assembly', gr: ['horror', 'stealth', 'shooter'],
    tg: ['scifi', 'tense', 'difficult', 'long', 'cinematic', 'dark'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1200,
    len: [18, 30], dif: 5, pace: 3, rat: 81, mood: ['scare', 'tense'],
    desc: { ru: 'Чужой не скриптуется, а охотится: 20 часов непрерывного напряжения в стиле первого фильма.', en: 'The alien does not script: it hunts. Twenty hours of unbroken tension in the style of the first film.' },
  },
  {
    t: 'Dead Space (2023)', y: 2023, dev: 'Motive', gr: ['horror', 'shooter', 'action'],
    tg: ['scifi', 'tense', 'epic', 'cinematic', 'photomode', 'dark'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [12, 25], dif: 4, pace: 4, rat: 89, mood: ['scare', 'adrenaline'],
    desc: { ru: 'Космический хоррор на разваливающемся корабле: расчленение как основная механика.', en: 'Space horror on a collapsing ship where dismemberment is the core mechanic.' },
  },
  {
    t: 'SOMA', y: 2015, dev: 'Frictional Games', gr: ['horror', 'adventure'],
    tg: ['scifi', 'philosophical', 'dark', 'tense', 'underwater', 'walkingsim', 'storyrich'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'cheap', pv: 900,
    len: [9, 15], dif: 2, pace: 2, rat: 84, mood: ['think', 'scare', 'story'],
    desc: { ru: 'Подводная станция и вопрос, что значит быть человеком: страшно и очень умно.', en: 'An underwater station and the question of what makes you human: terrifying and very smart.' },
  },
  {
    t: 'Outlast', y: 2013, dev: 'Red Barrels', gr: ['horror', 'survival'],
    tg: ['tense', 'short', 'dark', 'difficult', 'linear', 'tense'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 500,
    len: [6, 10], dif: 4, pace: 4, rat: 80, mood: ['scare'],
    desc: { ru: 'Бежать и снимать на камеру: хоррор без оружия, где единственный враг — вы сами и ваша паника.', en: 'Run and film: horror without weapons where your only enemy is your own panic.' },
  },
  {
    t: 'Amnesia: The Bunker', y: 2023, dev: 'Frictional Games', gr: ['horror', 'survival'],
    tg: ['tense', 'dark', 'short', 'procedural', 'difficult', 'historical', 'puzzles'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1200,
    len: [5, 10], dif: 4, pace: 3, rat: 84, mood: ['scare', 'tense'],
    desc: { ru: 'Подземный бункер Первой мировой, генератор и зверь, который слышит каждый ваш шаг.', en: 'A WWI bunker, a generator and a beast that hears every step you take.' },
  },
  {
    t: 'Subnautica', y: 2018, dev: 'Unknown Worlds', gr: ['survival', 'adventure', 'sandbox'],
    tg: ['underwater', 'exploration', 'crafting', 'basebuilding', 'tense', 'relaxing', 'storyrich', 'colorful', 'openworld'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [30, 60], dif: 3, pace: 2, rat: 92, mood: ['explore', 'scare', 'relax'],
    desc: { ru: 'Океанская планета без карты и оружия: красота на глубине 20 метров и ужас на глубине 200.', en: 'An ocean planet with no map and no weapons: beauty at 20 meters, dread at 200.' },
  },
  {
    t: 'The Long Dark', y: 2017, dev: 'Hinterland', gr: ['survival', 'simulator'],
    tg: ['hardcoresim', 'permadeath', 'difficult', 'slow', 'relaxing', 'tense', 'cozy', 'exploration'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [20, 500], dif: 5, pace: 1, rat: 84, mood: ['relax', 'tense', 'escape'],
    desc: { ru: 'Тихая канадская зима и одна ошибка, которая стоит всего: медитация о выживании в одиночестве.', en: 'A quiet Canadian winter and one mistake that costs everything: a meditation on solo survival.' },
  },
  {
    t: 'Hollow Knight', y: 2017, dev: 'Team Cherry', gr: ['metroidvania', 'platformer', 'action'],
    tg: ['difficult', 'dark', 'exploration', 'cute', 'handdrawn', 'lowsysreq', 'soundtrack', 'long', 'epic', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 500,
    len: [30, 60], dif: 4, pace: 3, rat: 95, mood: ['explore', 'adrenaline', 'story'],
    desc: { ru: 'Подземное королевство насекомых, нарисованное от руки: исследование, боссы и грусть.', en: 'A hand-drawn underground kingdom of insects: exploration, bosses and melancholy.' },
  },
  {
    t: 'Ori and the Will of the Wisps', y: 2020, dev: 'Moon Studios', gr: ['platformer', 'metroidvania', 'adventure'],
    tg: ['sad', 'photomode', 'epic', 'soundtrack', 'handdrawn', 'exploration', 'colorful', 'cinematic', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [12, 25], dif: 4, pace: 4, rat: 90, mood: ['story', 'feel', 'escape', 'adrenaline'], gp: 1,
    desc: { ru: 'Плач по умирающему лесу: музыка, платформинг и эмоции в каждой сцене.', en: 'A lament for a dying forest: music, platforming and emotion in every frame.' },
  },
  {
    t: 'Celeste', y: 2018, dev: 'Extremely OK Games', gr: ['platformer', 'action'],
    tg: ['difficult', 'storyrich', 'short', 'pixelart', 'lowsysreq', 'soundtrack', 'philosophical', 'easytolearn', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 700,
    len: [8, 30], dif: 5, pace: 5, rat: 92, mood: ['adrenaline', 'story'],
    desc: { ru: 'Прыжки по горе и история о тревоге: сложно, честно и лечит лучше терапии.', en: 'Climbing a mountain and a story about anxiety: hard, fair and more healing than therapy.' },
  },
  {
    t: 'Hades', y: 2020, dev: 'Supergiant Games', gr: ['roguelike', 'action', 'rpg'],
    tg: ['mythology', 'replayable', 'storyrich', 'dialogheavy', 'soundtrack', 'colorful', 'endlessloop', 'difficult', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1200,
    len: [25, 100], dif: 4, pace: 5, rat: 93, mood: ['adrenaline', 'story', 'progress'], gp: 1,
    desc: { ru: 'Побег из подземного мира, где каждая смерть двигает сюжет и открывает новые диалоги.', en: 'Escaping the underworld where every death advances the plot and unlocks new dialogue.' },
  },
  {
    t: 'Hades II', y: 2024, dev: 'Supergiant Games', gr: ['roguelike', 'action', 'rpg'],
    tg: ['mythology', 'replayable', 'storyrich', 'soundtrack', 'colorful', 'endlessloop', 'difficult', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'switch'], pr: 'mid', pv: 1990,
    len: [25, 100], dif: 4, pace: 5, rat: 89, mood: ['adrenaline', 'story', 'progress'],
    desc: { ru: 'Медея против титанов: тот же формула «ещё один забег», но с магией и новыми богами.', en: 'Melinoe against the Titans: the same one-more-run formula with magic and new gods.' },
  },
  {
    t: 'Dead Cells', y: 2018, dev: 'Motion Twin', gr: ['roguelike', 'action', 'platformer'],
    tg: ['procedural', 'difficult', 'replayable', 'pixelart', 'endlessloop', 'lowsysreq', 'replayable', 'steamdeck', 'controller'],
    md: ['solo', 'coopLocal'], pl: [1, 2], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1500,
    len: [20, 200], dif: 4, pace: 5, rat: 89, mood: ['adrenaline', 'progress'], coopQ: 6,
    desc: { ru: 'Метроидвания-рогалик с лучшим ощущением от боя: умирать приятно, потому что растёшь.', en: 'A metroidvania roguelike with the best combat feel: dying is fine because you keep growing.' },
  },
  {
    t: 'Slay the Spire', y: 2019, dev: 'Mega Crit', gr: ['card', 'roguelike', 'strategy'],
    tg: ['deckbuilding', 'endlessloop', 'difficult', 'replayable', 'lowsysreq', 'puzzles', 'procedural', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1100,
    len: [15, 500], dif: 4, pace: 2, rat: 93, mood: ['think', 'progress'],
    desc: { ru: 'Карточный рогалик, определивший жанр: строить колоду, считать ходы, страдать от плохих реликвий.', en: 'The card roguelike that defined the genre: build a deck, count turns, suffer bad relics.' },
  },
  {
    t: 'Balatro', y: 2024, dev: 'LocalThunk', gr: ['card', 'roguelike', 'puzzle'],
    tg: ['deckbuilding', 'endlessloop', 'lowsysreq', 'easytolearn', 'difficult', 'pixelart', 'replayable', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 800,
    len: [10, 500], dif: 3, pace: 2, rat: 92, mood: ['think', 'progress', 'relax'],
    desc: { ru: 'Покер плюс джокеры: одна партия — минута, но остановиться невозможно.', en: 'Poker plus jokers: one run takes a minute, but stopping is impossible.' },
  },
  {
    t: 'The Binding of Isaac: Repentance', y: 2021, dev: 'Nicalis', gr: ['roguelike', 'action'],
    tg: ['dark', 'difficult', 'procedural', 'replayable', 'endlessloop', 'pixelart', 'loot', 'philosophical', 'steamdeck', 'controller'],
    md: ['solo', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1900,
    len: [30, 1000], dif: 5, pace: 4, rat: 87, mood: ['progress', 'escape', 'adrenaline'], coopQ: 6,
    desc: { ru: 'Слёзы младенца против библейских кошмаров: сотни предметов и тысячи часов на 100%.', en: 'A baby\u2019s tears against biblical nightmares: hundreds of items and thousands of hours to 100%.' },
  },
  {
    t: 'Return of the Obra Dinn', y: 2018, dev: 'Lucas Pope', gr: ['puzzle', 'mystery', 'adventure'],
    tg: ['historical', 'short', 'lowsysreq', 'philosophical', 'pixelart', 'puzzles'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1100,
    len: [8, 12], dif: 4, pace: 1, rat: 90, mood: ['think', 'story'],
    desc: { ru: 'Страховой детектив на корабле мертвецов: вы сами должны вывести судьбу каждого из 60 человек.', en: 'An insurance investigator on a ship of the dead: you must deduce all 60 fates yourself.' },
  },
  {
    t: 'Outer Wilds', y: 2019, dev: 'Mobius Digital', gr: ['adventure', 'mystery', 'puzzle'],
    tg: ['space', 'exploration', 'philosophical', 'relaxing', 'tense', 'short', 'soundtrack', 'storyrich'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [20, 30], dif: 3, pace: 2, rat: 94, mood: ['explore', 'think', 'escape'],
    desc: { ru: '22 минуты до конца вселенной: прокачивается не персонаж, а ваши знания о мире.', en: 'Twenty-two minutes until the universe ends: the only progression is your own knowledge.' },
  },
  {
    t: 'Disco Elysium', y: 2019, dev: 'ZA/UM', gr: ['rpg', 'adventure'],
    tg: ['storyrich', 'dialogheavy', 'philosophical', 'dark', 'funny', 'modern', 'choices', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [25, 50], dif: 3, pace: 1, rat: 93, mood: ['story', 'think'],
    desc: { ru: 'Детектив с похмельем, где драка — это диалог: лучший текст в истории игр.', en: 'A hungover detective where fighting means talking: the best writing in games.' },
  },
  {
    t: 'Undertale', y: 2015, dev: 'Toby Fox', gr: ['rpg', 'adventure'],
    tg: ['funny', 'sad', 'short', 'philosophical', 'cute', 'pixelart', 'lowsysreq', 'soundtrack', 'choices', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 500,
    len: [8, 20], dif: 3, pace: 3, rat: 92, mood: ['story', 'feel', 'laugh', 'think'],
    desc: { ru: 'Можно никого не убивать: RPG, которая помнит каждое ваше решение и отвечает на него.', en: 'You can spare everyone: an RPG that remembers every choice and answers it.' },
  },
  {
    t: 'NieR: Automata', y: 2017, dev: 'PlatinumGames', gr: ['action', 'rpg'],
    tg: ['philosophical', 'sad', 'anime', 'epic', 'soundtrack', 'storyrich', 'replayable', 'cutscenes'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [30, 60], dif: 3, pace: 5, rat: 90, mood: ['story', 'feel', 'think', 'adrenaline'],
    desc: { ru: 'Андроиды, философия и пять концовок: игра, которую надо пройти дважды, чтобы понять.', en: 'Androids, philosophy and five endings: a game you must finish twice to understand.' },
  },
  {
    t: 'Persona 5 Royal', y: 2019, dev: 'Atlus', gr: ['rpg', 'adventure', 'tactics'],
    tg: ['jrpg', 'anime', 'tbs', 'storyrich', 'long', 'soundtrack', 'social', 'choices', 'cinematic', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'full', pv: 3990,
    len: [80, 130], dif: 3, pace: 2, rat: 93, mood: ['story', 'escape', 'progress'], gp: 1,
    desc: { ru: 'Японские школьники меняют мир изнутри дворца украденных сердец: стиль и музыка на максимум.', en: 'Japanese students change the world from inside palaces of stolen hearts: maximum style and music.' },
  },
  {
    t: 'Metaphor: ReFantazio', y: 2024, dev: 'Atlus', gr: ['rpg', 'adventure'],
    tg: ['jrpg', 'fantasy', 'tbs', 'storyrich', 'long', 'soundtrack', 'choices', 'social', 'anime'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [70, 100], dif: 3, pace: 3, rat: 91, mood: ['story', 'escape', 'progress'],
    desc: { ru: 'Фэнтезийные выборы короля от авторов Persona: политика, демоны и календарь на 5 месяцев.', en: 'A fantasy royal election from the Persona team: politics, demons and a five-month calendar.' },
  },
  {
    t: 'Yakuza: Like a Dragon', y: 2020, dev: 'Ryu Ga Gotoku', gr: ['rpg', 'adventure', 'action'],
    tg: ['jrpg', 'funny', 'modern', 'storyrich', 'tbs', 'long', 'cinematic', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [45, 100], dif: 3, pace: 3, rat: 88, mood: ['story', 'laugh', 'escape'], gp: 1,
    desc: { ru: 'Бывший якудза становится героем пошаговых боёв, а по пути поёт караоке и ловит покемонов.', en: 'An ex-yakuza becomes a turn-based hero while singing karaoke and collecting creatures.' },
  },
  {
    t: 'Stardew Valley', y: 2016, dev: 'ConcernedApe', gr: ['simulator', 'rpg', 'sandbox'],
    tg: ['farming', 'cozy', 'relaxing', 'crafting', 'coopfocused', 'long', 'cute', 'pixelart', 'social', 'lowsysreq', 'mods', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 700,
    len: [50, 200], dif: 1, pace: 1, rat: 96, mood: ['relax', 'create', 'progress'], coopQ: 9,
    desc: { ru: 'Ферма, деревня и романтика: лучший способ замедлиться и провести с другом 100 спокойных часов.', en: 'A farm, a village and romance: the best way to slow down and spend 100 calm hours with a friend.' },
  },
  {
    t: 'A Short Hike', y: 2019, dev: 'adamgryu', gr: ['adventure', 'platformer'],
    tg: ['cozy', 'relaxing', 'short', 'cute', 'exploration', 'pixelart', 'lowsysreq', 'family', 'colorful', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 400,
    len: [1, 3], dif: 1, pace: 1, rat: 90, mood: ['relax', 'explore'],
    desc: { ru: 'Полтора часа в горах: идеальный «перерыв» между большими играми.', en: 'Ninety minutes in the mountains: the perfect break between big games.' },
  },
  {
    t: 'Journey', y: 2012, dev: 'thatgamecompany', gr: ['adventure', 'platformer'],
    tg: ['relaxing', 'short', 'philosophical', 'soundtrack', 'epic', 'coopfocused', 'family', 'nonviolent', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'async'], pl: [1, 2], pf: ['pc', 'ps', 'mobile'], pr: 'cheap', pv: 700,
    len: [2, 5], dif: 1, pace: 1, rat: 89, mood: ['relax', 'story', 'escape'], coopQ: 7,
    desc: { ru: 'Пустыня, музыка и безымянный попутчик: два часа, которые невозможно забыть.', en: 'A desert, music and a nameless companion: two hours you cannot forget.' },
  },
  {
    t: 'Firewatch', y: 2016, dev: 'Campo Santo', gr: ['adventure', 'mystery'],
    tg: ['walkingsim', 'storyrich', 'short', 'dialogheavy', 'relaxing', 'tense', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 900,
    len: [4, 7], dif: 1, pace: 1, rat: 84, mood: ['story', 'relax', 'think'],
    desc: { ru: 'Лето в лесу, только рация и голос на другом конце: история о побеге от прошлого.', en: 'A summer in the woods with only a radio and a voice on the other end: a story about running from the past.' },
  },
  {
    t: 'What Remains of Edith Finch', y: 2017, dev: 'Giant Sparrow', gr: ['adventure', 'mystery'],
    tg: ['walkingsim', 'storyrich', 'short', 'sad', 'philosophical', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 900,
    len: [2, 4], dif: 1, pace: 1, rat: 89, mood: ['story', 'feel', 'think', 'relax'],
    desc: { ru: 'Два часа историй одной семьи, каждая в своей механике: финал бьёт прямо в грудь.', en: 'Two hours of one family\u2019s stories, each with its own mechanic: the ending hits hard.' },
  },
  {
    t: 'Detroit: Become Human', y: 2018, dev: 'Quantic Dream', gr: ['adventure', 'mystery'],
    tg: ['scifi', 'storyrich', 'choices', 'cinematic', 'cutscenes', 'philosophical', 'epic', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 1990,
    len: [12, 25], dif: 2, pace: 3, rat: 85, mood: ['story', 'think'],
    desc: { ru: 'Три андроида, тысячи веток сюжета и постоянное «а что было бы, если…».', en: 'Three androids, thousands of story branches and constant what-ifs.' },
  },
  {
    t: 'Until Dawn', y: 2015, dev: 'Supermassive Games', gr: ['horror', 'adventure'],
    tg: ['cinematic', 'choices', 'tense', 'short', 'dark', 'coopfocused', 'cutscenes'],
    md: ['solo', 'coopLocal'], pl: [1, 8], pf: ['pc', 'ps'], pr: 'mid', pv: 1990,
    len: [8, 12], dif: 2, pace: 3, rat: 82, mood: ['scare', 'laugh'], coopQ: 9,
    desc: { ru: 'Слэшер-фильм, где вы решаете, кто доживёт до утра: идеально смотреть и играть компанией.', en: 'A slasher movie where you decide who survives: perfect to play with a crowd.' },
  },
  {
    t: 'The Quarry', y: 2022, dev: 'Supermassive Games', gr: ['horror', 'adventure'],
    tg: ['cinematic', 'choices', 'tense', 'coopfocused', 'short', 'dark', 'funny'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 8], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [8, 12], dif: 2, pace: 3, rat: 79, mood: ['scare', 'laugh'], coopQ: 9,
    desc: { ru: 'Летний лагерь, оборотни и восемь голосов за одним экраном — вечерний ритуал для компании.', en: 'Summer camp, werewolves and eight votes on one screen: a group ritual for the evening.' },
  },
  {
    t: 'The Elder Scrolls V: Skyrim', y: 2011, dev: 'Bethesda', gr: ['rpg', 'action', 'sandbox'],
    tg: ['openworld', 'fantasy', 'exploration', 'mods', 'endless', 'relaxing', 'epic', 'lowsysreq', 'long'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [50, 500], dif: 2, pace: 2, rat: 88, mood: ['explore', 'escape', 'create'],
    desc: { ru: 'Драконы, гильдии и моды: мир, в который можно возвращаться десятилетиями.', en: 'Dragons, guilds and mods: a world you can return to for decades.' },
  },
  {
    t: 'Dragon Age: The Veilguard', y: 2024, dev: 'BioWare', gr: ['rpg', 'action', 'adventure'],
    tg: ['storyrich', 'fantasy', 'choices', 'cinematic', 'dialogheavy', 'squad', 'long', 'cutscenes'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [40, 70], dif: 2, pace: 3, rat: 72, mood: ['story', 'escape'], gp: 1,
    desc: { ru: 'Команда героев против богов: классическая BioWare с романтикой и тактическими паузами.', en: 'A hero squad against gods: classic BioWare with romance and tactical pauses.' },
  },
  {
    t: 'Assassin\u2019s Creed Odyssey', y: 2018, dev: 'Ubisoft', gr: ['rpg', 'action', 'adventure'],
    tg: ['openworld', 'historical', 'mythology', 'long', 'exploration', 'photomode', 'grind'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [50, 150], dif: 3, pace: 3, rat: 84, mood: ['explore', 'adrenaline', 'escape'],
    desc: { ru: 'Древняя Греция, море и 100 часов: исследовать античный мир интереснее, чем его сюжет.', en: 'Ancient Greece, the sea and 100 hours: exploring antiquity is better than its plot.' },
  },
  {
    t: 'Armored Core VI: Fires of Rubicon', y: 2023, dev: 'FromSoftware', gr: ['action', 'shooter'],
    tg: ['mecha', 'difficult', 'scifi', 'epic', 'loot', 'tense'],
    md: ['solo', 'pvpOnline'], pl: [1, 6], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [20, 60], dif: 5, pace: 5, rat: 87, mood: ['adrenaline', 'progress'],
    desc: { ru: 'Сборка меха из сотен деталей и боссы, которых нужно разобрать по фазам.', en: 'Building a mech from hundreds of parts and bosses you must break down by phases.' },
  },
  {
    t: 'Katana ZERO', y: 2019, dev: 'Askiisoft', gr: ['action', 'platformer'],
    tg: ['cyberpunk', 'pixelart', 'difficult', 'short', 'soundtrack', 'storyrich', 'bullettime', 'lowsysreq', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 600,
    len: [5, 12], dif: 4, pace: 5, rat: 86, mood: ['adrenaline', 'story'],
    desc: { ru: 'Неонуар про наёмника с замедлением времени: идеальные 5 часов, где всё работает на ритм.', en: 'Neon noir about a hitman with bullet time: perfect five hours where everything serves the rhythm.' },
  },
];
