/** Каталог, часть A — игры для компании: кооп, онлайн, PvP, MMO. */
export const PART_A = [
  {
    t: 'Deep Rock Galactic', y: 2020, dev: 'Ghost Ship Games', gr: ['shooter', 'action', 'survival'],
    tg: ['coopfocused', 'procedural', 'loot', 'funny', 'space', 'squad', 'replayable', 'voicechat', 'mods', 'lowsysreq'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1200,
    len: [40, 400], dif: 3, pace: 4, rat: 93, mood: ['laugh', 'adrenaline', 'progress'], coopQ: 10, gp: 1,
    desc: { ru: 'Четвёрка космических гномов бурит астероиды, отбивается от жуков и держится вместе — идеальный кооп без токсичности.', en: 'Four space dwarves mine asteroids and hold the line against bugs in the friendliest co-op shooter around.' },
  },
  {
    t: 'Helldivers 2', y: 2024, dev: 'Arrowhead', gr: ['shooter', 'action'],
    tg: ['coopfocused', 'squad', 'scifi', 'epic', 'tense', 'replayable', 'voicechat', 'difficult', 'gpuheavy'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps'], pr: 'mid', pv: 2490,
    len: [50, 600], dif: 4, pace: 5, rat: 89, mood: ['adrenaline', 'laugh'], coopQ: 10,
    desc: { ru: 'Управляемая демократия, орбитальные удары и постоянные жертвы союзников — кооп, где хаос и есть веселье.', en: 'Managed democracy, orbital strikes and constant friendly fire: co-op where the chaos is the point.' },
  },
  {
    t: 'Left 4 Dead 2', y: 2009, dev: 'Valve', gr: ['shooter', 'survival', 'horror'],
    tg: ['coopfocused', 'zombie', 'tense', 'replayable', 'mods', 'splitscreen', 'lowsysreq', 'easytolearn', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'xbox'], pr: 'cheap', pv: 600,
    len: [15, 300], dif: 3, pace: 5, rat: 92, mood: ['adrenaline', 'laugh'], coopQ: 10,
    desc: { ru: 'Классика зомби-коопа: ИИ-режиссёр подкидывает паники, а четверо выживших держатся спина к спине.', en: 'The zombie co-op classic: an AI director throws panics at four survivors who must stay back to back.' },
  },
  {
    t: 'Warhammer: End Times – Vermintide 2', y: 2018, dev: 'Fatshark', gr: ['action', 'rpg'],
    tg: ['coopfocused', 'fantasy', 'dark', 'loot', 'tense', 'squad', 'replayable', 'difficult', 'soulslike'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1200,
    len: [30, 300], dif: 4, pace: 5, rat: 85, mood: ['adrenaline', 'progress'], coopQ: 10,
    desc: { ru: 'Первое лицо, ближний бой и крысиные орды: четверо против тысяч, и один опоздавший означает вайп.', en: 'First-person melee against rat hordes: four players versus thousands, and one straggler means a wipe.' },
  },
  {
    t: 'Warhammer 40,000: Darktide', y: 2022, dev: 'Fatshark', gr: ['shooter', 'action'],
    tg: ['coopfocused', 'scifi', 'dark', 'loot', 'tense', 'squad', 'replayable', 'difficult'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'xbox'], pr: 'mid', pv: 2490,
    len: [30, 300], dif: 4, pace: 5, rat: 76, mood: ['adrenaline', 'progress'], coopQ: 9,
    desc: { ru: 'Мрачный улей-город, тяжёлый отряд и постоянное давление хаоса — кооп для тех, кто любит страдать красиво.', en: 'A grim hive city, a heavy squad and constant pressure: co-op for those who suffer beautifully.' },
  },
  {
    t: 'Payday 2', y: 2013, dev: 'Overkill', gr: ['shooter', 'stealth'],
    tg: ['coopfocused', 'loot', 'replayable', 'grind', 'mods', 'lowsysreq', 'voicechat', 'difficult'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 300,
    len: [30, 600], dif: 4, pace: 4, rat: 85, mood: ['adrenaline', 'progress'], coopQ: 9,
    desc: { ru: 'Тихий налёт на банк за 40 секунд или кровавый беспредел — вся соль в командной координации.', en: 'A silent bank heist in 40 seconds or total bloodshed: it all comes down to team coordination.' },
  },
  {
    t: 'Borderlands 3', y: 2019, dev: 'Gearbox', gr: ['shooter', 'rpg'],
    tg: ['coopfocused', 'loot', 'funny', 'scifi', 'replayable', 'long', 'splitscreen', 'squad'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [30, 150], dif: 2, pace: 4, rat: 80, mood: ['laugh', 'progress', 'adrenaline'], coopQ: 8,
    desc: { ru: 'Миллиард стволов, тупые шутки и кооп на четверых — как лут-шутер и должен работать.', en: 'A billion guns, dumb jokes and four-player co-op: exactly how a looter-shooter should feel.' },
  },
  {
    t: 'Monster Hunter: World', y: 2018, dev: 'Capcom', gr: ['action', 'rpg'],
    tg: ['coopfocused', 'grind', 'loot', 'fantasy', 'epic', 'long', 'replayable', 'difficult', 'exploration', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [60, 600], dif: 4, pace: 3, rat: 89, mood: ['progress', 'adrenaline', 'escape'], coopQ: 9,
    desc: { ru: 'Охота на 30-метровых драконов вчетвером: готовиться, ловить момент, разделывать трофей.', en: 'Hunting 100-foot dragons with three friends: prepare, strike and carve the trophy.' },
  },
  {
    t: 'It Takes Two', y: 2021, dev: 'Hazelight', gr: ['platformer', 'adventure', 'puzzle'],
    tg: ['friendlier2', 'coopfocused', 'splitscreen', 'funny', 'storyrich', 'cute', 'easytolearn', 'cozy'],
    md: ['coopOnline', 'coopLocal'], pl: [2, 2], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [12, 18], dif: 2, pace: 3, rat: 89, mood: ['laugh', 'story'], coopQ: 10, gp: 1,
    desc: { ru: 'Лучшая игра строго для двоих: каждые полчаса новая механика, а другу хватит одной копии.', en: 'The definitive two-player game: a new mechanic every half hour, and a friend needs only one copy.' },
  },
  {
    t: 'Split Fiction', y: 2025, dev: 'Hazelight', gr: ['action', 'adventure', 'platformer'],
    tg: ['friendlier2', 'coopfocused', 'splitscreen', 'scifi', 'fantasy', 'funny', 'storyrich', 'epic'],
    md: ['coopOnline', 'coopLocal'], pl: [2, 2], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [14, 20], dif: 3, pace: 4, rat: 90, mood: ['laugh', 'adrenaline', 'story'], coopQ: 10,
    desc: { ru: 'Две писательницы застревают в своих же мирах — sci-fi и фэнтези переключаются каждые десять минут.', en: 'Two writers trapped in their own worlds, flipping between sci-fi and fantasy every ten minutes.' },
  },
  {
    t: 'A Way Out', y: 2018, dev: 'Hazelight', gr: ['action', 'adventure'],
    tg: ['friendlier2', 'coopfocused', 'splitscreen', 'tense', 'storyrich', 'modern'],
    md: ['coopOnline', 'coopLocal'], pl: [2, 2], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1200,
    len: [6, 8], dif: 2, pace: 3, rat: 79, mood: ['story', 'adrenaline'], coopQ: 9,
    desc: { ru: 'Побег из тюрьмы на двоих: половина игры — диалоги и доверие, вторая — погони и перестрелки.', en: 'A two-player prison break: half dialogue and trust, half chases and shootouts.' },
  },
  {
    t: 'Overcooked! 2', y: 2018, dev: 'Ghost Town Games', gr: ['party', 'action'],
    tg: ['coopfocused', 'splitscreen', 'funny', 'tense', 'easytolearn', 'cute', 'lobby4', 'wacky', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal', 'pvpLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 900,
    len: [8, 60], dif: 3, pace: 5, rat: 84, mood: ['laugh', 'adrenaline'], coopQ: 10,
    desc: { ru: 'Кухня на двух плавучих платформах и друг, который опять уронил суп, — тест ваших отношений.', en: 'A kitchen split across two rafts and a friend who dropped the soup again: a relationship stress test.' },
  },
  {
    t: 'PlateUp!', y: 2022, dev: 'It\'s Happening', gr: ['simulator', 'roguelike', 'party'],
    tg: ['coopfocused', 'replayable', 'splitscreen', 'funny', 'tense', 'management', 'easytolearn', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc', 'switch', 'ps', 'xbox'], pr: 'cheap', pv: 800,
    len: [10, 100], dif: 3, pace: 5, rat: 85, mood: ['laugh', 'progress'], coopQ: 9,
    desc: { ru: 'Рогалик-ресторан: 15 дней, растущее меню и автоматизация, которую вы строите вместе.', en: 'A roguelike restaurant: 15 days, a growing menu and automation you build together.' },
  },
  {
    t: 'Cuphead', y: 2017, dev: 'Studio MDHR', gr: ['platformer', 'action'],
    tg: ['coopfocused', 'difficult', 'bullethell', 'splitscreen', 'tense', 'epic', 'replayable', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 2], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 900,
    len: [12, 40], dif: 5, pace: 5, rat: 88, mood: ['adrenaline'], coopQ: 8,
    desc: { ru: 'Мультфильм 1930-х и адские боссы: вдвоём тяжелее, но смешнее и обиднее.', en: 'A 1930s cartoon with hellish bosses: harder with two players, but funnier and more painful.' },
  },
  {
    t: 'Human: Fall Flat', y: 2016, dev: 'No Brakes Games', gr: ['platformer', 'puzzle'],
    tg: ['coopfocused', 'physics', 'funny', 'wacky', 'splitscreen', 'easytolearn', 'lobbybig', 'lowsysreq', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 8], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 700,
    len: [5, 40], dif: 1, pace: 2, rat: 79, mood: ['laugh'], coopQ: 9,
    desc: { ru: 'Тряпичные человечки, неуправляемые конечности и постоянные падения в пропасть — смех гарантирован.', en: 'Ragdoll bodies, uncontrollable limbs and constant falling: guaranteed laughter.' },
  },
  {
    t: 'Gang Beasts', y: 2017, dev: 'Boneloaf', gr: ['party', 'fighting'],
    tg: ['splitscreen', 'funny', 'wacky', 'physics', 'lobbybig', 'easytolearn'],
    md: ['coopOnline', 'coopLocal', 'pvpLocal', 'pvpOnline'], pl: [2, 8], pf: ['pc', 'ps', 'xbox'], pr: 'cheap', pv: 700,
    len: [3, 50], dif: 1, pace: 3, rat: 70, mood: ['laugh'], coopQ: 9,
    desc: { ru: 'Безрукий мордобой на вечер: физика безумная, победа нелепая, крик в комнате — обязательный.', en: 'Armless brawling for an evening: insane physics, ridiculous wins and mandatory yelling.' },
  },
  {
    t: 'Pummel Party', y: 2018, dev: 'Rebuilt Games', gr: ['party'],
    tg: ['splitscreen', 'funny', 'wacky', 'lobbybig', 'pvpfocused', 'replayable'],
    md: ['coopOnline', 'coopLocal', 'pvpLocal'], pl: [2, 8], pf: ['pc'], pr: 'cheap', pv: 600,
    len: [3, 100], dif: 2, pace: 3, rat: 79, mood: ['laugh'], coopQ: 9,
    desc: { ru: 'Марио Парти для взрослых: настольная гонка, мини-игры и подставы, за которые потом извиняются.', en: 'Mario Party for adults: a board race, minigames and betrayals you apologize for later.' },
  },
  {
    t: 'Ultimate Chicken Horse', y: 2016, dev: 'Clever Endeavour', gr: ['platformer', 'party'],
    tg: ['splitscreen', 'funny', 'easytolearn', 'replayable', 'lobby4', 'cute', 'steamdeck', 'controller'],
    md: ['coopLocal', 'coopOnline', 'pvpLocal', 'pvpOnline'], pl: [2, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 500,
    len: [2, 60], dif: 2, pace: 3, rat: 87, mood: ['laugh'], coopQ: 9,
    desc: { ru: 'Сами строите уровень и сами по нему бежите: главное — сделать так, чтобы друг не добежал.', en: 'You build the level, then race it — the goal is making sure your friend cannot finish.' },
  },
  {
    t: 'Keep Talking and Nobody Explodes', y: 2015, dev: 'Steel Crate Games', gr: ['puzzle', 'party'],
    tg: ['coopfocused', 'friendlier2', 'tense', 'funny', 'easytolearn', 'voicechat', 'splitscreen'],
    md: ['coopLocal', 'coopOnline'], pl: [2, 6], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 500,
    len: [2, 30], dif: 4, pace: 5, rat: 85, mood: ['laugh', 'adrenaline'], coopQ: 10,
    desc: { ru: 'Один разминирует бомбу, остальные читают инструкцию вслух — чистая коммуникация под давлением.', en: 'One player defuses, the others read the manual out loud: pure communication under pressure.' },
  },
  {
    t: 'Valheim', y: 2021, dev: 'Iron Gate', gr: ['survival', 'sandbox', 'rpg'],
    tg: ['coopfocused', 'basebuilding', 'crafting', 'procedural', 'epic', 'exploration', 'relaxing', 'long', 'lowsysreq'],
    md: ['solo', 'coopOnline'], pl: [1, 10], pf: ['pc', 'xbox'], pr: 'mid', pv: 1200,
    len: [60, 400], dif: 3, pace: 2, rat: 90, mood: ['create', 'escape', 'progress'], coopQ: 10, gp: 1,
    desc: { ru: 'Викинги строят деревню, плывут за железом и умирают от деревьев — кооп-выживание с лучшей атмосферой.', en: 'Vikings build a village, sail for iron and die to trees: co-op survival with the best atmosphere.' },
  },
  {
    t: 'Palworld', y: 2024, dev: 'Pocketpair', gr: ['survival', 'sandbox', 'rpg'],
    tg: ['coopfocused', 'basebuilding', 'crafting', 'cute', 'funny', 'openworld', 'grind', 'exploration', 'automation'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 32], pf: ['pc', 'xbox'], pr: 'mid', pv: 1200,
    len: [40, 400], dif: 2, pace: 3, rat: 86, mood: ['create', 'progress', 'laugh'], coopQ: 9, gp: 1,
    desc: { ru: 'Покемоны с автоматами, фабрика палов и кооп-сессии на неделю — странно, но затягивает.', en: 'Pokemon with guns, a pal factory and week-long co-op sessions: bizarre but addictive.' },
  },
  {
    t: 'Minecraft', y: 2011, dev: 'Mojang', gr: ['sandbox', 'survival'],
    tg: ['coopfocused', 'basebuilding', 'crafting', 'endless', 'cozy', 'mods', 'exploration', 'easytolearn', 'lobbybig', 'lowsysreq', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal', 'pvpOnline'], pl: [1, 100], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1900,
    len: [30, 2000], dif: 1, pace: 2, rat: 90, mood: ['create', 'relax', 'escape'], coopQ: 10,
    desc: { ru: 'Универсальный конструктор миров: от уютной фермы вдвоём до огромного сервера с мини-играми.', en: 'The universal world-builder: from a cozy two-player farm to a huge minigame server.' },
  },
  {
    t: 'Terraria', y: 2011, dev: 'Re-Logic', gr: ['sandbox', 'rpg', 'platformer'],
    tg: ['coopfocused', 'basebuilding', 'crafting', 'exploration', 'loot', 'long', 'replayable', 'lowsysreq', 'mods', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 8], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 500,
    len: [60, 500], dif: 3, pace: 3, rat: 95, mood: ['create', 'progress', 'escape'], coopQ: 10,
    desc: { ru: '2D-песочница с сотнями предметов, боссами и метроидванией — на восьмерых превращается в отдельную жизнь.', en: 'A 2D sandbox with hundreds of items, bosses and metroidvania progression: with eight players it becomes a second life.' },
  },
  {
    t: "Don't Starve Together", y: 2016, dev: 'Klei', gr: ['survival', 'sandbox'],
    tg: ['coopfocused', 'crafting', 'dark', 'tense', 'difficult', 'permadeath', 'procedural', 'cute', 'mods'],
    md: ['solo', 'coopOnline'], pl: [1, 6], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 700,
    len: [20, 500], dif: 4, pace: 2, rat: 88, mood: ['progress', 'tense', 'escape'], coopQ: 9,
    desc: { ru: 'Тим Бертон в выживании: зимой все умирают от голода, летом — от пожара, и это весело.', en: 'Tim Burton does survival: everyone starves in winter, burns in summer, and it is hilarious.' },
  },
  {
    t: 'Project Zomboid', y: 2013, dev: 'The Indie Stone', gr: ['survival', 'simulator', 'rpg'],
    tg: ['zombie', 'hardcoresim', 'grind', 'permadeath', 'difficult', 'basebuilding', 'crafting', 'openworld', 'tense', 'mods', 'coopfocused'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc'], pr: 'mid', pv: 1100,
    len: [20, 1000], dif: 5, pace: 2, rat: 87, mood: ['tense', 'progress', 'escape'], coopQ: 9,
    desc: { ru: 'Симулятор зомби-апокалипсиса с безумной детализацией: смерть постоянна, а навыки — только ваши.', en: 'A zombie apocalypse sim with insane detail: death is permanent and skills only live in your head.' },
  },
  {
    t: '7 Days to Die', y: 2024, dev: 'The Fun Pimps', gr: ['survival', 'sandbox', 'horror'],
    tg: ['zombie', 'basebuilding', 'crafting', 'grind', 'coopfocused', 'procedural', 'tense', 'mods'],
    md: ['solo', 'coopOnline', 'coopLocal', 'pvpOnline'], pl: [1, 8], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1500,
    len: [40, 500], dif: 4, pace: 3, rat: 78, mood: ['create', 'tense', 'progress'], coopQ: 9,
    desc: { ru: 'Раз в семь дней — орда, значит крепость строим по-настоящему: вечный цикл «дожить до кровавой луны».', en: 'A horde every seven days means building a real fortress: survive until the blood moon, repeat.' },
  },
  {
    t: 'Grounded', y: 2022, dev: 'Obsidian', gr: ['survival', 'adventure', 'rpg'],
    tg: ['coopfocused', 'basebuilding', 'crafting', 'exploration', 'cute', 'funny', 'relaxing', 'cozy'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'xbox', 'ps', 'switch'], pr: 'mid', pv: 1990,
    len: [30, 120], dif: 3, pace: 3, rat: 82, mood: ['create', 'escape', 'laugh'], coopQ: 9, gp: 1,
    desc: { ru: 'Уменьшенные до размера муравья дети выживают в своём же саду: паук — босс, роса — источник воды.', en: 'Kids shrunk to ant size survive in their own backyard: a spider is a boss, dew is your water source.' },
  },
  {
    t: 'Raft', y: 2022, dev: 'Redbeet Interactive', gr: ['survival', 'adventure', 'sandbox'],
    tg: ['coopfocused', 'basebuilding', 'crafting', 'relaxing', 'cozy', 'exploration', 'procedural', 'underwater'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc'], pr: 'mid', pv: 1100,
    len: [25, 120], dif: 2, pace: 2, rat: 84, mood: ['relax', 'create', 'escape'], coopQ: 9,
    desc: { ru: 'Плот, океан и акула: спокойное выживание вдвоём-вчетвером, где даже рыбалка приносит прогресс.', en: 'A raft, an ocean and a shark: relaxed co-op survival where even fishing moves you forward.' },
  },
  {
    t: 'The Forest', y: 2018, dev: 'Endnight', gr: ['survival', 'horror', 'action'],
    tg: ['coopfocused', 'basebuilding', 'crafting', 'tense', 'dark', 'exploration', 'openworld'],
    md: ['solo', 'coopOnline'], pl: [1, 8], pf: ['pc', 'ps'], pr: 'mid', pv: 1200,
    len: [20, 100], dif: 3, pace: 3, rat: 84, mood: ['scare', 'create', 'tense'], coopQ: 9,
    desc: { ru: 'Выживание после крушения, канибалы-мутанты и бункеры: страшно в одиночку, очень смешно вчетвером.', en: 'Survival after a plane crash, cannibal mutants and bunkers: terrifying alone, hilarious with four.' },
  },
  {
    t: 'Sea of Thieves', y: 2018, dev: 'Rare', gr: ['adventure', 'action', 'sandbox'],
    tg: ['coopfocused', 'social', 'epic', 'funny', 'voicechat', 'exploration', 'endless', 'pvpfocused', 'cozy'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [30, 1000], dif: 3, pace: 3, rat: 82, mood: ['laugh', 'escape', 'adrenaline'], coopQ: 10, gp: 1,
    desc: { ru: 'Пиратская песочница, где истории создают сами игроки: сегодня кракен, завтра обмен сундуками с врагом.', en: 'A pirate sandbox where players make their own stories: a kraken today, a chest trade with an enemy tomorrow.' },
  },
  {
    t: 'Phasmophobia', y: 2020, dev: 'Kinetic Games', gr: ['horror', 'mystery'],
    tg: ['coopfocused', 'tense', 'voicechat', 'procedural', 'replayable', 'lowsysreq'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1100,
    len: [10, 200], dif: 3, pace: 3, rat: 85, mood: ['scare', 'laugh'], coopQ: 10,
    desc: { ru: 'Четверо охотников за призраками, микрофон включён, и что-то отвечает — самый страшный кооп на рынке.', en: 'Four ghost hunters with mics on, and something answers back: the scariest co-op out there.' },
  },
  {
    t: 'Lethal Company', y: 2023, dev: 'Zeekerss', gr: ['horror', 'survival'],
    tg: ['coopfocused', 'funny', 'tense', 'procedural', 'voicechat', 'replayable', 'lowsysreq', 'wacky'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc'], pr: 'cheap', pv: 400,
    len: [5, 200], dif: 4, pace: 3, rat: 88, mood: ['laugh', 'scare'], coopQ: 10,
    desc: { ru: 'Сбор металлолома на проклятых планетах: крик в микрофон — это 50% геймплея.', en: 'Scrap collecting on cursed moons where screaming into your mic is 50% of the gameplay.' },
  },
  {
    t: 'Dead by Daylight', y: 2016, dev: 'Behaviour', gr: ['horror', 'action'],
    tg: ['pvpfocused', 'tense', 'replayable', 'grind', 'social', 'dark', 'crosplay'],
    md: ['coopOnline', 'pvpOnline'], pl: [1, 5], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1200,
    len: [20, 1000], dif: 3, pace: 4, rat: 72, mood: ['tense', 'adrenaline', 'scare'], coopQ: 7,
    desc: { ru: 'Асимметричный хоррор: один маньяк против четырёх выживших, и выжить можно только вместе.', en: 'Asymmetric horror: one killer versus four survivors, and you only survive together.' },
  },
  {
    t: 'Destiny 2', y: 2017, dev: 'Bungie', gr: ['shooter', 'rpg', 'mmo'],
    tg: ['coopfocused', 'loot', 'grind', 'scifi', 'squad', 'epic', 'mmosocial', 'replayable', 'voicechat'],
    md: ['solo', 'coopOnline', 'pvpOnline', 'mmo'], pl: [1, 6], pf: ['pc', 'ps', 'xbox'], pr: 'free', pv: 0,
    len: [50, 1000], dif: 4, pace: 4, rat: 78, mood: ['progress', 'adrenaline', 'escape'], coopQ: 9,
    desc: { ru: 'Рейды на шесть человек и лут-спираль на сотни часов: лучший gunplay в жанре, но нужен отряд.', en: 'Six-player raids and a hundred-hour loot loop: the best gunplay in the genre, but you need a fireteam.' },
  },
  {
    t: 'Warframe', y: 2013, dev: 'Digital Extremes', gr: ['shooter', 'action', 'mmo'],
    tg: ['coopfocused', 'loot', 'grind', 'scifi', 'endless', 'mmosocial', 'epic', 'replayable', 'social'],
    md: ['solo', 'coopOnline', 'mmo', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'free', pv: 0,
    len: [50, 3000], dif: 3, pace: 5, rat: 86, mood: ['progress', 'adrenaline', 'escape'], coopQ: 8,
    desc: { ru: 'Космические ниндзя с бесплатной прокачкой на тысячи часов — глубина билдов и лучший паркур-шутинг.', en: 'Space ninjas with thousands of hours of free progression: deep builds and the best parkour shooting.' },
  },
  {
    t: 'Final Fantasy XIV', y: 2013, dev: 'Square Enix', gr: ['mmo', 'rpg'],
    tg: ['storyrich', 'mmosocial', 'coopfocused', 'fantasy', 'epic', 'long', 'social', 'exploration'],
    md: ['solo', 'coopOnline', 'mmo', 'pvpOnline'], pl: [1, 24], pf: ['pc', 'ps', 'xbox'], pr: 'subscription', pv: 1500,
    len: [100, 3000], dif: 3, pace: 3, rat: 91, mood: ['story', 'escape', 'progress'], coopQ: 9,
    desc: { ru: 'MMO с лучшим сюжетом в жанре: сотни часов истории, рейды на восемь и самая дружелюбная комьюнити.', en: 'The best story in MMOs: hundreds of hours of plot, eight-player raids and the friendliest community.' },
  },
  {
    t: 'World of Warcraft', y: 2004, dev: 'Blizzard', gr: ['mmo', 'rpg'],
    tg: ['mmosocial', 'coopfocused', 'fantasy', 'grind', 'long', 'social', 'loot', 'epic'],
    md: ['solo', 'coopOnline', 'mmo', 'pvpOnline'], pl: [1, 40], pf: ['pc'], pr: 'subscription', pv: 1000,
    len: [100, 5000], dif: 3, pace: 3, rat: 83, mood: ['progress', 'escape', 'story'], coopQ: 8,
    desc: { ru: 'Классика MMO: гильдии, рейды и чувство дома, которое возвращается каждые несколько лет.', en: 'The MMO classic: guilds, raids and a sense of home that keeps pulling you back.' },
  },
  {
    t: 'Guild Wars 2', y: 2012, dev: 'ArenaNet', gr: ['mmo', 'rpg'],
    tg: ['mmosocial', 'coopfocused', 'exploration', 'relaxing', 'fantasy', 'endless', 'social', 'cozy'],
    md: ['solo', 'coopOnline', 'mmo', 'pvpOnline'], pl: [1, 50], pf: ['pc'], pr: 'free', pv: 0,
    len: [60, 2000], dif: 3, pace: 3, rat: 85, mood: ['escape', 'relax', 'progress'], coopQ: 9,
    desc: { ru: 'Самая дружелюбная MMO: патрульные события собирают случайных игроков вместе без обязательств.', en: 'The friendliest MMO: world events pull strangers together without any commitment.' },
  },
  {
    t: 'Path of Exile 2', y: 2024, dev: 'Grinding Gear Games', gr: ['rpg', 'action'],
    tg: ['loot', 'grind', 'dark', 'difficult', 'long', 'coopfocused', 'replayable', 'fantasy'],
    md: ['solo', 'coopOnline'], pl: [1, 6], pf: ['pc', 'ps', 'xbox'], pr: 'free', pv: 0,
    len: [60, 1000], dif: 5, pace: 4, rat: 84, mood: ['progress', 'adrenaline', 'escape'], coopQ: 8,
    desc: { ru: 'Тёмное фэнтези и глубочайшая система билдов: по-настоящему хардкорный рогалик-APRG на годы.', en: 'Dark fantasy and the deepest build system around: a truly hardcore action RPG for years.' },
  },
  {
    t: 'Diablo IV', y: 2023, dev: 'Blizzard', gr: ['rpg', 'action'],
    tg: ['loot', 'dark', 'grind', 'coopfocused', 'epic', 'replayable', 'cutscenes'],
    md: ['solo', 'coopOnline', 'coopLocal', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [40, 500], dif: 3, pace: 4, rat: 81, mood: ['progress', 'adrenaline', 'escape'], coopQ: 8, gp: 1,
    desc: { ru: 'Мрачный Санктуарий, сезонные персонажи и кооп на четверых с общего экрана и по сети.', en: 'Grim Sanctuary, seasonal characters and four-player co-op online or on a shared screen.' },
  },
  {
    t: 'Counter-Strike 2', y: 2023, dev: 'Valve', gr: ['shooter'],
    tg: ['pvpfocused', 'tense', 'voicechat', 'squad', 'easytolearn', 'lowsysreq', 'endlessloop'],
    md: ['pvpOnline'], pl: [2, 10], pf: ['pc'], pr: 'free', pv: 0,
    len: [20, 5000], dif: 4, pace: 5, rat: 83, mood: ['compete', 'adrenaline', 'progress'],
    desc: { ru: 'Эталон тактического шутера 5×5: один раунд — минута, одна ошибка — весь матч.', en: 'The benchmark 5v5 tactical shooter: one round is a minute, one mistake is the match.' },
  },
  {
    t: 'Valorant', y: 2020, dev: 'Riot Games', gr: ['shooter', 'tactics'],
    tg: ['pvpfocused', 'squad', 'voicechat', 'easytolearn', 'crosplay', 'lowsysreq', 'modern'],
    md: ['pvpOnline'], pl: [2, 10], pf: ['pc', 'ps', 'xbox'], pr: 'free', pv: 0,
    len: [20, 3000], dif: 4, pace: 5, rat: 80, mood: ['compete', 'adrenaline'],
    desc: { ru: 'Тактический шутер с агентами и способностями: продуманный, но прощающий новичкам.', en: 'A tactical shooter with agents and abilities: thoughtful, yet forgiving to newcomers.' },
  },
  {
    t: 'Dota 2', y: 2013, dev: 'Valve', gr: ['strategy'],
    tg: ['pvpfocused', 'squad', 'hardcoresim', 'difficult', 'long', 'voicechat', 'social'],
    md: ['pvpOnline'], pl: [2, 10], pf: ['pc'], pr: 'free', pv: 0,
    len: [50, 5000], dif: 5, pace: 4, rat: 84, mood: ['compete', 'progress'],
    desc: { ru: 'Самая глубокая MOBA: порог входа огромен, зато потолок мастерства почти бесконечен.', en: 'The deepest MOBA: a huge learning curve and an almost endless skill ceiling.' },
  },
  {
    t: 'League of Legends', y: 2009, dev: 'Riot Games', gr: ['strategy'],
    tg: ['pvpfocused', 'squad', 'grind', 'social', 'endless', 'easytolearn', 'lowsysreq'],
    md: ['pvpOnline'], pl: [2, 10], pf: ['pc', 'mobile'], pr: 'free', pv: 0,
    len: [50, 5000], dif: 4, pace: 4, rat: 76, mood: ['compete', 'progress'],
    desc: { ru: 'Главная MOBA мира: легко начать, сложно остановиться, и всегда найдётся друг для пары.', en: 'The world\u2019s biggest MOBA: easy to start, hard to stop, and there is always a friend for a duo queue.' },
  },
  {
    t: 'Apex Legends', y: 2019, dev: 'Respawn', gr: ['shooter', 'action'],
    tg: ['pvpfocused', 'squad', 'voicechat', 'scifi', 'easytolearn', 'crosplay', 'endlessloop'],
    md: ['pvpOnline'], pl: [1, 3], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'free', pv: 0,
    len: [20, 3000], dif: 4, pace: 5, rat: 80, mood: ['adrenaline', 'compete'], coopQ: 7,
    desc: { ru: 'Лучшая стрельба в королевской битве: трио, скольжение и ощущение, что каждый бой честный.', en: 'The best gunplay in battle royale: trios, sliding and fights that feel fair.' },
  },
  {
    t: 'Overwatch 2', y: 2022, dev: 'Blizzard', gr: ['shooter', 'action'],
    tg: ['pvpfocused', 'squad', 'epic', 'easytolearn', 'crosplay', 'coopfocused', 'modern'],
    md: ['pvpOnline'], pl: [1, 10], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'free', pv: 0,
    len: [20, 2000], dif: 3, pace: 5, rat: 72, mood: ['adrenaline', 'compete', 'laugh'], coopQ: 7,
    desc: { ru: 'Героический шутер 5×5: быстрые раунды, яркие герои и ультимейты, меняющие ход боя.', en: 'A 5v5 hero shooter: quick rounds, colorful heroes and ultimates that flip a fight.' },
  },
  {
    t: 'Rocket League', y: 2015, dev: 'Psyonix', gr: ['sports', 'racing'],
    tg: ['pvpfocused', 'easytolearn', 'difficult', 'crosplay', 'squad', 'endlessloop', 'coopfocused', 'lowsysreq', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal', 'pvpOnline', 'pvpLocal'], pl: [1, 8], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'free', pv: 0,
    len: [10, 3000], dif: 4, pace: 5, rat: 86, mood: ['compete', 'adrenaline', 'laugh'], coopQ: 9,
    desc: { ru: 'Футбол машинами: правила понятны за минуту, а мастерство растёт годами — идеальный кооп на двоих.', en: 'Car soccer: the rules take a minute to learn and years to master: perfect two-player co-op.' },
  },
  {
    t: 'Fall Guys', y: 2020, dev: 'Mediatonic', gr: ['party'],
    tg: ['funny', 'cute', 'easytolearn', 'crosplay', 'lobbybig', 'pvpfocused', 'wacky'],
    md: ['pvpOnline', 'coopOnline'], pl: [1, 60], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'free', pv: 0,
    len: [5, 300], dif: 1, pace: 3, rat: 77, mood: ['laugh', 'relax'], coopQ: 8,
    desc: { ru: 'Полоса препятствий на 60 человек: нелепо, ярко и отлично подходит для вечера с друзьями.', en: 'A 60-player obstacle course: silly, colorful and perfect for an evening with friends.' },
  },
  {
    t: 'PUBG: Battlegrounds', y: 2017, dev: 'Krafton', gr: ['shooter', 'survival'],
    tg: ['pvpfocused', 'tense', 'squad', 'voicechat', 'modern', 'loot'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'mobile'], pr: 'free', pv: 0,
    len: [20, 2000], dif: 4, pace: 4, rat: 70, mood: ['adrenaline', 'tense', 'compete'], coopQ: 8,
    desc: { ru: 'Королевская битва с самой нервной посадкой: один выстрел решает всё, а друзья прикрывают.', en: 'The most nerve-wracking battle royale drop: one bullet decides everything while friends cover you.' },
  },
];
