/** Каталог, часть B — одиночные игры: сюжет, атмосфера, хардкор, хоррор. */
export const PART_B = [
  {
    t: 'Baldur\u2019s Gate 3', y: 2023, dev: 'Larian Studios', gr: ['rpg', 'tactics', 'adventure'],
    tg: ['storyrich', 'choices', 'tbs', 'fantasy', 'dialogheavy', 'squad', 'long', 'replayable', 'coopfocused', 'cinematic', 'cutscenes', 'social'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [80, 400], dif: 3, pace: 2, rat: 96, mood: ['story', 'think', 'escape'], coopQ: 9,
    desc: { ru: 'Эталонная RPG с выборами, которые реально меняют мир, и коопом на четверых с той же свободой.', en: 'The benchmark RPG where choices really change the world, with four-player co-op that keeps all the freedom.' },
    about: {"ru":"Эталонная RPG по правилам Dungeons & Dragons: каждое решение меняет сюжет, а свободу действий ограничивает только фантазия. Бои пошаговые, диалоги — с сотнями развилок, а пройти кампанию можно и в кооперативе на четверых.","en":"The benchmark RPG built on Dungeons & Dragons rules: every decision reshapes the story, and only imagination limits your options. Combat is turn-based, dialogues branch by the hundreds, and the whole campaign runs in four-player co-op."},
    feats: {"ru":["Игра года 2023 — редкое единодушие прессы и игроков","Выборы действительно меняют мир и финал","Полноценный кооператив с той же свободой, что и соло"],"en":["2023 Game of the Year — rare press-and-player unanimity","Choices genuinely reshape the world and the ending","Full co-op with the same freedom as solo play"]},
  },
  {
    t: 'The Witcher 3: Wild Hunt', y: 2015, dev: 'CD Projekt Red', gr: ['rpg', 'action', 'adventure'],
    tg: ['storyrich', 'openworld', 'fantasy', 'dark', 'exploration', 'long', 'cinematic', 'cutscenes', 'dialogheavy', 'choices', 'epic', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [60, 200], dif: 3, pace: 3, rat: 93, mood: ['story', 'explore', 'escape'],
    desc: { ru: 'Охота на ведьмака по огромному континенту: лучшие побочные квесты в жанре и морально серые решения.', en: 'Witcher work across a vast continent: the best side quests in the genre and morally grey decisions.' },
    about: {"ru":"Охотник на чудовищ Геральт ищет приёмную дочь Цири по огромному миру, раздираемому войной. Побочные задания здесь написаны лучше, чем основные сюжеты многих игр, а каждое решение имеет последствия.","en":"Monster hunter Geralt searches for his adopted daughter Ciri across a vast war-torn world. Side quests here are written better than most games’ main plots, and every decision has consequences."},
    feats: {"ru":["Один из самых награждаемых сюжетов в истории игр","Живой мир, где даже маленький контракт рассказывает историю","Два дополнения уровня отдельной большой игры"],"en":["One of the most awarded narratives in gaming history","A living world where even a small contract tells a story","Two expansions the size of full games"]},
  },
  {
    t: 'Cyberpunk 2077', y: 2020, dev: 'CD Projekt Red', gr: ['rpg', 'action', 'shooter'],
    tg: ['cyberpunk', 'openworld', 'storyrich', 'epic', 'photomode', 'cutscenes', 'choices', 'modern', 'gpuheavy', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [50, 150], dif: 3, pace: 4, rat: 88, mood: ['story', 'adrenaline', 'escape'],
    desc: { ru: 'Найт-Сити, имплантаты и долг перед Киану Ривзом — самая стильная RPG про будущее.', en: 'Night City, implants and a debt to Keanu Reeves: the most stylish RPG of the future.' },
    about: {"ru":"Ролевой экшен в мегаполисе будущего: наёмник Ви борется за жизнь, в голове у которой живёт цифровая копия рок-звезды. После масштабных обновлений Найт-Сити стал эталоном атмосферного открытого города, а полиция и ИИ получили полную переработку.","en":"An action RPG in the megacity of the future: mercenary V fights for survival with a digital copy of a rock star living in their head. After sweeping updates, Night City became a benchmark atmospheric open city, with police and AI fully reworked."},
    feats: {"ru":["Найт-Сити — один из самых детальных городов в играх","Стиль сборки решает: хакер, стрелок или мастер клинков","Дополнение Phantom Liberty — шпионский триллер с Голливудом в кадре"],"en":["Night City is one of the most detailed cities in games","Builds define playstyle: hacker, gunslinger or blade master","Phantom Liberty expansion is a Hollywood-grade spy thriller"]},
  },
  {
    t: 'Elden Ring', y: 2022, dev: 'FromSoftware', gr: ['rpg', 'action'],
    tg: ['soulslike', 'difficult', 'openworld', 'dark', 'fantasy', 'exploration', 'epic', 'long', 'coopfocused', 'photomode', 'philosophical'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [60, 200], dif: 5, pace: 3, rat: 94, mood: ['adrenaline', 'explore', 'progress'], coopQ: 7,
    desc: { ru: 'Открытый фэнтези-мир, который не ведёт за руку: награда за любопытство и за терпение к смерти.', en: 'An open fantasy world that never holds your hand: rewards curiosity and patience with death.' },
    about: {"ru":"Соулслайк в открытом мире от FromSoftware и Джорджа Мартина: Междуземье полно боссов, тайн и подземелий, которые находятся сами собой, стоит лишь свернуть с дороги. Свобода маршрута сочетается с фирменной боевой системой на таймингах.","en":"An open-world soulslike from FromSoftware and George Martin: the Lands Between are packed with bosses, secrets and dungeons that find themselves once you stray off the path. Route freedom meets the studio’s signature timing-based combat."},
    feats: {"ru":["Игра года 2022 по версии The Game Awards","Мир, который не ведёт за руку, а вознаграждает любопытство","Пеплы войны и призывы делают боги доступнее без потери глубины"],"en":["The Game Awards 2022 Game of the Year","A world that rewards curiosity instead of hand-holding","Ashes of War and summons make it approachable without losing depth"]},
  },
  {
    t: 'Dark Souls III', y: 2016, dev: 'FromSoftware', gr: ['rpg', 'action'],
    tg: ['soulslike', 'difficult', 'dark', 'fantasy', 'linear', 'epic', 'coopfocused', 'tense'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 6], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [30, 120], dif: 5, pace: 4, rat: 91, mood: ['adrenaline', 'escape'], coopQ: 7,
    desc: { ru: 'Пепел угасает, а вы снова умираете: классический соулслайк с плотнейшей боевой системой.', en: 'The fire fades and you die again: the classic soulslike with the tightest combat system.' },
    about: {"ru":"Третья часть легендарной серии: Пепельный странник возвращает на троны повелителей пепла, пока мир сходит в воронку угасания. Самый быстрый и отточенный бой классической трилогии плюс боссы, ставшие иконами.","en":"The third entry in the legendary series: the Ashen One returns the Lords of Cinder to their thrones as the world collapses into entropy. The fastest, most polished combat of the classic trilogy, plus iconic bosses."},
    feats: {"ru":["Боссы уровня именитого танца и близнецов принцев","Самая динамичная боевая система трилогии","Множество сборок: магия, чудеса, чистый меч"],"en":["Boss fights of Dance of the Firelancers calibre","The most dynamic combat in the trilogy","Build variety: sorcery, miracles or pure steel"]},
  },
  {
    t: 'Sekiro: Shadows Die Twice', y: 2019, dev: 'FromSoftware', gr: ['action', 'adventure'],
    tg: ['soulslike', 'difficult', 'historical', 'linear', 'cinematic', 'epic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [30, 60], dif: 5, pace: 5, rat: 91, mood: ['adrenaline', 'story'],
    desc: { ru: 'Фехтование по ритму, шиноби в Сэнгоку и никакой прокачки уровня — чистая честная сложность.', en: 'Rhythm-based swordplay, a Sengoku shinobi and no level grinding: pure, honest difficulty.' },
    about: {"ru":"Экшен про однорукого синоби в фэнтезийной Японии эпохи Сэнгоку. Вместо уклонений — парирования: бой построен на столкновении клинков и сломе стойки противника. Игра года 2019 и, пожалуй, самый требовательный тайтл FromSoftware.","en":"An action game about a one-armed shinobi in a fantastical Sengoku-era Japan. Dodging gives way to parries: combat is built on clashing blades and breaking the enemy’s posture. 2019 Game of the Year and arguably FromSoftware’s most demanding title."},
    feats: {"ru":["Система парирований, изменившая жанр","Сюжет о верности и бессмертии без многопользовательских костылей","Победа над финальным боссом — медаль на всю жизнь"],"en":["A parry system that changed the genre","A tale of loyalty and immortality, no multiplayer crutches","Beating the final boss is a badge for life"]},
  },
  {
    t: 'Bloodborne', y: 2015, dev: 'FromSoftware', gr: ['action', 'rpg', 'horror'],
    tg: ['soulslike', 'difficult', 'dark', 'tense', 'epic', 'mythology'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 3], pf: ['ps'], pr: 'mid', pv: 2490,
    len: [35, 90], dif: 5, pace: 5, rat: 92, mood: ['adrenaline', 'scare'], coopQ: 6,
    desc: { ru: 'Викторианский кошмар Лавкрафта: страх как механика и агрессивный бой без щитов.', en: 'A Victorian Lovecraftian nightmare: fear as a mechanic and aggressive combat without shields.' },
    about: {"ru":"Готический экшен про Охотника в городе Ярнам, который поражён чумой зверя и тайной древних богов. Бой поощряет агрессию: здоровье возвращает атака сразу после удара врага. Эксклюзив PlayStation с культовым статусом.","en":"A gothic action game about the Hunter in Yharnam, a city stricken by a beast plague and the secrets of ancient gods. Combat rewards aggression: attacking right after being hit regains health. A PlayStation exclusive with cult status."},
    feats: {"ru":["Атмосфера викторианского кошмара без единой фальшивой ноты","Агрессивный темп боя вместо щитов и блоков","Лавкрафтовский второй акт, переворачивающий всё"],"en":["A Victorian nightmare atmosphere without a false note","Aggressive combat tempo instead of shields and blocks","A Lovecraftian second act that flips everything"]},
  },
  {
    t: 'Lies of P', y: 2023, dev: 'Round8', gr: ['action', 'rpg'],
    tg: ['soulslike', 'difficult', 'dark', 'linear', 'cinematic', 'soundtrack', 'epic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [30, 60], dif: 5, pace: 4, rat: 82, mood: ['adrenaline', 'story'], gp: 1,
    desc: { ru: 'Пиноккио-соулслайк в стиле Belle Époque: красиво, жёстко и с отличными боссами.', en: 'A Pinocchio soulslike in Belle Époque style: gorgeous, brutal and full of great bosses.' },
    about: {"ru":"Соулслайк по мотивам Пиноккио: механический мальчик идёт через Белль-эток, поражённый безумием марионеток, и учится лгать — каждая ложь меняет его человечность. Бой собран из парирований, идеальных уклонений и сменного оружия.","en":"A Pinocchio-inspired soulslike: a mechanical boy crosses the plague-mad city of Krat, where puppets have gone feral, and learns to lie — each lie shaping his humanity. Combat mixes parries, perfect dodges and swappable weapons."},
    feats: {"ru":["Одна из самых красивых соулслайк-игр","Система лжи влияет на финал","Сборка оружия из клинка и рукояти"],"en":["One of the most beautiful soulslikes","A lie system that shapes the ending","Weapon assembly from blade and handle parts"]},
  },
  {
    t: 'Black Myth: Wukong', y: 2024, dev: 'Game Science', gr: ['action', 'rpg'],
    tg: ['mythology', 'difficult', 'epic', 'photomode', 'cinematic', 'fantasy', 'epic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [30, 60], dif: 4, pace: 5, rat: 82, mood: ['adrenaline', 'story'],
    desc: { ru: 'Китайская мифология и бои на посохах против 70+ боссов — зрелищный экшен про Царя обезьян.', en: 'Chinese mythology and staff combat against 70+ bosses: a spectacular Monkey King action game.' },
    about: {"ru":"Экшен по мотивам классического романа «Путешествие на Запад»: Обезьяний царь противостоит богам и демонам в фотореалистичном Китае. Быстрые комбо, превращения и заклинания складываются в зрелищные бои с боссами.","en":"An action game inspired by the classic novel Journey to the West: the Destined One faces gods and demons across a photorealistic China. Fast combos, transformations and spells combine into spectacular boss fights."},
    feats: {"ru":["Один из самых громких релизов 2024 года","Боссы один впечатляющее другого","Мифология Китая без западных фильтров"],"en":["One of the biggest releases of 2024","Boss encounters that keep outdoing each other","Chinese mythology told without a Western filter"]},
  },
  {
    t: 'God of War (2018)', y: 2018, dev: 'Santa Monica Studio', gr: ['action', 'adventure'],
    tg: ['storyrich', 'mythology', 'epic', 'cinematic', 'cutscenes', 'photomode', 'dark', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 2490,
    len: [25, 60], dif: 4, pace: 4, rat: 94, mood: ['story', 'adrenaline'],
    desc: { ru: 'Кратос взрослеет вместе с сыном: один непрерывный кадр, топор, что возвращается, и скандинавские мифы.', en: 'Kratos grows up alongside his son: one continuous shot, a returning axe and Norse myth.' },
    about: {"ru":"Кратос, бывший бог войны, растит сына Атрея в мире скандинавских богов и учится быть отцом. Камера переехала за плечо, топор возвращается в руку как молот Тора, а история держится на диалогах по пути к вершине горы.","en":"Kratos, the former god of war, raises his son Atreus in the realm of Norse gods and learns to be a father. The camera moved over the shoulder, the axe returns to hand like Thor’s hammer, and the story lives in the conversations on the way to the peak."},
    feats: {"ru":["Игра года 2018","Один непрерывный кадр без монтажных склеек","Одна из лучших историй об отцовстве в играх"],"en":["2018 Game of the Year","A single continuous shot with no cuts","One of gaming’s best stories about fatherhood"]},
  },
  {
    t: 'God of War Ragnar\u00f6k', y: 2022, dev: 'Santa Monica Studio', gr: ['action', 'adventure'],
    tg: ['storyrich', 'mythology', 'epic', 'cinematic', 'cutscenes', 'photomode', 'long'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [35, 80], dif: 4, pace: 4, rat: 92, mood: ['story', 'adrenaline'],
    desc: { ru: 'Все девять миров на грани Рагнарёка, а Кратос пытается не повторить свою судьбу.', en: 'All nine realms on the brink of Ragnarok while Kratos tries not to repeat his own fate.' },
    about: {"ru":"Продолжение истории Кратоса и Атрея: приближается Рагнарёк, и отец с сыном идут по девяти мирам, пытаясь его пережить. Боёв, миров и масштаба стало больше, а ядро — всё то же путешествие двух персонажей.","en":"The continuation of Kratos and Atreus’ story: Ragnarök is coming, and father and son journey through all nine realms trying to survive it. More combat, more worlds, more scale — with the same two-character journey at the core."},
    feats: {"ru":["Девять миров против нескольких в прошлой части","Больше оружия и стилей боя у обоих героев","Финал арки Кратоса, который ждали годами"],"en":["Nine realms versus a handful in the previous game","More weapons and fighting styles for both heroes","The long-awaited finale of Kratos’ arc"]},
  },
  {
    t: 'The Last of Us Part I', y: 2022, dev: 'Naughty Dog', gr: ['action', 'adventure', 'horror'],
    tg: ['storyrich', 'sad', 'zombie', 'tense', 'linear', 'cinematic', 'cutscenes', 'epic', 'photomode'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [15, 25], dif: 3, pace: 4, rat: 89, mood: ['story', 'feel', 'tense'],
    desc: { ru: 'Джоэл и Элли идут через погибший мир: лучший пример, как игра может рассказать историю.', en: 'Joel and Ellie cross a dead world: the best example of games telling a story.' },
    about: {"ru":"Полный ремейк истории Джоэла и Элли — контрабандиста и девочки-подростка, идущих через Америку после пандемии кордицепса. Классический сюжет от студии Naughty Dog с современной графикой и переработанным геймплеем.","en":"A full remake of Joel and Ellie’s story — a smuggler and a teenage girl crossing post-cordyceps America. Naughty Dog’s classic tale rebuilt with modern visuals and reworked gameplay."},
    feats: {"ru":["Один из самых признанных сюжетов в истории игр","Ремейк с нуля, а не ремастер","Режим пермасмерти для смелых"],"en":["One of the most acclaimed stories in gaming","A ground-up remake, not a remaster","A permadeath mode for the brave"]},
  },
  {
    t: 'The Last of Us Part II Remastered', y: 2024, dev: 'Naughty Dog', gr: ['action', 'adventure', 'horror'],
    tg: ['storyrich', 'sad', 'zombie', 'tense', 'cinematic', 'cutscenes', 'epic', 'difficult', 'photomode'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [25, 40], dif: 4, pace: 4, rat: 89, mood: ['story', 'feel', 'tense'],
    desc: { ru: 'Месть, которая никого не делает счастливым: технически безупречный и эмоционально тяжёлый опыт.', en: 'Revenge that makes nobody happy: technically flawless and emotionally brutal.' },
    about: {"ru":"Продолжение истории Элли: месть ведёт её из Джексона в Сиэтл, а вторая половина кампании показывает события глазами другой стороны. Издание для современных платформ добавляет режим «Без возврата» — рогалик со случайными забегами.","en":"Ellie’s story continues: revenge carries her from Jackson to Seattle, and the second half retells events from the other side. The current-gen edition adds “No Return”, a roguelike mode with randomised runs."},
    feats: {"ru":["Самая обсуждаемая история поколения","Две переплетённые кампании в одной игре","Рогалик «Без возврата» в комплекте"],"en":["The most discussed story of its generation","Two interwoven campaigns in one game","The “No Return” roguelike included"]},
  },
  {
    t: 'Red Dead Redemption 2', y: 2018, dev: 'Rockstar Games', gr: ['action', 'adventure'],
    tg: ['openworld', 'storyrich', 'historical', 'slow', 'epic', 'long', 'cinematic', 'photomode', 'realistic', 'soundtrack'],
    md: ['solo', 'pvpOnline'], pl: [1, 32], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [60, 250], dif: 3, pace: 2, rat: 94, mood: ['story', 'explore', 'escape'],
    desc: { ru: 'Закат эпохи бандитов на Диком Западе: медленно, красиво и очень больно к финалу.', en: 'The sunset of the outlaw era in the Wild West: slow, beautiful and deeply painful by the end.' },
    about: {"ru":"Эпос об угасании бандитского Запада: Артур Морган и банда Ван дер Линде уходят от погони через всю Америку конца XIX века. Невероятно детальный мир, где охота, покер и случайные встречи складываются в жизнь, а не в список заданий.","en":"An epic about the dying Wild West: Arthur Morgan and the Van der Linde gang outrun pursuit across late-19th-century America. An astonishingly detailed world where hunting, poker and chance encounters add up to a life, not a quest list."},
    feats: {"ru":["Мир, живущий по собственному расписанию","Один из сильнейших финалов в играх","Онлайн-режим с отдельной жизнью"],"en":["A world running on its own schedule","One of the strongest endings in games","An online mode with a life of its own"]},
  },
  {
    t: 'Grand Theft Auto V', y: 2013, dev: 'Rockstar Games', gr: ['action', 'adventure'],
    tg: ['openworld', 'modern', 'funny', 'epic', 'grind', 'long', 'mmosocial', 'replayable', 'coopfocused'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 30], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [30, 300], dif: 2, pace: 4, rat: 92, mood: ['laugh', 'adrenaline', 'escape'], coopQ: 8,
    desc: { ru: 'Три бандита, один город и Online, где каждый вечер находится новая авантюра с друзьями.', en: 'Three criminals, one city, and an Online mode with a fresh scheme every evening with friends.' },
    about: {"ru":"Три переплетающихся истории преступников Лос-Сантоса, между которыми можно переключаться прямо посреди дела. Сатира на американскую мечту, ограбления с подготовкой и огромный открытый мир — рекордсмен индустрии по продажам.","en":"Three intertwining criminal stories in Los Santos, switchable mid-heist. A satire of the American dream with planned heists and a huge open world — an industry sales record-holder."},
    feats: {"ru":["Три играбельных героя с разными характерами","Ограбления с выбором подхода и команды","GTA Online — отдельная вселенная на годы"],"en":["Three playable protagonists with distinct personalities","Heists with approach and crew choices","GTA Online — a universe of its own for years"]},
  },
  {
    t: 'Uncharted 4: A Thief\u2019s End', y: 2016, dev: 'Naughty Dog', gr: ['action', 'adventure'],
    tg: ['storyrich', 'epic', 'cinematic', 'linear', 'exploration', 'cutscenes', 'funny', 'photomode'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 1990,
    len: [15, 35], dif: 3, pace: 4, rat: 90, mood: ['story', 'adrenaline', 'explore'],
    desc: { ru: 'Приключение в духе Индианы Джонса: обвалы, джунгли и братья, которым есть что делить.', en: 'Indiana Jones in game form: collapses, jungles and brothers with history between them.' },
    about: {"ru":"Финальная глава приключений Нейтана Дрейка: поиски пиратских сокровищ брата Генри Эвери бросают его из Италии на Мадагаскар. Постановка уровня летнего блокбастера, акробатика, перестрелки и семейная драма в основе.","en":"Nathan Drake’s final chapter: the hunt for pirate Henry Avery’s treasure throws him from Italy to Madagascar. Blockbuster-movie direction, acrobatics, gunfights and a family drama at the core."},
    feats: {"ru":["Эталон кинематографичного экшена","Лучшая графика своего поколения и на ПК сегодня","Финал, достойный десяти лет серии"],"en":["The benchmark of cinematic action","Generation-defining visuals, still great on PC","A finale worthy of a decade-long series"]},
  },
  {
    t: 'Marvel\u2019s Spider-Man 2', y: 2023, dev: 'Insomniac Games', gr: ['action', 'adventure'],
    tg: ['openworld', 'epic', 'cinematic', 'easytolearn', 'modern', 'photomode', 'storyrich', 'colorful'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [20, 45], dif: 2, pace: 5, rat: 88, mood: ['adrenaline', 'story', 'laugh'],
    desc: { ru: 'Полёты между небоскрёбами как лучшая механика в супергероике, плюс двое пауков сразу.', en: 'Web-swinging between skyscrapers is the best superhero mechanic, now with two Spider-Men.' },
    about: {"ru":"Два Паука — Питер Паркер и Майлз Моралес — против Венома и Крейвена-охотника в Нью-Йорке, который стал вдвое больше. Полёты на паутине стали быстрее, крылья-мантии добавляют планирование, а переключение героев происходит мгновенно.","en":"Two Spider-Men — Peter Parker and Miles Morales — face Venom and Kraven the Hunter in a New York twice as big. Web-swinging is faster, wing-suits add gliding, and switching heroes is instant."},
    feats: {"ru":["Нью-Йорк, по которому хочется просто летать","Два героя с разными способностями в одной истории","Веном в лучшей игровой форме"],"en":["A New York you want to swing through for hours","Two heroes with different powers in one story","Venom at his video-game best"]},
  },
  {
    t: 'Batman: Arkham Knight', y: 2015, dev: 'Rocksteady', gr: ['action', 'adventure'],
    tg: ['openworld', 'dark', 'cinematic', 'epic', 'photomode', 'modern'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1500,
    len: [20, 50], dif: 3, pace: 4, rat: 87, mood: ['adrenaline', 'story'],
    desc: { ru: 'Бэтмобиль, масса свободной боевой системы и лучший силуэт Готэма ночью.', en: 'The Batmobile, a massively free-flow combat system and Gotham\u2019s best night silhouette.' },
    about: {"ru":"Финал серии Arkham: Пугало объединяет всех злодеев Готэма, а против Бэтмена выставляют рыцаря Аркхема. Впервые в серии — Бэтмобиль, который участвует и в погонях, и в боях, и в головоломках.","en":"The Arkham series finale: Scarecrow unites all of Gotham’s villains, and the Arkham Knight is unleashed against Batman. For the first time — the Batmobile, used in chases, battles and puzzles alike."},
    feats: {"ru":["Бэтмобиль как полноценная механика","Вся галерея злодеев Готэма в одной игре","Лучшая система контрударов в жанре"],"en":["The Batmobile as a full mechanic","Gotham’s entire rogues gallery in one game","The best free-flow counter system in the genre"]},
  },
  {
    t: 'Ghost of Tsushima', y: 2020, dev: 'Sucker Punch', gr: ['action', 'adventure'],
    tg: ['openworld', 'historical', 'epic', 'photomode', 'exploration', 'cinematic', 'soundtrack'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 4], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [30, 70], dif: 3, pace: 4, rat: 89, mood: ['explore', 'story', 'adrenaline'], coopQ: 7,
    desc: { ru: 'Самурай против монгольского нашествия: ветер вместо маркеров и самый красивый исследуемый остров.', en: 'A samurai against the Mongol invasion: wind instead of markers and the most beautiful island to explore.' },
    about: {"ru":"Дзин Сакай защищает остров Цусима от монгольского вторжения, постепенно превращаясь из самурая в Призрака. Бои на катанах со сменой стоек, бесшумные освобождения деревень и один из самых красивых открытых миров — с режимом без интерфейса.","en":"Jin Sakai defends Tsushima island from the Mongol invasion, slowly turning from samurai into the Ghost. Stance-switching katana combat, stealth liberations of villages and one of the most beautiful open worlds — with a no-HUD mode."},
    feats: {"ru":["Кинорежим «Куросава» — чёрно-белый с плёнкой","Мир, в котором ветер сам ведёт к цели","Кооперативный режим «Легенды» про духов Японии"],"en":["Kurosawa mode — black-and-white film look","A world where the wind itself guides you","The co-op “Legends” mode about Japanese spirits"]},
  },
  {
    t: 'Horizon Forbidden West', y: 2022, dev: 'Guerilla Games', gr: ['action', 'rpg', 'adventure'],
    tg: ['openworld', 'scifi', 'exploration', 'photomode', 'storyrich', 'epic', 'long', 'colorful'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [30, 80], dif: 3, pace: 4, rat: 89, mood: ['explore', 'story', 'adrenaline'],
    desc: { ru: 'Роботизированные динозавры и луки: исследование постапокалиптического Золотого Запада.', en: 'Robot dinosaurs and bows: exploring the post-apocalyptic frontier.' },
    about: {"ru":"Элой идёт на Запретный Запад, чтобы спасти умирающую биосферу: новые племена, подводные руины и машины-динозавры крупнее и опаснее прежних. Бой построен на отстреле деталей машин — от брони до оружейных модулей.","en":"Aloy heads to the Forbidden West to save a dying biosphere: new tribes, underwater ruins and machine-dinosaurs bigger and deadlier than before. Combat is built on shooting machine parts off — from armour plates to weapon modules."},
    feats: {"ru":["Машины, которых интересно разбирать на части","Один из самых сочных открытых миров поколения","Полёты на солнечном крыле и подводные зоны"],"en":["Machines that are fun to disassemble piece by piece","One of the lushest open worlds of its generation","Sunwing flights and underwater areas"]},
  },
  {
    t: 'Death Stranding', y: 2019, dev: 'Kojima Productions', gr: ['adventure', 'simulator'],
    tg: ['walkingsim', 'scifi', 'philosophical', 'slow', 'relaxing', 'long', 'photomode', 'social', 'epic'],
    md: ['solo', 'async'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 2490,
    len: [40, 100], dif: 3, pace: 1, rat: 84, mood: ['relax', 'explore', 'story'],
    desc: { ru: 'Курьер через опустевшую Америку: медитативная логистика, страннейший сюжет и лестницы от других игроков.', en: 'A courier across an empty America: meditative logistics, a bizarre plot and ladders from other players.' },
    about: {"ru":"Курьер Сэм Портер Бриджес заново соединяет разорванную Америку: несёт грузы через горы и реки, прокладывая маршруты и инфраструктуру для других игроков. Медитативная игра Кодзимы о связях между людьми с асинхронным мультиплеером.","en":"Courier Sam Porter Bridges reconnects a fractured America: hauling cargo across mountains and rivers, laying routes and infrastructure for other players. Kojima’s meditative game about human connection with asynchronous multiplayer."},
    feats: {"ru":["Мир, который достраивают сами игроки — мосты, дороги, укрытия","Ландшафт как главный противник и главный герой","Неспешная, но затягивающая петля доставки"],"en":["A world built up by players themselves — bridges, roads, shelters","The terrain as the main enemy and the main hero","A slow-burn delivery loop that hooks hard"]},
  },
  {
    t: 'Control', y: 2019, dev: 'Remedy', gr: ['action', 'adventure', 'shooter'],
    tg: ['scifi', 'tense', 'epic', 'photomode', 'philosophical', 'dark', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1500,
    len: [15, 30], dif: 3, pace: 4, rat: 85, mood: ['story', 'adrenaline'],
    desc: { ru: 'Брутализм, телекинез и здание, которое меняет геометрию — самый странный экшен Remedy.', en: 'Brutalism, telekinesis and a building that shifts geometry: Remedy at their strangest.' },
    about: {"ru":"Джесси Фейденс становится директором Федерального Бюро Контроля — учреждения, изучающего паранормальное, — и разгребает вторжение шипящей силы Шипения. Телекинез, служебный пистолет-трансформер и Старейший Дом, который перестраивает сам себя.","en":"Jesse Faden becomes Director of the Federal Bureau of Control — an agency studying the paranormal — and fights back an invasion called the Hiss. Telekinesis, a shapeshifting Service Weapon and the Oldest House that rearranges itself."},
    feats: {"ru":["Разрушаемость уровня топ-уровня: летит всё","Сетевой лор в духе «Секретных материалов» и Фонда SCP","Дополнения «Фундамент» и «АВА» расширяют Старейший Дом"],"en":["Top-tier destructibility: everything flies","Lore in the spirit of The X-Files and the SCP Foundation","The Foundation and AWE expansions deepen the Oldest House"]},
  },
  {
    t: 'Alan Wake 2', y: 2023, dev: 'Remedy', gr: ['horror', 'adventure', 'shooter'],
    tg: ['storyrich', 'dark', 'tense', 'cinematic', 'photomode', 'epic', 'choices', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [20, 30], dif: 3, pace: 3, rat: 88, mood: ['story', 'scare', 'think'],
    desc: { ru: 'Детектив и писатель распутывают одну историю: FMV-сцены, мюзикл и настоящий северный хоррор.', en: 'A detective and a writer untangle one story: FMV scenes, a musical and genuine Nordic horror.' },
    about: {"ru":"Писатель Алан Уэйк заперт в Тёмной Обители и пишет реальность, а агент ФБР Сага Андерсон расследует ритуальные убийства в Брайт Фоллс. Две переплетённые истории, выживание и лучшие живые вставки среди всех игр.","en":"Writer Alan Wake is trapped in the Dark Place rewriting reality, while FBI agent Saga Anderson investigates ritual murders in Bright Falls. Two interwoven stories, survival gameplay and the best live-action inserts in gaming."},
    feats: {"ru":["Два героя, два жанра и один сюжет","Доска расследований Саги — детектив внутри игры","Музыкальные сцены, которые невозможно забыть"],"en":["Two heroes, two genres, one story","Saga’s case board — a detective game within the game","Musical scenes you will not forget"]},
  },
  {
    t: 'Resident Evil 4 Remake', y: 2023, dev: 'Capcom', gr: ['horror', 'shooter', 'action'],
    tg: ['tense', 'epic', 'replayable', 'cinematic', 'difficult', 'zombie', 'loot'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [15, 40], dif: 4, pace: 5, rat: 93, mood: ['adrenaline', 'scare'], gp: 1,
    desc: { ru: 'Сельская Испания, топор в спину и чемоданы инвентаря: эталонный ремейк классики.', en: 'Rural Spain, an axe in your back and attache-case inventory: the gold standard remake.' },
    about: {"ru":"Полный ремейк классики 2005 года: Леон Кеннеди пробирается через испанскую глушь, заражённую паразитом лас-плагас, чтобы спасти дочь президента. Экшен стал современнее, стелс появился, а знакомые сцены переосмыслены без потери духа.","en":"A full remake of the 2005 classic: Leon Kennedy pushes through a Spanish countryside infected by the Las Plagas parasite to rescue the president’s daughter. The action is modernised, stealth is in, and famous scenes are reimagined without losing their spirit."},
    feats: {"ru":["Эталон ремейка: всё знакомое, всё новое","Битвы с толпой на нерве и ресурсах","Режим наёмников и ножевание как высший пилотаж"],"en":["The benchmark remake: familiar yet entirely new","Crowd fights on nerve and resources","The Mercenaries mode and knife-only runs as high art"]},
  },
  {
    t: 'Resident Evil 2 Remake', y: 2019, dev: 'Capcom', gr: ['horror', 'survival'],
    tg: ['tense', 'zombie', 'dark', 'difficult', 'replayable', 'linear', 'puzzles'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [10, 30], dif: 4, pace: 4, rat: 91, mood: ['scare', 'think'],
    desc: { ru: 'Раккун-Сити, полицейский участок и мистер X, который не перестаёт идти за вами.', en: 'Raccoon City, the police station and Mr. X, who never stops walking after you.' },
    about: {"ru":"Леон и Клэр в полицейском участке Раккун-Сити, полном зомби и тираном по имени Мистер Икс, который слышит выстрелы и идёт на звук. Две кампании с переплетающимися событиями и классическая структура «метроидвании» внутри здания.","en":"Leon and Claire in the Raccoon City police station, full of zombies and a Tyrant called Mr. X who hears gunshots and walks toward them. Two campaigns with interlocking events and a classic metroidvania structure inside the building."},
    feats: {"ru":["Мистер Икс — один из самых памятных преследователей в хоррорах","Две кампании за разных героев с уникальными сценами","Ремейк, задавший стандарт всей серии"],"en":["Mr. X — one of horror’s most memorable stalkers","Two campaigns with unique scenes per hero","The remake that set the standard for the series"]},
  },
  {
    t: 'Silent Hill 2 (2024)', y: 2024, dev: 'Bloober Team', gr: ['horror', 'adventure'],
    tg: ['storyrich', 'sad', 'dark', 'tense', 'philosophical', 'cinematic', 'slow'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'full', pv: 3990,
    len: [15, 25], dif: 3, pace: 2, rat: 87, mood: ['scare', 'feel', 'story', 'think'],
    desc: { ru: 'Туман, письмо от жены и монстры, которые говорят о вашей вине: ремейк главного психологического хоррора.', en: 'Fog, a letter from your wife and monsters that speak of your guilt: a remake of the definitive psychological horror.' },
    about: {"ru":"Ремейк культового психологического хоррора: Джеймс Сандерленд приходит в туманный Сайлент Хилл по письму умершей жены. Команда студии из Варшавы перенесла историю на современный движок, сохранив гнетущую атмосферу оригинала.","en":"A remake of the cult psychological horror: James Sunderland comes to fog-drenched Silent Hill following a letter from his dead wife. The Warsaw-based team carried the story onto a modern engine while keeping the original’s oppressive atmosphere."},
    feats: {"ru":["Пирамидоголовый на новой ступени ужаса","Сюжет, который обсуждают десятилетиями","Аккуратная модернизация без переписывания классики"],"en":["Pyramid Head terrifying on a new level","A story people have debated for decades","A careful modernisation that never rewrites the classic"]},
  },
  {
    t: 'Alien: Isolation', y: 2014, dev: 'Creative Assembly', gr: ['horror', 'stealth', 'shooter'],
    tg: ['scifi', 'tense', 'difficult', 'long', 'cinematic', 'dark'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1200,
    len: [18, 30], dif: 5, pace: 3, rat: 81, mood: ['scare', 'tense'],
    desc: { ru: 'Чужой не скриптуется, а охотится: 20 часов непрерывного напряжения в стиле первого фильма.', en: 'The alien does not script: it hunts. Twenty hours of unbroken tension in the style of the first film.' },
    about: {"ru":"Аманда Рипли ищет мать на станции «Севастополь», где охотится чужой с полноценным искусственным интеллектом: он слышит шаги, запоминает ваши привычки и проверяет вентиляции. Убежать нельзя — только прятаться и отвлекать.","en":"Amanda Ripley searches for her mother aboard the Sevastopol station, hunted by an Alien with true AI: it hears footsteps, learns your habits and checks the vents. You cannot outrun it — only hide and distract."},
    feats: {"ru":["Лучший ИИ-противник в истории хорроров","Эстетика «Чужого» 1979 года до последнего монитора","Датчик движения — самый страшный предмет в инвентаре"],"en":["The best AI antagonist in horror history","The 1979 Alien aesthetic down to the last monitor","The motion tracker — the scariest item in your inventory"]},
  },
  {
    t: 'Dead Space (2023)', y: 2023, dev: 'Motive', gr: ['horror', 'shooter', 'action'],
    tg: ['scifi', 'tense', 'epic', 'cinematic', 'photomode', 'dark'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [12, 25], dif: 4, pace: 4, rat: 89, mood: ['scare', 'adrenaline'],
    desc: { ru: 'Космический хоррор на разваливающемся корабле: расчленение как основная механика.', en: 'Space horror on a collapsing ship where dismemberment is the core mechanic.' },
    about: {"ru":"Ремейк космохоррора о инженере Айзеке Кларке, который прибывает чинить корабль «Ишимура» и находит экипаж, превращённый в некроморфов. Стратегическое расчленение, гравипушка и звук, который страшно слушать в наушниках.","en":"The remake of the space horror about engineer Isaac Clarke, who boards the USG Ishimura for repairs and finds the crew turned into Necromorphs. Strategic dismemberment, the gravity gun and sound design that is terrifying on headphones."},
    feats: {"ru":["Стрелять нужно по конечностям, а не в тело","Корабль как единое целое без загрузок","Интенсивный хоррор с режимом «новая игра+» и альтернативным финалом"],"en":["Shoot the limbs, not the body","One seamless ship with no loading screens","An intense horror with New Game+ and an alternate ending"]},
  },
  {
    t: 'SOMA', y: 2015, dev: 'Frictional Games', gr: ['horror', 'adventure'],
    tg: ['scifi', 'philosophical', 'dark', 'tense', 'underwater', 'walkingsim', 'storyrich'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'cheap', pv: 900,
    len: [9, 15], dif: 2, pace: 2, rat: 84, mood: ['think', 'scare', 'story'],
    desc: { ru: 'Подводная станция и вопрос, что значит быть человеком: страшно и очень умно.', en: 'An underwater station and the question of what makes you human: terrifying and very smart.' },
    about: {"ru":"Философский хоррор создателей Amnesia: Саймон просыпается на подводной станции ПАФОС-2, где машины уверены, что они люди. Игра меньше пугает, сколько ставит вопросы о сознании, которые остаются с игроком навсегда.","en":"A philosophical horror from the creators of Amnesia: Simon wakes in the undersea PATHOS-II station, where machines believe they are human. It unsettles more than it scares, asking questions about consciousness that stay with you forever."},
    feats: {"ru":["Один из сильнейших научно-фантастических сюжетов в играх","Хоррор без боя: только присутствие и давление","Финал, который пересказывают друг другу"],"en":["One of the strongest sci-fi stories in games","Combat-free horror built on presence and dread","An ending people retell to each other"]},
  },
  {
    t: 'Outlast', y: 2013, dev: 'Red Barrels', gr: ['horror', 'survival'],
    tg: ['tense', 'short', 'dark', 'difficult', 'linear', 'tense'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 500,
    len: [6, 10], dif: 4, pace: 4, rat: 80, mood: ['scare'],
    desc: { ru: 'Бежать и снимать на камеру: хоррор без оружия, где единственный враг — вы сами и ваша паника.', en: 'Run and film: horror without weapons where your only enemy is your own panic.' },
    about: {"ru":"Журналист с камерой ночного видения забирается в психлечебницу Маунт-Мэссив, где эксперименты корпорации пошли не по плану. Сражаться нельзя вовсе: только бежать, прятаться в шкафах и менять батарейки в камере.","en":"A journalist with a night-vision camera breaks into Mount Massive asylum, where corporate experiments went horribly wrong. There is no combat at all: only running, hiding in lockers and swapping camera batteries."},
    feats: {"ru":["Полная беззащитность как главный источник страха","Камера ночного видения — ваше единственное зрение","Классика хорроров 2010-х"],"en":["Total helplessness as the main source of fear","The night-vision camera as your only sight","A defining horror of the 2010s"]},
  },
  {
    t: 'Amnesia: The Bunker', y: 2023, dev: 'Frictional Games', gr: ['horror', 'survival'],
    tg: ['tense', 'dark', 'short', 'procedural', 'difficult', 'historical', 'puzzles'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1200,
    len: [5, 10], dif: 4, pace: 3, rat: 84, mood: ['scare', 'tense'],
    desc: { ru: 'Подземный бункер Первой мировой, генератор и зверь, который слышит каждый ваш шаг.', en: 'A WWI bunker, a generator and a beast that hears every step you take.' },
    about: {"ru":"Солдат Первой мировой заперт в бункере с существом, которое реагирует на каждый звук. Генератор требует топлива, свет отгоняет тварь, а всё остальное — импровизация: уровень генерирует события, и каждый забег складывается иначе.","en":"A WWI soldier is locked in a bunker with a creature that reacts to every sound. The generator needs fuel, light keeps the beast away, and the rest is improvisation: the level generates events so every playthrough unfolds differently."},
    feats: {"ru":["Полусистемный хоррор: тварь живёт по своим правилам","Свет как ресурс, за который борешься","Каждое прохождение непохоже на предыдущее"],"en":["A semi-systemic horror: the beast plays by its own rules","Light as a resource you fight for","Every playthrough differs from the last"]},
  },
  {
    t: 'Subnautica', y: 2018, dev: 'Unknown Worlds', gr: ['survival', 'adventure', 'sandbox'],
    tg: ['underwater', 'exploration', 'crafting', 'basebuilding', 'tense', 'relaxing', 'storyrich', 'colorful', 'openworld'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [30, 60], dif: 3, pace: 2, rat: 92, mood: ['explore', 'scare', 'relax'],
    desc: { ru: 'Океанская планета без карты и оружия: красота на глубине 20 метров и ужас на глубине 200.', en: 'An ocean planet with no map and no weapons: beauty at 20 meters, dread at 200.' },
    about: {"ru":"Кораблекрушение на океанической планете: стройте базу и батискафы, ныряйте всё глубже и выясняйте, что случилось с предшественниками. Чем глубже — тем темнее, больше и страшнее, но и награды там ценнее.","en":"Shipwrecked on an ocean planet: build bases and submersibles, dive ever deeper and find out what happened to those who came before. The deeper you go, the darker, bigger and scarier it gets — and the rewards are richer too."},
    feats: {"ru":["Страх глубины как игровая механика","Выживание без насилия: убегать умнее, чем драться","Продолжение Below Zero в том же мире"],"en":["Fear of the deep as a game mechanic","Non-violent survival: fleeing is smarter than fighting","The sequel Below Zero in the same world"]},
  },
  {
    t: 'The Long Dark', y: 2017, dev: 'Hinterland', gr: ['survival', 'simulator'],
    tg: ['hardcoresim', 'permadeath', 'difficult', 'slow', 'relaxing', 'tense', 'cozy', 'exploration'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [20, 500], dif: 5, pace: 1, rat: 84, mood: ['relax', 'tense', 'escape'],
    desc: { ru: 'Тихая канадская зима и одна ошибка, которая стоит всего: медитация о выживании в одиночестве.', en: 'A quiet Canadian winter and one mistake that costs everything: a meditation on solo survival.' },
    about: {"ru":"Выживание в канадской глуши после геомагнитной катастрофы: мороз, волки и собственная неосторожность убивают быстрее любого врага. Никаких зомби — только природа, планирование маршрутов и тёплая печка как смысл жизни.","en":"Survival in the Canadian wilderness after a geomagnetic disaster: cold, wolves and your own carelessness kill faster than any enemy. No zombies — just nature, route planning and a warm stove as life’s purpose."},
    feats: {"ru":["Самое честное «холодное» выживание","Сюжетный режим с историей пилота и доктора","Каждый выход из дома — маленькая экспедиция"],"en":["The most honest cold-weather survival","A story mode following a pilot and a doctor","Every trip outside is a small expedition"]},
  },
  {
    t: 'Hollow Knight', y: 2017, dev: 'Team Cherry', gr: ['metroidvania', 'platformer', 'action'],
    tg: ['difficult', 'dark', 'exploration', 'cute', 'handdrawn', 'lowsysreq', 'soundtrack', 'long', 'epic', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 500,
    len: [30, 60], dif: 4, pace: 3, rat: 95, mood: ['explore', 'adrenaline', 'story'],
    desc: { ru: 'Подземное королевство насекомых, нарисованное от руки: исследование, боссы и грусть.', en: 'A hand-drawn underground kingdom of insects: exploration, bosses and melancholy.' },
    about: {"ru":"Метроидвания про молчаливого рыцаря в подземном королевстве жуков Халлоунест: десятки взаимосвязанных зон, сложные боссы и меланхоличная история павшей цивилизации. За скромной ценой — десятки часов контента.","en":"A metroidvania about a silent knight in Hallownest, an underground kingdom of bugs: dozens of interconnected areas, tough bosses and the melancholic history of a fallen civilisation. Tens of hours of content for a modest price."},
    feats: {"ru":["Один из лучших миров в жанре — без единого лишнего экрана","Пантеон боссов для настоящих мастеров","Бесплатные дополнения сделали игру только больше"],"en":["One of the best worlds in the genre — not a wasted screen","The Pantheon boss gauntlet for true masters","Free expansions made the game even bigger"]},
  },
  {
    t: 'Ori and the Will of the Wisps', y: 2020, dev: 'Moon Studios', gr: ['platformer', 'metroidvania', 'adventure'],
    tg: ['sad', 'photomode', 'epic', 'soundtrack', 'handdrawn', 'exploration', 'colorful', 'cinematic', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [12, 25], dif: 4, pace: 4, rat: 90, mood: ['story', 'feel', 'escape', 'adrenaline'], gp: 1,
    desc: { ru: 'Плач по умирающему лесу: музыка, платформинг и эмоции в каждой сцене.', en: 'A lament for a dying forest: music, platforming and emotion in every frame.' },
    about: {"ru":"Платформер-метроидвания о духе Ори: акробатика доведённая до балета, рисованные пейзажи и оркестровый саундтрек. Боевая система и система духовных осколков заметно выросли по сравнению с первой частью.","en":"A metroidvania platformer about the spirit Ori: ballet-grade movement, painterly landscapes and an orchestral score. Combat and the Spirit Shard system grew markedly over the first game."},
    feats: {"ru":["Один из самых красивых платформеров в истории","Погони-эскейп-сцены с адреналином уровня лучших боссов","Трогательная история без единого слова пафоса"],"en":["One of the most beautiful platformers ever made","Escape sequences as thrilling as the best boss fights","A touching story without a word of bombast"]},
  },
  {
    t: 'Celeste', y: 2018, dev: 'Extremely OK Games', gr: ['platformer', 'action'],
    tg: ['difficult', 'storyrich', 'short', 'pixelart', 'lowsysreq', 'soundtrack', 'philosophical', 'easytolearn', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 700,
    len: [8, 30], dif: 5, pace: 5, rat: 92, mood: ['adrenaline', 'story'],
    desc: { ru: 'Прыжки по горе и история о тревоге: сложно, честно и лечит лучше терапии.', en: 'Climbing a mountain and a story about anxiety: hard, fair and more healing than therapy.' },
    about: {"ru":"Мадлен поднимается на гору Селест, а вместе с ней игрок проходит сотни экранов точнейшего платформинга. Каждая смерть чему-то учит, каждая глава — новая механика, а история о тревожности рассказана с редкой честностью.","en":"Madeline climbs Celeste Mountain while the player works through hundreds of precision platforming screens. Every death teaches something, every chapter adds a new mechanic, and the story about anxiety is told with rare honesty."},
    feats: {"ru":["Платформинг, где смерть — часть обучения, а не наказание","История о принятии себя, которая попадает в сердце","Главы для хардкорщиков после финала"],"en":["Platforming where death is part of learning, not punishment","A story about self-acceptance that lands","Post-game chapters for the hardcore"]},
  },
  {
    t: 'Hades', y: 2020, dev: 'Supergiant Games', gr: ['roguelike', 'action', 'rpg'],
    tg: ['mythology', 'replayable', 'storyrich', 'dialogheavy', 'soundtrack', 'colorful', 'endlessloop', 'difficult', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1200,
    len: [25, 100], dif: 4, pace: 5, rat: 93, mood: ['adrenaline', 'story', 'progress'], gp: 1,
    desc: { ru: 'Побег из подземного мира, где каждая смерть двигает сюжет и открывает новые диалоги.', en: 'Escaping the underworld where every death advances the plot and unlocks new dialogue.' },
    about: {"ru":"Загрей, сын Аида, прорубается из подземного мира на Олимп, умирая и возвращаясь снова. Рогалик, где каждая смерть продвигает сюжет: боги, призраки и сам отец реагируют на ваши провалы и победы.","en":"Zagreus, son of Hades, fights his way out of the Underworld to Olympus, dying and returning again. A roguelike where every death advances the story: gods, ghosts and his own father react to your failures and wins."},
    feats: {"ru":["Сюжет, который открывается именно через смерти","Боевая система с десятками жизнеспособных сборок","Идеальный пример «ещё одного забега»"],"en":["A story revealed precisely through dying","A combat system with dozens of viable builds","The perfect “one more run” game"]},
  },
  {
    t: 'Hades II', y: 2024, dev: 'Supergiant Games', gr: ['roguelike', 'action', 'rpg'],
    tg: ['mythology', 'replayable', 'storyrich', 'soundtrack', 'colorful', 'endlessloop', 'difficult', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'switch'], pr: 'mid', pv: 1990,
    len: [25, 100], dif: 4, pace: 5, rat: 89, mood: ['adrenaline', 'story', 'progress'],
    desc: { ru: 'Медея против титанов: тот же формула «ещё один забег», но с магией и новыми богами.', en: 'Melinoe against the Titans: the same one-more-run formula with magic and new gods.' },
    about: {"ru":"Продолжение рогалика от Supergiant: Мелиноя, сестра Загрея, идёт против Хроноса, титана времени. Магия, серебряные орудия и новый пантеон покровителей, а масштаб стал больше: новые биомы, система трав и переработанные механики.","en":"Supergiant’s sequel: Melinoë, sister of Zagreus, marches against Chronos, the Titan of Time. Witchcraft, silver weaponry and a new pantheon of patrons, with bigger scale — new biomes, a herb system and reworked mechanics."},
    feats: {"ru":["Новая героиня с собственной магией и стилем","Хронос — один из самых запоминающихся антагонистов студии","Больше глубины: травы, ковка, побочные активности"],"en":["A new heroine with her own magic and style","Chronos — one of the studio’s most memorable villains","More depth: herbs, forging, side activities"]},
  },
  {
    t: 'Dead Cells', y: 2018, dev: 'Motion Twin', gr: ['roguelike', 'action', 'platformer'],
    tg: ['procedural', 'difficult', 'replayable', 'pixelart', 'endlessloop', 'lowsysreq', 'replayable', 'steamdeck', 'controller'],
    md: ['solo', 'coopLocal'], pl: [1, 2], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1500,
    len: [20, 200], dif: 4, pace: 5, rat: 89, mood: ['adrenaline', 'progress'], coopQ: 6,
    desc: { ru: 'Метроидвания-рогалик с лучшим ощущением от боя: умирать приятно, потому что растёшь.', en: 'A metroidvania roguelike with the best combat feel: dying is fine because you keep growing.' },
    about: {"ru":"Рогалик-метроидвания в замке, который перестраивается после каждой смерти: стремительный бой десятками видов оружия, мутации и бесконечные петли прокачки. Темп такой, что пауза между забегами длится секунды.","en":"A roguelike metroidvania in a castle that rebuilds itself after every death: frantic combat with dozens of weapons, mutations and endless progression loops. The pace is such that breaks between runs last seconds."},
    feats: {"ru":["Один из самых быстрых боёвок в жанре","Ежедневные испытания и режимы для ветеранов","Годы бесплатных обновлений и кроссоверов"],"en":["One of the fastest-feeling combat systems in the genre","Daily challenges and modes for veterans","Years of free updates and crossovers"]},
  },
  {
    t: 'Slay the Spire', y: 2019, dev: 'Mega Crit', gr: ['card', 'roguelike', 'strategy'],
    tg: ['deckbuilding', 'endlessloop', 'difficult', 'replayable', 'lowsysreq', 'puzzles', 'procedural', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1100,
    len: [15, 500], dif: 4, pace: 2, rat: 93, mood: ['think', 'progress'],
    desc: { ru: 'Карточный рогалик, определивший жанр: строить колоду, считать ходы, страдать от плохих реликвий.', en: 'The card roguelike that defined the genre: build a deck, count turns, suffer bad relics.' },
    about: {"ru":"Карточный рогалик, задавший стандарт жанра: колода строится прямо по ходу подъёма на Шпиль, а каждая карта и реликвия меняют математику забега. Четыре героя с радикально разными стилями и сотни комбинаций.","en":"The deck-builder roguelike that set the genre standard: your deck grows as you climb the Spire, and every card and relic changes the run’s math. Four characters with radically different styles and hundreds of combinations."},
    feats: {"ru":["Игра, породившая целый поджанр","Идеальный баланс между случайностью и контролем","Один забег — полчаса, залипнуть можно на годы"],"en":["The game that spawned a whole subgenre","A perfect balance of randomness and control","Runs are half an hour; the game lasts for years"]},
  },
  {
    t: 'Balatro', y: 2024, dev: 'LocalThunk', gr: ['card', 'roguelike', 'puzzle'],
    tg: ['deckbuilding', 'endlessloop', 'lowsysreq', 'easytolearn', 'difficult', 'pixelart', 'replayable', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 800,
    len: [10, 500], dif: 3, pace: 2, rat: 92, mood: ['think', 'progress', 'relax'],
    desc: { ru: 'Покер плюс джокеры: одна партия — минута, но остановиться невозможно.', en: 'Poker plus jokers: one run takes a minute, but stopping is impossible.' },
    about: {"ru":"Покерный рогалик, в котором правила покера — только отправная точка: джокеры ломают подсчёт очков, планеты прокачивают комбинации, а цель — докрутить ставки до невозможных величин. Феномен 2024 года, идеален для коротких сессий.","en":"A poker roguelike where poker rules are only the starting point: Jokers break the scoring, Planets level up your hands, and the goal is pushing stakes to impossible numbers. The 2024 phenomenon, perfect for short sessions."},
    feats: {"ru":["«Ещё один забег» в чистом виде","Простые правила с бездонной глубиной сборок","Лучшая игра года по мнению десятков изданий"],"en":["“One more run” in its purest form","Simple rules, bottomless build depth","Named game of the year by dozens of outlets"]},
  },
  {
    t: 'The Binding of Isaac: Repentance', y: 2021, dev: 'Nicalis', gr: ['roguelike', 'action'],
    tg: ['dark', 'difficult', 'procedural', 'replayable', 'endlessloop', 'pixelart', 'loot', 'philosophical', 'steamdeck', 'controller'],
    md: ['solo', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1900,
    len: [30, 1000], dif: 5, pace: 4, rat: 87, mood: ['progress', 'escape', 'adrenaline'], coopQ: 6,
    desc: { ru: 'Слёзы младенца против библейских кошмаров: сотни предметов и тысячи часов на 100%.', en: 'A baby\u2019s tears against biblical nightmares: hundreds of items and thousands of hours to 100%.' },
    about: {"ru":"Рогалик про Айзека, сбегающего в подвал от фанатичной матери: случайные комнаты, сотни предметов и синергии, которые превращают слёзы героя в рельсотрон или рой мух. Версия Repentance собрала весь контент десяти лет разработки.","en":"A roguelike about Isaac, fleeing into the basement from a fanatical mother: random rooms, hundreds of items and synergies that turn the hero’s tears into a railgun or a swarm of flies. Repentance gathers a decade of content."},
    feats: {"ru":["Сотни предметов и тысячи синергий","Каждый забег может сломаться в лучшую сторону","Десятки часов до первого полного прохождения"],"en":["Hundreds of items, thousands of synergies","Every run can break in the best possible way","Dozens of hours before your first full clear"]},
  },
  {
    t: 'Return of the Obra Dinn', y: 2018, dev: 'Lucas Pope', gr: ['puzzle', 'mystery', 'adventure'],
    tg: ['historical', 'short', 'lowsysreq', 'philosophical', 'pixelart', 'puzzles'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1100,
    len: [8, 12], dif: 4, pace: 1, rat: 90, mood: ['think', 'story'],
    desc: { ru: 'Страховой детектив на корабле мертвецов: вы сами должны вывести судьбу каждого из 60 человек.', en: 'An insurance investigator on a ship of the dead: you must deduce all 60 fates yourself.' },
    about: {"ru":"Детектив в уникальном визуальном стиле однобитного мака: корабль «Обра Динн» вернулся без экипажа, а вам по застывшим сценам смертей нужно установить судьбу каждого из шестидесяти человек. Игра, где дедукция — единственный инструмент.","en":"A detective game in a unique 1-bit visual style: the ship Obra Dinn returns crewless, and from frozen death scenes you must determine the fate of all sixty people aboard. A game where deduction is your only tool."},
    feats: {"ru":["Жанр «детектив» в самом чистом виде","Визуальный стиль, который не спутать ни с чем","Награда BAFTA за лучший геймдизайн"],"en":["The detective genre in its purest form","A visual style unlike anything else","BAFTA winner for best game design"]},
  },
  {
    t: 'Outer Wilds', y: 2019, dev: 'Mobius Digital', gr: ['adventure', 'mystery', 'puzzle'],
    tg: ['space', 'exploration', 'philosophical', 'relaxing', 'tense', 'short', 'soundtrack', 'storyrich'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [20, 30], dif: 3, pace: 2, rat: 94, mood: ['explore', 'think', 'escape'],
    desc: { ru: '22 минуты до конца вселенной: прокачивается не персонаж, а ваши знания о мире.', en: 'Twenty-two minutes until the universe ends: the only progression is your own knowledge.' },
    about: {"ru":"Космическая археология в солнечной системе, застревающей в 22-минутной петле до взрыва солнца. Прогресс — только знания: поняв, как работает одна планета, вы открываете путь к следующей. Игру нельзя перепройти — её можно только понять.","en":"Space archaeology in a solar system stuck in a 22-minute loop before the sun explodes. Progress is knowledge only: understanding one planet unlocks the way to the next. The game cannot be replayed — only understood."},
    feats: {"ru":["Единственный в своём роде опыт — спойлеры действительно вредят","Каждая планета — отдельная физическая загадка","Финал, ради которого стоило всё это летать"],"en":["A one-of-a-kind experience — spoilers genuinely hurt","Each planet is its own physics puzzle","A finale worth every flight"]},
  },
  {
    t: 'Disco Elysium', y: 2019, dev: 'ZA/UM', gr: ['rpg', 'adventure'],
    tg: ['storyrich', 'dialogheavy', 'philosophical', 'dark', 'funny', 'modern', 'choices', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [25, 50], dif: 3, pace: 1, rat: 93, mood: ['story', 'think'],
    desc: { ru: 'Детектив с похмельем, где драка — это диалог: лучший текст в истории игр.', en: 'A hungover detective where fighting means talking: the best writing in games.' },
    about: {"ru":"Детектив-алкоголик просыпается без памяти в районе, где на заднем дворе висит труп, а в голове спорят двадцать четыре голоса — от Логики до Электрохимии. Ролевая игра без боёвки: всё решают диалоги, навыки-личности и ваши решения.","en":"An amnesiac alcoholic detective wakes in a district with a corpse hanging in the backyard and twenty-four voices arguing in his head — from Logic to Electrochemistry. A combat-free RPG: dialogues, personality skills and your choices decide everything."},
    feats: {"ru":["Лучший текст в истории ролевых игр","Навыки — это черты характера, которые с вами спорят","Политика, философия и нуар в одном флаконе"],"en":["The best writing in RPG history","Skills are personality traits that argue with you","Politics, philosophy and noir in one bottle"]},
  },
  {
    t: 'Undertale', y: 2015, dev: 'Toby Fox', gr: ['rpg', 'adventure'],
    tg: ['funny', 'sad', 'short', 'philosophical', 'cute', 'pixelart', 'lowsysreq', 'soundtrack', 'choices', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 500,
    len: [8, 20], dif: 3, pace: 3, rat: 92, mood: ['story', 'feel', 'laugh', 'think'],
    desc: { ru: 'Можно никого не убивать: RPG, которая помнит каждое ваше решение и отвечает на него.', en: 'You can spare everyone: an RPG that remembers every choice and answers it.' },
    about: {"ru":"Ребёнок падает в подземелье монстров, и только игрок решает: убивать всех или со всеми дружить. Игра помнит ваши поступки даже после перезапуска, а боёвка превращается то в ритм-игру, то в разговор по душам.","en":"A child falls into a monster underworld, and only the player decides: kill everyone or befriend everyone. The game remembers your actions even after a restart, and combat shifts between rhythm game and heart-to-heart."},
    feats: {"ru":["Игра, которая ломает четвёртую стену осознанно и с любовью","Три радикально разных финала","Саундтрек, который узнают с двух нот"],"en":["A game that breaks the fourth wall knowingly and lovingly","Three radically different endings","A soundtrack recognised in two notes"]},
  },
  {
    t: 'NieR: Automata', y: 2017, dev: 'PlatinumGames', gr: ['action', 'rpg'],
    tg: ['philosophical', 'sad', 'anime', 'epic', 'soundtrack', 'storyrich', 'replayable', 'cutscenes'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [30, 60], dif: 3, pace: 5, rat: 90, mood: ['story', 'feel', 'think', 'adrenaline'],
    desc: { ru: 'Андроиды, философия и пять концовок: игра, которую надо пройти дважды, чтобы понять.', en: 'Androids, philosophy and five endings: a game you must finish twice to understand.' },
    about: {"ru":"Андроиды 2B, 9S и A2 воюют с машинами на Земле будущего, пока сюжет постепенно разбирает вопросы сознания и смысла. Экшен от создателя Bayonetta сочетается с историей, которая рассказана в несколько прохождений.","en":"Androids 2B, 9S and A2 fight machines on a future Earth while the story slowly dissects questions of consciousness and meaning. Bayonetta-creator action fused with a tale told across multiple playthroughs."},
    feats: {"ru":["Боевая система ПлатинумГеймс в лучшей форме","Сюжет, который раскрывается только на третьем заходе","Финал, который невозможно забыть"],"en":["PlatinumGames combat at its finest","A story that only opens up on the third route","An ending you cannot forget"]},
  },
  {
    t: 'Persona 5 Royal', y: 2019, dev: 'Atlus', gr: ['rpg', 'adventure', 'tactics'],
    tg: ['jrpg', 'anime', 'tbs', 'storyrich', 'long', 'soundtrack', 'social', 'choices', 'cinematic', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'full', pv: 3990,
    len: [80, 130], dif: 3, pace: 2, rat: 93, mood: ['story', 'escape', 'progress'], gp: 1,
    desc: { ru: 'Японские школьники меняют мир изнутри дворца украденных сердец: стиль и музыка на максимум.', en: 'Japanese students change the world from inside palaces of stolen hearts: maximum style and music.' },
    about: {"ru":"Днём — школьник в Токио, вечером — фантомный вор, крадущий испорченные сердца взрослых из их дворцов-подсознаний. Сто часов жизни, где социальные связи усиливают боевую команду, а стиль бьёт через край в каждом меню.","en":"By day a Tokyo high-schooler, by night a Phantom Thief stealing corrupt adults’ hearts from palace-dungeons of their subconscious. A hundred hours of life where social links empower your battle party and style drips from every menu."},
    feats: {"ru":["Одна из самых стильных игр в истории","Двойная жизнь: школа, друзья и кража сердец","Версия Royal добавила целый семестр контента"],"en":["One of the most stylish games ever made","A double life: school, friends and heart-stealing","Royal adds a whole extra semester of content"]},
  },
  {
    t: 'Metaphor: ReFantazio', y: 2024, dev: 'Atlus', gr: ['rpg', 'adventure'],
    tg: ['jrpg', 'fantasy', 'tbs', 'storyrich', 'long', 'soundtrack', 'choices', 'social', 'anime'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [70, 100], dif: 3, pace: 3, rat: 91, mood: ['story', 'escape', 'progress'],
    desc: { ru: 'Фэнтезийные выборы короля от авторов Persona: политика, демоны и календарь на 5 месяцев.', en: 'A fantasy royal election from the Persona team: politics, demons and a five-month calendar.' },
    about: {"ru":"Фэнтезийная RPG от создателей Persona: королевство выбирает нового монарха, и гонка за троном превращается в путешествие по миру, полном предрассудков и древних чудовищ. Система «архетипов» развивает идею классов, а календарь — дедлайны и события.","en":"A fantasy RPG from the Persona creators: the kingdom elects a new monarch, and the race for the throne becomes a journey through a world of prejudice and ancient monsters. The Archetype system evolves class design, and the calendar drives deadlines and events."},
    feats: {"ru":["Лучшая RPG 2024 года по версии The Game Awards","Социальные связи и политические интриги в одном ритме","Арт Сигэнори Соэдзимы на пике формы"],"en":["The Game Awards 2024 Best RPG","Social bonds and political intrigue in one rhythm","Soejima’s art at its peak"]},
  },
  {
    t: 'Yakuza: Like a Dragon', y: 2020, dev: 'Ryu Ga Gotoku', gr: ['rpg', 'adventure', 'action'],
    tg: ['jrpg', 'funny', 'modern', 'storyrich', 'tbs', 'long', 'cinematic', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [45, 100], dif: 3, pace: 3, rat: 88, mood: ['story', 'laugh', 'escape'], gp: 1,
    desc: { ru: 'Бывший якудза становится героем пошаговых боёв, а по пути поёт караоке и ловит покемонов.', en: 'An ex-yakuza becomes a turn-based hero while singing karaoke and collecting creatures.' },
    about: {"ru":"Ичибан Касуга выходит из тюрьмы после восемнадцати лет за преступление, которого не совершал, и находит якудза совсем другими. Серия сменила жанр на пошаговую RPG, а город Иокогама стал новой площадкой для драмы, комедии и абсурдных подработок.","en":"Ichiban Kasuga leaves prison after eighteen years for a crime he didn’t commit and finds the yakuza utterly changed. The series switched to turn-based RPG combat, and Yokohama became the new stage for drama, comedy and absurd side jobs."},
    feats: {"ru":["Новый герой, которого невозможно не полюбить","Пошаговые бои с профессиями из повседневных работ","Фирменная смесь слёз и полного абсурда"],"en":["A new hero you cannot help but love","Turn-based battles with jobs from everyday life","The series’ trademark mix of tears and absurdity"]},
  },
  {
    t: 'Stardew Valley', y: 2016, dev: 'ConcernedApe', gr: ['simulator', 'rpg', 'sandbox'],
    tg: ['farming', 'cozy', 'relaxing', 'crafting', 'coopfocused', 'long', 'cute', 'pixelart', 'social', 'lowsysreq', 'mods', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 700,
    len: [50, 200], dif: 1, pace: 1, rat: 96, mood: ['relax', 'create', 'progress'], coopQ: 9,
    desc: { ru: 'Ферма, деревня и романтика: лучший способ замедлиться и провести с другом 100 спокойных часов.', en: 'A farm, a village and romance: the best way to slow down and spend 100 calm hours with a friend.' },
    about: {"ru":"Наследство деда оказывается заброшенной фермой, и игрок сам решает, чем заняться: урожаи, животные, шахты, рыбалка или отношения с жителями городка. Игра сделана одним человеком и стала эталоном уютных симуляторов жизни.","en":"Grandpa’s legacy turns out to be a run-down farm, and the player chooses the life: crops, animals, mines, fishing or friendships with the townsfolk. Made by one person, it became the benchmark of cosy life sims."},
    feats: {"ru":["Сотни часов контента и бесконечная ферма","Кооператив до четырёх игроков на одной ферме","Бесплатные обновления годами — версия 1.6 добавила ещё десятки часов"],"en":["Hundreds of hours of content on an endless farm","Co-op for up to four players on one farm","Free updates for years — version 1.6 added dozens more hours"]},
  },
  {
    t: 'A Short Hike', y: 2019, dev: 'adamgryu', gr: ['adventure', 'platformer'],
    tg: ['cozy', 'relaxing', 'short', 'cute', 'exploration', 'pixelart', 'lowsysreq', 'family', 'colorful', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 400,
    len: [1, 3], dif: 1, pace: 1, rat: 90, mood: ['relax', 'explore'],
    desc: { ru: 'Полтора часа в горах: идеальный «перерыв» между большими играми.', en: 'Ninety minutes in the mountains: the perfect break between big games.' },
    about: {"ru":"Птичка Клэр приехала на остров и хочет залезть на гору, чтобы поймать сигнал телефона. По пути — рыбалка, гонки с зайцами и десятки маленьких секретов. Проходится за вечер и оставляет ощущение отпуска.","en":"Claire the bird arrives on an island and wants to climb the mountain to get phone reception. Along the way: fishing, races with rabbits and dozens of tiny secrets. Beatable in an evening, and it leaves you feeling like you had a holiday."},
    feats: {"ru":["Идеальный масштаб: ни одной лишней минуты","Полёт и планирование — чистая радость","Отдых для головы после больших игр"],"en":["Perfect scale: not one wasted minute","Flying and gliding are pure joy","A palate cleanser between big games"]},
  },
  {
    t: 'Journey', y: 2012, dev: 'thatgamecompany', gr: ['adventure', 'platformer'],
    tg: ['relaxing', 'short', 'philosophical', 'soundtrack', 'epic', 'coopfocused', 'family', 'nonviolent', 'steamdeck', 'controller'],
    md: ['solo', 'coopOnline', 'async'], pl: [1, 2], pf: ['pc', 'ps', 'mobile'], pr: 'cheap', pv: 700,
    len: [2, 5], dif: 1, pace: 1, rat: 89, mood: ['relax', 'story', 'escape'], coopQ: 7,
    desc: { ru: 'Пустыня, музыка и безымянный попутчик: два часа, которые невозможно забыть.', en: 'A desert, music and a nameless companion: two hours you cannot forget.' },
    about: {"ru":"Странник в пустыне идёт к светящейся горе, а по пути может встретить другого игрока — без слов, только жесты и совместное скольжение по барханам. Опыт, который длится пару часов и запоминается навсегда.","en":"A robed traveller crosses the desert toward a glowing mountain and may meet another player along the way — no words, only gestures and gliding down dunes together. An experience that lasts a couple of hours and is remembered forever."},
    feats: {"ru":["Невербальная встреча с незнакомцем — уникальный формат","Музыка и пейзаж как одно целое","Классика, с которой начинают разговор об играх как искусстве"],"en":["Wordless encounters with strangers — a unique format","Music and landscape fused into one","The classic cited when games are called art"]},
  },
  {
    t: 'Firewatch', y: 2016, dev: 'Campo Santo', gr: ['adventure', 'mystery'],
    tg: ['walkingsim', 'storyrich', 'short', 'dialogheavy', 'relaxing', 'tense', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 900,
    len: [4, 7], dif: 1, pace: 1, rat: 84, mood: ['story', 'relax', 'think'],
    desc: { ru: 'Лето в лесу, только рация и голос на другом конце: история о побеге от прошлого.', en: 'A summer in the woods with only a radio and a voice on the other end: a story about running from the past.' },
    about: {"ru":"Генри сбежал от проблем на должность наблюдателя за пожарами в лесах Вайоминга, и единственная связь с миром — рация и начальница Делайла. История двух людей, рассказанная диалогами на фоне бесконечных сосен.","en":"Henry flees his problems to a fire lookout job in the Wyoming wilderness, and his only link to the world is a radio and his supervisor Delilah. A two-hander told in dialogue against endless pines."},
    feats: {"ru":["Диалоги, которые звучат как настоящая жизнь","Вайоминг, в который хочется переехать","Детектив о паранойе в декорациях нацпарка"],"en":["Dialogue that sounds like real life","A Wyoming you want to move to","A paranoia mystery set in a national park"]},
  },
  {
    t: 'What Remains of Edith Finch', y: 2017, dev: 'Giant Sparrow', gr: ['adventure', 'mystery'],
    tg: ['walkingsim', 'storyrich', 'short', 'sad', 'philosophical', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'cheap', pv: 900,
    len: [2, 4], dif: 1, pace: 1, rat: 89, mood: ['story', 'feel', 'think', 'relax'],
    desc: { ru: 'Два часа историй одной семьи, каждая в своей механике: финал бьёт прямо в грудь.', en: 'Two hours of one family\u2019s stories, each with its own mechanic: the ending hits hard.' },
    about: {"ru":"Эдит возвращается в дом семьи Финч, где каждая комната — история родственника, погибшего при странных обстоятельствах. Антология коротких историй, каждая со своей механикой, — два часа, которые читаются как роман.","en":"Edith returns to the Finch house, where every room holds the story of a relative who died in strange circumstances. An anthology of short tales, each with its own mechanic — two hours that read like a novel."},
    feats: {"ru":["Каждая история — новый способ играть","Магический реализм без единого спецэффекта","Лучший «симулятор ходьбы» с настоящим сердцем"],"en":["Every story is a new way to play","Magical realism without a single gimmick","The best walking simulator with a real heart"]},
  },
  {
    t: 'Detroit: Become Human', y: 2018, dev: 'Quantic Dream', gr: ['adventure', 'mystery'],
    tg: ['scifi', 'storyrich', 'choices', 'cinematic', 'cutscenes', 'philosophical', 'epic', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 1990,
    len: [12, 25], dif: 2, pace: 3, rat: 85, mood: ['story', 'think'],
    desc: { ru: 'Три андроида, тысячи веток сюжета и постоянное «а что было бы, если…».', en: 'Three androids, thousands of story branches and constant what-ifs.' },
    about: {"ru":"Детройт 2038 года: андроиды обретают сознание, а три истории — полицейской машины, сиделки и лидера восстания — сходятся в одну. Каждое решение фиксируется в таблице последствий, и финалов у игры десятки.","en":"Detroit 2038: androids gain consciousness, and three stories — a police unit, a caretaker and the rebellion’s leader — converge into one. Every decision is tracked in a consequence chart, and the game has dozens of endings."},
    feats: {"ru":["Дерево решений, которое видно после каждой главы","Три переплетающиеся истории в одном городе","Сценарий, написанный как сериал-антология"],"en":["A decision tree revealed after every chapter","Three interwoven stories in one city","A script written like an anthology series"]},
  },
  {
    t: 'Until Dawn', y: 2015, dev: 'Supermassive Games', gr: ['horror', 'adventure'],
    tg: ['cinematic', 'choices', 'tense', 'short', 'dark', 'coopfocused', 'cutscenes'],
    md: ['solo', 'coopLocal'], pl: [1, 8], pf: ['pc', 'ps'], pr: 'mid', pv: 1990,
    len: [8, 12], dif: 2, pace: 3, rat: 82, mood: ['scare', 'laugh'], coopQ: 9,
    desc: { ru: 'Слэшер-фильм, где вы решаете, кто доживёт до утра: идеально смотреть и играть компанией.', en: 'A slasher movie where you decide who survives: perfect to play with a crowd.' },
    about: {"ru":"Восемь подростков на горном курорте, и до рассвета доживут не все: каждое решение и каждая мелочь (вплоть до того, не пошевелились ли вы) меняют, кто выживет. Интерактивный слэшер с механикой «эффекта бабочки».","en":"Eight teenagers on a mountain resort, and not all of them will see dawn: every choice and tiny detail — even whether you stayed still — changes who survives. An interactive slasher with a butterfly-effect mechanic."},
    feats: {"ru":["Выживает кто угодно — даже все или никто","Правило «не двигайся» в сценах с монстром","Ремейк 2024 года обновил графику и сцены"],"en":["Anyone can survive — even all of them, or none","The “don’t move” scenes with the monster","The 2024 remake refreshed visuals and scenes"]},
  },
  {
    t: 'The Quarry', y: 2022, dev: 'Supermassive Games', gr: ['horror', 'adventure'],
    tg: ['cinematic', 'choices', 'tense', 'coopfocused', 'short', 'dark', 'funny'],
    md: ['solo', 'coopOnline', 'coopLocal'], pl: [1, 8], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [8, 12], dif: 2, pace: 3, rat: 79, mood: ['scare', 'laugh'], coopQ: 9,
    desc: { ru: 'Летний лагерь, оборотни и восемь голосов за одним экраном — вечерний ритуал для компании.', en: 'Summer camp, werewolves and eight votes on one screen: a group ritual for the evening.' },
    about: {"ru":"Духовный наследник Until Dawn: вожатые летнего лагеря остаются на последнюю ночь и встречают нечто в лесу. Киношный хоррор с девятью героями, режимом «киновечеринки» для компании и сотнями развилок сюжета.","en":"The spiritual successor to Until Dawn: summer-camp counsellors stay for one last night and meet something in the woods. A cinematic horror with nine characters, a movie-night mode for groups and hundreds of story branches."},
    feats: {"ru":["Режим «смотри вместе»: компания голосует за решения","Каждый герой может дожить или не дожить","Хоррор-оммаж сразу нескольким десятилетиям жанра"],"en":["A watch-together mode where the group votes on choices","Every counsellor can live or die","A horror homage spanning decades of the genre"]},
  },
  {
    t: 'The Elder Scrolls V: Skyrim', y: 2011, dev: 'Bethesda', gr: ['rpg', 'action', 'sandbox'],
    tg: ['openworld', 'fantasy', 'exploration', 'mods', 'endless', 'relaxing', 'epic', 'lowsysreq', 'long'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [50, 500], dif: 2, pace: 2, rat: 88, mood: ['explore', 'escape', 'create'],
    desc: { ru: 'Драконы, гильдии и моды: мир, в который можно возвращаться десятилетиями.', en: 'Dragons, guilds and mods: a world you can return to for decades.' },
    about: {"ru":"Довакин возвращается, чтобы остановить дракона Алдуина, но настоящая игра — в самом Скайриме: сотни подземелий, гильдии, крафт и истории, которые находятся сами. Моды превращают игру в конструктор, живущий уже второе десятилетие.","en":"The Dragonborn returns to stop the dragon Alduin, but the real game is Skyrim itself: hundreds of dungeons, guilds, crafting and stories that find you on their own. Mods turn it into a construction set that has lived for a second decade."},
    feats: {"ru":["Мир, в котором каждый угол хранит историю","Свобода быть кем угодно: вор, маг, оборотень, вампир","Бесконечная жизнь благодаря модам"],"en":["A world where every corner holds a story","Freedom to be anyone: thief, mage, werewolf, vampire","Endless life thanks to mods"]},
  },
  {
    t: 'Dragon Age: The Veilguard', y: 2024, dev: 'BioWare', gr: ['rpg', 'action', 'adventure'],
    tg: ['storyrich', 'fantasy', 'choices', 'cinematic', 'dialogheavy', 'squad', 'long', 'cutscenes'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [40, 70], dif: 2, pace: 3, rat: 72, mood: ['story', 'escape'], gp: 1,
    desc: { ru: 'Команда героев против богов: классическая BioWare с романтикой и тактическими паузами.', en: 'A hero squad against gods: classic BioWare with romance and tactical pauses.' },
    about: {"ru":"Новая глава саги BioWare: Солас собирается разорвать Завесу, и команда из семи спутников пытается его остановить. Бой стал экшеном в реальном времени с тактической паузой, а решения по-прежнему формируют Тедас и отношения внутри отряда.","en":"The next chapter of BioWare’s saga: Solas plans to tear down the Veil, and a team of seven companions tries to stop him. Combat is real-time action with tactical pauses, and decisions still shape Thedas and your relationships within the squad."},
    feats: {"ru":["Семь спутников с личными квестами и романами","Экшен-боёвка с паузой — впервые в серии","Знакомый Тедас с новыми регионами"],"en":["Seven companions with personal quests and romances","Action combat with pause — a first for the series","A familiar Thedas with new regions"]},
  },
  {
    t: 'Assassin\u2019s Creed Odyssey', y: 2018, dev: 'Ubisoft', gr: ['rpg', 'action', 'adventure'],
    tg: ['openworld', 'historical', 'mythology', 'long', 'exploration', 'photomode', 'grind'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 2490,
    len: [50, 150], dif: 3, pace: 3, rat: 84, mood: ['explore', 'adrenaline', 'escape'],
    desc: { ru: 'Древняя Греция, море и 100 часов: исследовать античный мир интереснее, чем его сюжет.', en: 'Ancient Greece, the sea and 100 hours: exploring antiquity is better than its plot.' },
    about: {"ru":"Греция эпохи Пелопоннесской войны: Алексий или Кассандра — наёмник с копьём Леонида — оказывается в центре заговора культа Космоса. Самая ролевая часть серии с диалогами, выборами, морскими сражениями и сотней часов контента.","en":"Greece during the Peloponnesian War: Alexios or Kassandra — a mercenary wielding Leonidas’ spear — ends up at the heart of the Cult of Kosmos conspiracy. The most RPG-like entry, with dialogues, choices, naval battles and a hundred hours of content."},
    feats: {"ru":["Эгейское море под парусом — отдельное удовольствие","Выборы влияют на семью героя и финал","Мифы Греции как реальные боссы"],"en":["Sailing the Aegean is a joy in itself","Choices shape the hero’s family and the ending","Greek myths as actual boss fights"]},
  },
  {
    t: 'Armored Core VI: Fires of Rubicon', y: 2023, dev: 'FromSoftware', gr: ['action', 'shooter'],
    tg: ['mecha', 'difficult', 'scifi', 'epic', 'loot', 'tense'],
    md: ['solo', 'pvpOnline'], pl: [1, 6], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [20, 60], dif: 5, pace: 5, rat: 87, mood: ['adrenaline', 'progress'],
    desc: { ru: 'Сборка меха из сотен деталей и боссы, которых нужно разобрать по фазам.', en: 'Building a mech from hundreds of parts and bosses you must break down by phases.' },
    about: {"ru":"Мех-экшен FromSoftware: наёмник 621 сражается за корпорации на планете Рубикон, где вещество Коралл стало причиной войны. Сборка меха из десятков деталей меняет стиль боя радикальнее, чем в любом другом экшене.","en":"A FromSoftware mech action: mercenary 621 fights for corporations on planet Rubicon, where the Coral substance ignited a war. Building your mech from dozens of parts shifts your playstyle more radically than in any other action game."},
    feats: {"ru":["Конструктор робота как главный геймплей","Скорость и вертикальность боёв уровня FromSoftware","Три концовки и новые игры+ с другими миссиями"],"en":["The mech garage as the core gameplay","FromSoftware-grade speed and verticality in combat","Three endings and New Game+ with different missions"]},
  },
  {
    t: 'Katana ZERO', y: 2019, dev: 'Askiisoft', gr: ['action', 'platformer'],
    tg: ['cyberpunk', 'pixelart', 'difficult', 'short', 'soundtrack', 'storyrich', 'bullettime', 'lowsysreq', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'cheap', pv: 600,
    len: [5, 12], dif: 4, pace: 5, rat: 86, mood: ['adrenaline', 'story'],
    desc: { ru: 'Неонуар про наёмника с замедлением времени: идеальные 5 часов, где всё работает на ритм.', en: 'Neon noir about a hitman with bullet time: perfect five hours where everything serves the rhythm.' },
    about: {"ru":"Неонуарный экшен про самурая с катаной и способностью замедлять время: каждый уровень — хореография на одно касание, где смерть мгновенна, а перезапуск — моментальный. Стиль, синтвейв и сюжет, который внезапно оказывается глубже, чем кажется.","en":"A neo-noir action game about a katana-wielding samurai who can slow time: every level is one-hit choreography where death is instant and restart is instant. Style, synthwave and a plot that turns out deeper than it looks."},
    feats: {"ru":["Одна смерть — один вдох, и снова в бой","Синтвейв-саундтрек, под который хочется двигаться","Сюжет с неожиданным вторым дном"],"en":["One death, one breath, back into the fight","A synthwave soundtrack that makes you move","A story with an unexpected second layer"]},
  },
];
