/** Каталог, часть D — современные релизы, милитари-шутеры, экстракшн, ритм-игры, новеллы, мобильные. */
export const PART_D = [
  {
    t: 'Clair Obscur: Expedition 33', y: 2025, dev: 'Sandfall Interactive', gr: ['rpg', 'adventure', 'tactics'],
    tg: ['storyrich', 'tbs', 'sad', 'fantasy', 'epic', 'cinematic', 'soundtrack', 'photomode', 'cutscenes', 'choices'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [30, 60], dif: 4, pace: 3, rat: 94, mood: ['story', 'feel', 'think', 'adrenaline'], gp: 1,
    desc: { ru: 'Художница стирает людей по годам, а отряд идёт её остановить: главная сенсация 2025 года.', en: 'A Paintress erases people by age and an expedition marches to stop her: the breakout hit of 2025.' },
  },
  {
    t: 'Hollow Knight: Silksong', y: 2025, dev: 'Team Cherry', gr: ['metroidvania', 'platformer', 'action'],
    tg: ['difficult', 'handdrawn', 'exploration', 'soundtrack', 'long', 'epic', 'lowsysreq', 'controller', 'steamdeck'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1500,
    len: [30, 60], dif: 5, pace: 5, rat: 92, mood: ['adrenaline', 'explore', 'story'], gp: 1,
    desc: { ru: 'Хорнет против нового королевства: быстрее, злее и воздушнее первой части.', en: 'Hornet against a new kingdom: faster, meaner and airier than the first game.' },
  },
  {
    t: 'Kingdom Come: Deliverance II', y: 2025, dev: 'Warhorse Studios', gr: ['rpg', 'adventure', 'simulator'],
    tg: ['historical', 'realistic', 'openworld', 'storyrich', 'hardcoresim', 'long', 'choices', 'slow', 'cinematic', 'difficult'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [60, 150], dif: 4, pace: 2, rat: 88, mood: ['story', 'explore', 'think'],
    desc: { ru: 'Чешское средневековье без магии: меч, репутация и запоминание рецептов зелий.', en: 'Medieval Bohemia without magic: swordplay, reputation and memorizing potion recipes.' },
  },
  {
    t: 'STALKER 2: Heart of Chornobyl', y: 2024, dev: 'GSC Game World', gr: ['shooter', 'survival', 'horror'],
    tg: ['postapo', 'openworld', 'tense', 'dark', 'hardcoresim', 'difficult', 'exploration', 'long', 'epic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'xbox'], pr: 'full', pv: 3990,
    len: [40, 100], dif: 4, pace: 3, rat: 74, mood: ['tense', 'explore', 'scare'], gp: 1,
    desc: { ru: 'Зона, аномалии и мутанты: выживание, где патроны считают, а погода убивает.', en: 'The Zone, anomalies and mutants: survival where you count bullets and weather kills.' },
  },
  {
    t: 'Warhammer 40,000: Space Marine 2', y: 2024, dev: 'Saber Interactive', gr: ['shooter', 'action'],
    tg: ['coopfocused', 'epic', 'scifi', 'squad', 'cinematic', 'loot', 'grind', 'difficult', 'gpuheavy'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 6], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [15, 200], dif: 4, pace: 5, rat: 83, mood: ['adrenaline', 'progress', 'adrenaline'], coopQ: 9,
    desc: { ru: 'Титус против тысяч тиранидов: мясной кооп, где на экране реально сотни врагов.', en: 'Titus against thousands of Tyranids: meaty co-op with genuinely hundreds of enemies on screen.' },
  },
  {
    t: 'Peak', y: 2025, dev: 'Aggro Crab', gr: ['survival', 'party', 'adventure'],
    tg: ['coopfocused', 'voicechat', 'funny', 'tense', 'procedural', 'difficult', 'wacky', 'cute'],
    md: ['coopOnline'], pl: [1, 4], pf: ['pc'], pr: 'cheap', pv: 400,
    len: [10, 100], dif: 3, pace: 3, rat: 90, mood: ['laugh', 'adrenaline'], coopQ: 10,
    desc: { ru: 'Восхождение на гору с друзьями, где голод, холод и ваша же верёвка убивают чаще скал.', en: 'Climbing a mountain with friends where hunger, cold and your own rope kill more often than rocks.' },
  },
  {
    t: 'The Alters', y: 2025, dev: '11 bit studios', gr: ['survival', 'adventure', 'simulator'],
    tg: ['scifi', 'storyrich', 'choices', 'basebuilding', 'management', 'tense', 'philosophical', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 3990,
    len: [20, 40], dif: 3, pace: 2, rat: 83, mood: ['story', 'think', 'create'], gp: 1,
    desc: { ru: 'Разные версии себя самого как рабочие смены: выживание, менеджмент и разговоры с собой.', en: 'Different versions of yourself as shift workers: survival, management and talking to yourself.' },
  },
  {
    t: 'Schedule I', y: 2025, dev: 'TVGS', gr: ['simulator', 'sandbox', 'strategy'],
    tg: ['tycoon', 'management', 'coopfocused', 'grind', 'funny', 'dark', 'mods', 'lowsysreq', 'modern'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc'], pr: 'cheap', pv: 900,
    len: [20, 200], dif: 3, pace: 2, rat: 89, mood: ['progress', 'create', 'laugh'], coopQ: 9,
    desc: { ru: 'Криминальная империя от одного гаража: менеджмент, торговля и кооп с друзьями.', en: 'A criminal empire from a single garage: management, trading and co-op with friends.' },
  },
  {
    t: 'Marvel Rivals', y: 2024, dev: 'NetEase', gr: ['shooter', 'action'],
    tg: ['pvpfocused', 'squad', 'colorful', 'easytolearn', 'crosplay', 'social', 'epic', 'voicechat'],
    md: ['pvpOnline'], pl: [1, 12], pf: ['pc', 'ps', 'xbox'], pr: 'free', pv: 0,
    len: [20, 1000], dif: 3, pace: 5, rat: 78, mood: ['adrenaline', 'compete', 'laugh'], coopQ: 8,
    desc: { ru: 'Героический шутер 6×6 с разрушаемыми локациями: самый весёлый хаос для компании.', en: 'A 6v6 hero shooter with destructible maps: the most fun chaos for a group.' },
  },
  {
    t: 'Escape from Tarkov', y: 2017, dev: 'Battlestate Games', gr: ['shooter', 'survival', 'simulator'],
    tg: ['hardcoresim', 'pvpfocused', 'tense', 'realistic', 'loot', 'difficult', 'grind', 'postapo', 'coopfocused', 'voicechat'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 5], pf: ['pc'], pr: 'full', pv: 3500,
    len: [50, 1000], dif: 5, pace: 2, rat: 74, mood: ['tense', 'progress', 'adrenaline'], coopQ: 8,
    desc: { ru: 'Экстракшн-шутер без жалости: потерять снаряжение за 40 минут рейда — обычное дело.', en: 'A ruthless extraction shooter: losing 40 minutes of gear in a raid is just Tuesday.' },
  },
  {
    t: 'Hunt: Showdown 1896', y: 2018, dev: 'Crytek', gr: ['shooter', 'horror', 'survival'],
    tg: ['pvpfocused', 'coopfocused', 'tense', 'historical', 'dark', 'voicechat', 'hardcoresim', 'difficult', 'permadeath'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 3], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 2490,
    len: [30, 500], dif: 5, pace: 3, rat: 80, mood: ['tense', 'adrenaline'], coopQ: 9,
    desc: { ru: 'Болота Луизианы, охотники на монстров и другие игроки, которые охотятся на вас.', en: 'Louisiana swamps, monster hunters and other players hunting you instead.' },
  },
  {
    t: 'Ready or Not', y: 2023, dev: 'VOID Interactive', gr: ['shooter', 'tactics', 'simulator'],
    tg: ['coopfocused', 'hardcoresim', 'tense', 'realistic', 'squad', 'voicechat', 'difficult', 'modern'],
    md: ['solo', 'coopOnline'], pl: [1, 5], pf: ['pc'], pr: 'full', pv: 2990,
    len: [20, 200], dif: 5, pace: 3, rat: 82, mood: ['tense', 'adrenaline', 'think'], coopQ: 10,
    desc: { ru: 'SWAT-операции с приказами и заложниками: чистый тактический кооп без беготни.', en: 'SWAT operations with orders and hostages: pure tactical co-op without the running and gunning.' },
  },
  {
    t: 'GTFO', y: 2021, dev: '10 Chambers', gr: ['shooter', 'horror', 'tactics'],
    tg: ['coopfocused', 'difficult', 'dark', 'voicechat', 'tense', 'squad', 'tense'],
    md: ['coopOnline'], pl: [1, 4], pf: ['pc'], pr: 'mid', pv: 1990,
    len: [30, 200], dif: 5, pace: 3, rat: 84, mood: ['tense', 'adrenaline'], coopQ: 10,
    desc: { ru: 'Хардкорный кооп для четырёх: один шумный выстрел убивает всю команду.', en: 'Hardcore four-player co-op where one loud shot kills the whole team.' },
  },
  {
    t: 'Risk of Rain 2', y: 2020, dev: 'Hopoo Games', gr: ['roguelike', 'shooter', 'action'],
    tg: ['coopfocused', 'loot', 'procedural', 'difficult', 'endlessloop', 'replayable', 'epic'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1200,
    len: [20, 300], dif: 4, pace: 5, rat: 90, mood: ['adrenaline', 'progress'], coopQ: 9, gp: 1,
    desc: { ru: 'Сложность растёт каждую минуту, а билды становятся абсурдными: кооп-рогалик про математику.', en: 'Difficulty scales every minute and builds become absurd: a co-op roguelike about math.' },
  },
  {
    t: 'Remnant II', y: 2023, dev: 'Gunfire Games', gr: ['shooter', 'rpg', 'action'],
    tg: ['coopfocused', 'loot', 'procedural', 'difficult', 'soulslike', 'dark', 'replayable', 'long'],
    md: ['solo', 'coopOnline'], pl: [1, 3], pf: ['pc', 'ps', 'xbox'], pr: 'full', pv: 2490,
    len: [30, 200], dif: 4, pace: 4, rat: 85, mood: ['adrenaline', 'progress'], coopQ: 9, gp: 1,
    desc: { ru: 'Соулслайк с пушками и процедурными мирами: идеально проходится втроём.', en: 'A soulslike with guns and procedural worlds: perfect to clear as a trio.' },
  },
  {
    t: 'Tom Clancy\u2019s Rainbow Six Siege', y: 2015, dev: 'Ubisoft', gr: ['shooter', 'tactics'],
    tg: ['pvpfocused', 'squad', 'voicechat', 'difficult', 'replayable', 'grind', 'realistic', 'modern'],
    md: ['pvpOnline', 'coopOnline'], pl: [1, 10], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1200,
    len: [30, 2000], dif: 5, pace: 4, rat: 80, mood: ['compete', 'adrenaline', 'think'], coopQ: 8,
    desc: { ru: 'Разрушаемые стены и одна жизнь на раунд: тактический шутер с самым высоким порогом входа.', en: 'Destructible walls and one life per round: the tactical shooter with the steepest learning curve.' },
  },
  {
    t: 'Halo Infinite', y: 2021, dev: '343 Industries', gr: ['shooter', 'action'],
    tg: ['scifi', 'coopfocused', 'pvpfocused', 'epic', 'squad', 'crosplay'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 24], pf: ['pc', 'xbox'], pr: 'free', pv: 0,
    len: [20, 500], dif: 3, pace: 4, rat: 78, mood: ['adrenaline', 'compete', 'explore'], coopQ: 9, gp: 1,
    desc: { ru: 'Мастер Чиф, крюк-кошка и лучшая стрельба в серии: кампания вчетвером и бесплатный мультиплеер.', en: 'Master Chief, a grappling hook and the best shooting in the series: four-player campaign, free multiplayer.' },
  },
  {
    t: 'Gears 5', y: 2019, dev: 'The Coalition', gr: ['shooter', 'action'],
    tg: ['coopfocused', 'splitscreen', 'epic', 'scifi', 'squad', 'cinematic', 'tense'],
    md: ['solo', 'coopOnline', 'coopLocal', 'pvpOnline'], pl: [1, 6], pf: ['pc', 'xbox'], pr: 'mid', pv: 1990,
    len: [15, 100], dif: 3, pace: 5, rat: 84, mood: ['adrenaline', 'story'], coopQ: 9, gp: 1,
    desc: { ru: 'Укрытия, мясорубка и поездка на санях по льду: классический кооп-шутер на двоих-троих.', en: 'Cover, gore and a sled ride across ice: the classic two-to-three player co-op shooter.' },
  },
  {
    t: 'Titanfall 2', y: 2016, dev: 'Respawn', gr: ['shooter', 'action'],
    tg: ['mecha', 'scifi', 'cinematic', 'storyrich', 'short', 'epic', 'tense', 'easytolearn'],
    md: ['solo', 'pvpOnline'], pl: [1, 16], pf: ['pc', 'ps', 'xbox'], pr: 'cheap', pv: 900,
    len: [6, 60], dif: 3, pace: 5, rat: 90, mood: ['adrenaline', 'story'],
    desc: { ru: 'Паркур, пилот и ТИТАН BT-7274: лучшая короткая кампания в шутерах за десятилетие.', en: 'Parkour, a pilot and BT-7274: the best short shooter campaign in a decade.' },
  },
  {
    t: 'Metro Exodus', y: 2019, dev: '4A Games', gr: ['shooter', 'survival', 'horror'],
    tg: ['postapo', 'storyrich', 'cinematic', 'dark', 'tense', 'exploration', 'choices', 'realistic', 'epic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1990,
    len: [15, 30], dif: 4, pace: 3, rat: 85, mood: ['story', 'tense', 'explore'],
    desc: { ru: 'Паровоз через постсоветскую пустошь: редкая игра, где тишина страшнее перестрелки.', en: 'A train across a post-Soviet wasteland: rare in making silence scarier than gunfire.' },
  },
  {
    t: 'Fallout 4', y: 2015, dev: 'Bethesda', gr: ['rpg', 'shooter', 'adventure'],
    tg: ['postapo', 'openworld', 'exploration', 'crafting', 'basebuilding', 'loot', 'mods', 'long', 'lowsysreq'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1500,
    len: [40, 300], dif: 3, pace: 3, rat: 84, mood: ['explore', 'progress', 'create'],
    desc: { ru: 'Пустошь, поселения и радио: строить базы и искать историю в каждой записке.', en: 'The wasteland, settlements and radio: build bases and find stories in every note.' },
  },
  {
    t: 'Fallout 76', y: 2018, dev: 'Bethesda', gr: ['rpg', 'shooter', 'mmo'],
    tg: ['postapo', 'openworld', 'coopfocused', 'mmosocial', 'basebuilding', 'crafting', 'long', 'social', 'exploration'],
    md: ['solo', 'coopOnline', 'mmo', 'pvpOnline'], pl: [1, 24], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1900,
    len: [50, 1000], dif: 3, pace: 3, rat: 72, mood: ['explore', 'create', 'progress'], coopQ: 9, gp: 1,
    desc: { ru: 'Аппалачия онлайн: дружелюбный кооп-выживальщик, где незнакомцы дарят вам стимпаки.', en: 'Appalachia online: a friendly co-op survival where strangers gift you stimpaks.' },
  },
  {
    t: 'Dying Light 2: Stay Human', y: 2022, dev: 'Techland', gr: ['action', 'survival', 'horror'],
    tg: ['zombie', 'openworld', 'coopfocused', 'tense', 'long', 'choices', 'modern'],
    md: ['solo', 'coopOnline'], pl: [1, 4], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 2490,
    len: [25, 100], dif: 3, pace: 4, rat: 78, mood: ['adrenaline', 'explore'], coopQ: 9,
    desc: { ru: 'Паркур по крышам города зомби: ночью выходить не стоит, но именно это интересно.', en: 'Parkour across a zombie city\u2019s rooftops: you should not go out at night, which is exactly the appeal.' },
  },
  {
    t: 'Days Gone', y: 2019, dev: 'Bend Studio', gr: ['action', 'adventure', 'horror'],
    tg: ['zombie', 'openworld', 'storyrich', 'tense', 'long', 'postapo', 'realistic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps'], pr: 'mid', pv: 2490,
    len: [40, 80], dif: 3, pace: 3, rat: 76, mood: ['story', 'tense', 'explore'],
    desc: { ru: 'Мотобайк, орды фриков и медленное открытие истории: недооценённый зомби-опенворлд.', en: 'A motorbike, hordes of freakers and a slow burn story: an underrated open-world zombie game.' },
  },
  {
    t: 'Sifu', y: 2022, dev: 'Sloclap', gr: ['action', 'fighting'],
    tg: ['difficult', 'short', 'cinematic', 'soundtrack', 'modern', 'tense'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [10, 30], dif: 5, pace: 5, rat: 85, mood: ['adrenaline', 'progress'],
    desc: { ru: 'Кунг-фу про месть: каждая смерть старит вас, а учиться драться придётся по-настоящему.', en: 'Kung fu revenge where every death ages you: you genuinely have to learn to fight.' },
  },
  {
    t: 'Hi-Fi Rush', y: 2023, dev: 'Tango Gameworks', gr: ['action', 'rhythm', 'platformer'],
    tg: ['colorful', 'funny', 'easytolearn', 'soundtrack', 'short', 'anime', 'controller', 'steamdeck'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox'], pr: 'mid', pv: 1990,
    len: [10, 20], dif: 3, pace: 5, rat: 89, mood: ['adrenaline', 'laugh'], gp: 1,
    desc: { ru: 'Экшен в ритме рока: всё вокруг подстраивается под бит, даже ваши удары.', en: 'Rock-opera action where the world syncs to the beat, including your punches.' },
  },
  {
    t: 'Beat Saber', y: 2019, dev: 'Beat Games', gr: ['rhythm', 'party'],
    tg: ['vr', 'easytolearn', 'difficult', 'colorful', 'soundtrack', 'short', 'family'],
    md: ['solo', 'coopLocal', 'pvpLocal'], pl: [1, 2], pf: ['pc', 'ps'], pr: 'mid', pv: 1990,
    len: [10, 500], dif: 3, pace: 5, rat: 91, mood: ['adrenaline', 'progress', 'relax'],
    desc: { ru: 'Рубить блоки в такт музыке: лучший VR-опыт и полноценная кардиотренировка.', en: 'Slashing blocks on beat: the best VR experience and a genuine cardio workout.' },
  },
  {
    t: 'Crypt of the NecroDancer', y: 2015, dev: 'Brace Yourself Games', gr: ['rhythm', 'roguelike', 'puzzle'],
    tg: ['difficult', 'pixelart', 'soundtrack', 'replayable', 'lowsysreq', 'coopfocused', 'procedural', 'steamdeck', 'controller'],
    md: ['solo', 'coopLocal'], pl: [1, 2], pf: ['pc', 'ps', 'switch', 'mobile'], pr: 'cheap', pv: 600,
    len: [15, 200], dif: 5, pace: 4, rat: 87, mood: ['adrenaline', 'progress'], coopQ: 8,
    desc: { ru: 'Ходить можно только в ритм: хардкорный рогалик для тех, у кого есть чувство такта.', en: 'You may only move on beat: a hardcore roguelike for the rhythmically gifted.' },
  },
  {
    t: 'Life is Strange Remastered', y: 2022, dev: 'Deck Nine', gr: ['adventure', 'mystery'],
    tg: ['storyrich', 'choices', 'episodic', 'chapterbased', 'sad', 'dialogheavy', 'walkingsim', 'short', 'modern'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1500,
    len: [12, 20], dif: 1, pace: 2, rat: 83, mood: ['story', 'feel', 'think', 'story'],
    desc: { ru: 'Перемотка времени, школьная драма и очень тяжёлые решения: история, к которой возвращаются.', en: 'Time rewinds, high school drama and very heavy choices: a story people return to.' },
  },
  {
    t: 'The Walking Dead: The Telltale Definitive Series', y: 2019, dev: 'Telltale', gr: ['adventure', 'horror'],
    tg: ['storyrich', 'choices', 'episodic', 'chapterbased', 'sad', 'zombie', 'dialogheavy', 'cinematic'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 1990,
    len: [30, 60], dif: 1, pace: 2, rat: 84, mood: ['story', 'feel', 'think'],
    desc: { ru: 'История Ли и Клементины: сериал, который заставил взрослых людей плакать в 4 утра.', en: 'The story of Lee and Clementine: the series that made grown adults cry at 4 am.' },
  },
  {
    t: 'Steins;Gate Elite', y: 2019, dev: 'Mages', gr: ['visual', 'adventure', 'mystery'],
    tg: ['storyrich', 'scifi', 'anime', 'choices', 'dialogheavy', 'soundtrack', 'long'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'switch', 'mobile'], pr: 'mid', pv: 1990,
    len: [30, 50], dif: 2, pace: 1, rat: 92, mood: ['story', 'think'],
    desc: { ru: 'Микроволновка, которая пишет в прошлое: лучшая визуальная новелла про путешествия во времени.', en: 'A microwave that texts the past: the best visual novel about time travel.' },
  },
  {
    t: 'Slime Rancher 2', y: 2022, dev: 'Monomi Park', gr: ['simulator', 'sandbox', 'adventure'],
    tg: ['cozy', 'cute', 'relaxing', 'colorful', 'exploration', 'farming', 'endless', 'family', 'easytolearn', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'xbox', 'ps'], pr: 'mid', pv: 1990,
    len: [20, 100], dif: 1, pace: 2, rat: 84, mood: ['relax', 'explore', 'create'],
    desc: { ru: 'Ранчо слизней на радужном острове: бесконечно милое и абсолютно без стресса.', en: 'A slime ranch on a rainbow island: endlessly cute and completely stress-free.' },
  },
  {
    t: 'Dave the Diver', y: 2023, dev: 'Mintrocket', gr: ['adventure', 'simulator', 'rpg'],
    tg: ['funny', 'management', 'exploration', 'underwater', 'pixelart', 'cozy', 'procedural', 'relaxing', 'colorful', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'switch', 'mobile'], pr: 'mid', pv: 1990,
    len: [25, 60], dif: 2, pace: 3, rat: 90, mood: ['relax', 'laugh', 'progress'],
    desc: { ru: 'Днём — дайвинг и рыба, вечером — суши-бар: смесь жанров, которая работает идеально.', en: 'Diving and fishing by day, running a sushi bar by night: a genre mashup that simply works.' },
  },
  {
    t: 'Cult of the Lamb', y: 2022, dev: 'Massive Monster', gr: ['roguelike', 'simulator', 'action'],
    tg: ['coopfocused', 'dark', 'funny', 'cute', 'management', 'replayable', 'colorful', 'short', 'colony', 'steamdeck', 'controller'],
    md: ['solo', 'coopLocal'], pl: [1, 2], pf: ['pc', 'ps', 'xbox', 'switch', 'mobile'], pr: 'mid', pv: 1500,
    len: [15, 60], dif: 3, pace: 3, rat: 85, mood: ['laugh', 'create', 'adrenaline'], coopQ: 8,
    desc: { ru: 'Культ милых зверьков с тёмной изнанкой: рогалик плюс менеджмент культовой секты.', en: 'A cult of cute animals with a dark side: a roguelike plus cult management.' },
  },
  {
    t: 'Kenshi', y: 2018, dev: 'Lo-Fi Games', gr: ['rpg', 'sandbox', 'survival', 'strategy'],
    tg: ['openworld', 'hardcoresim', 'permadeath', 'basebuilding', 'grind', 'colony', 'long', 'mods', 'difficult'],
    md: ['solo'], pl: [1, 1], pf: ['pc'], pr: 'mid', pv: 1500,
    len: [50, 1000], dif: 5, pace: 1, rat: 84, mood: ['create', 'progress', 'escape'],
    desc: { ru: 'Вы никто в жестоком мире: можно стать рабом, торговцем или королём — игра не подскажет.', en: 'You are nobody in a brutal world: become a slave, a trader or a king with no guidance.' },
  },
  {
    t: 'eFootball', y: 2021, dev: 'Konami', gr: ['sports'],
    tg: ['mtx', 'timegate', 'pvpfocused', 'easytolearn', 'crosplay', 'short', 'grind', 'collect'],
    md: ['solo', 'coopOnline', 'pvpOnline', 'pvpLocal'], pl: [1, 22], pf: ['pc', 'ps', 'xbox', 'mobile'], pr: 'free', pv: 0,
    len: [10, 5000], dif: 3, pace: 4, rat: 45, mood: ['compete', 'progress'], coopQ: 7,
    desc: { ru: 'Бесплатный футбол: матчи по 6 минут, ежедневные награды и постоянный прогресс состава.', en: 'Free football: six-minute matches, daily rewards and constant squad progression.' },
  },
  {
    t: 'Clash of Clans', y: 2012, dev: 'Supercell', gr: ['strategy', 'mmo'],
    tg: ['timegate', 'mtx', 'basebuilding', 'social', 'colony', 'endless', 'grind', 'easytolearn', 'social'],
    md: ['solo', 'coopOnline', 'pvpOnline'], pl: [1, 50], pf: ['mobile'], pr: 'free', pv: 0,
    len: [50, 5000], dif: 3, pace: 1, rat: 74, mood: ['progress', 'create', 'compete'], coopQ: 8,
    desc: { ru: 'Кланы, войны и вечные апгрейды: тайм-гейтинг как жанр, в который играют 10 лет.', en: 'Clans, wars and endless upgrades: time-gating as a genre, going strong for a decade.' },
  },
  {
    t: 'Arknights', y: 2019, dev: 'Hypergryph', gr: ['strategy', 'tactics', 'rpg'],
    tg: ['gacha', 'anime', 'tbs', 'storyrich', 'collect', 'timegate', 'mtx', 'long', 'soundtrack'],
    md: ['solo'], pl: [1, 1], pf: ['mobile', 'pc'], pr: 'free', pv: 0,
    len: [50, 1000], dif: 4, pace: 2, rat: 86, mood: ['think', 'collect', 'story'],
    desc: { ru: 'Тактическая гача-стратегия: продуманные карты, отличный мрачный сюжет и можно без денег.', en: 'A tactical gacha strategy: thoughtful maps, a strong grim story and fully playable for free.' },
  },
  {
    t: 'Deltarune', y: 2025, dev: 'Toby Fox', gr: ['rpg', 'adventure'],
    tg: ['storyrich', 'funny', 'pixelart', 'soundtrack', 'short', 'sad', 'choices', 'lowsysreq', 'episodic', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'switch'], pr: 'mid', pv: 1000,
    len: [15, 40], dif: 3, pace: 3, rat: 93, mood: ['story', 'feel', 'laugh', 'think'],
    desc: { ru: 'Наследник Undertale: три главы уже вышли, и они лучше, чем все ожидали.', en: 'The heir to Undertale: three chapters are out and they exceed every expectation.' },
  },
  {
    t: 'The Plucky Squire', y: 2024, dev: 'All Possible Futures', gr: ['adventure', 'platformer', 'puzzle'],
    tg: ['colorful', 'family', 'cute', 'easytolearn', 'short', 'storyrich', 'handdrawn', 'nonviolent', 'steamdeck', 'controller'],
    md: ['solo'], pl: [1, 1], pf: ['pc', 'ps', 'xbox', 'switch'], pr: 'mid', pv: 2490,
    len: [8, 12], dif: 1, pace: 2, rat: 80, mood: ['relax', 'story', 'laugh'], gp: 1,
    desc: { ru: 'Герой книги выпрыгивает со страницы в 3D: семейное приключение, где всё время меняются стили.', en: 'A book hero jumps off the page into 3D: a family adventure that keeps switching styles.' },
  },
];
