/** Условия использования и раскрытие информации о данных — нужны для Google OAuth и рекламных сетей. */
import { t, getLang } from '../i18n.js';
import { SITE, ADS, FEATURES } from '../config.js';
import { esc } from './components.js';

const TEXT = {
  ru: [
    ['О сервисе', `GustoPlay — бесплатный сервис подбора игр. Мы помогаем выбрать игру по вкусу: вы отвечаете на вопросы, отмечаете игры и получаете список с объяснениями. Сервис не продаёт игры и не является магазином.`],
    ['Данные об играх', 'Названия, жанры, теги, рейтинги, цены и наличие в подписках носят справочный характер и могут меняться без предупреждения. Перед покупкой проверяйте информацию в магазине: мы показываем ориентир, а не оферту.'],
    ['Рекомендации и их точность', 'Подбор формируется алгоритмом на основе ваших ответов и отметок. Это рекомендация, а не гарантия: вкус у всех разный, и мы не обещаем, что игра понравится. Чем больше отметок «понравилось» и «не понравилось», тем точнее выдача.'],
    ['Интеллектуальная собственность', 'Названия игр, товарные знаки и права принадлежат их издателям и разработчикам. Мы не связаны с ними и не претендуем на их права. Обложки на сайте генерируются нашим алгоритмом и не являются официальными артами.'],
    ['Партнёрские ссылки', ADS.affiliateDisclosure?.ru || 'Часть ссылок на магазины может быть партнёрской: если вы купите игру по такой ссылке, магазин может поделиться с нами небольшой комиссией. Для вас цена не меняется.'],
    ['Реклама', 'Сайт может показывать рекламу (Яндекс.РСЯ, Google AdSense). Рекламные скрипты загружаются только после вашего согласия на cookie. Реклама не влияет на порядок рекомендаций: алгоритм не знает, кто заплатил за показ.'],
    ['Аккаунт', `Аккаунт необязателен. Если вы его создаёте, вы отвечаете за сохранность пароля; мы храним только его необратимый хеш. Один человек — один аккаунт, без выдачи себя за других. Удалить аккаунт можно в любой момент на странице «Аккаунт».`],
    ['Запрещено', 'Автоматизированный сбор данных (парсинг) в объёме, создающем нагрузку, попытки взлома, обход ограничений частоты запросов, рассылка спама через формы сервиса.'],
    ['Гарантии и ответственность', 'Сервис предоставляется «как есть». Мы стараемся, чтобы он работал без сбоев, но не гарантируем бесперебойную доступность и не несём ответственности за решения, принятые на основе рекомендаций, а также за контент сторонних магазинов и рекламодателей.'],
    ['Изменения условий', 'Мы можем обновлять эти условия: актуальная версия всегда на этой странице. Продолжая пользоваться сервисом после изменений, вы принимаете новую редакцию.'],
    ['Контакты', `Вопросы, жалобы и предложения: ${SITE.email}.`],
  ],
  en: [
    ['About the service', 'GustoPlay is a free game-matching service. You answer questions, mark games, and get a list with explanations. We do not sell games and we are not a store.'],
    ['Game data', 'Titles, genres, tags, ratings, prices and subscription availability are informational and may change without notice. Check the store before buying: we show a hint, not an offer.'],
    ['Recommendations and their accuracy', 'Matches come from an algorithm working on your answers and marks. It is a recommendation, not a guarantee: taste differs, and we cannot promise you will love a game. More liked/disliked marks means a better match.'],
    ['Intellectual property', 'Game titles, trademarks and rights belong to their publishers and developers. We are not affiliated with them and claim no rights. Covers on the site are generated by our own algorithm and are not official artwork.'],
    ['Affiliate links', ADS.affiliateDisclosure?.en || 'Some store links may be affiliate links: if you buy a game through one, the store may share a small commission with us. Your price does not change.'],
    ['Advertising', 'The site may show ads (Yandex, Google AdSense). Ad scripts load only after you consent to cookies. Ads never influence the order of recommendations: the algorithm does not know who paid for an impression.'],
    ['Accounts', 'An account is optional. If you create one, you are responsible for keeping your password safe; we store only its irreversible hash. One person, one account, no impersonation. You can delete the account any time on the Account page.'],
    ['Prohibited', 'Automated scraping at a scale that creates load, hacking attempts, bypassing rate limits, and sending spam through site forms.'],
    ['Warranty and liability', 'The service is provided “as is”. We aim for reliability but do not guarantee uninterrupted availability and are not liable for decisions made from recommendations, or for third-party store and advertiser content.'],
    ['Changes to these terms', 'We may update these terms: the current version always lives on this page. By continuing to use the service you accept the new revision.'],
    ['Contact', `Questions, complaints and suggestions: ${SITE.email}.`],
  ],
};

export function render() {
  const lang = getLang();
  const rows = TEXT[lang] || TEXT.ru;
  const title = lang === 'ru' ? 'Условия использования' : 'Terms of use';
  const lead = lang === 'ru'
    ? 'Коротко и без юридического тумана: что мы делаем, чего не делаем и как вы можете это прекратить.'
    : 'Short and without legal fog: what we do, what we do not do, and how you can stop it.';

  return `
  <section class="section legal-page">
    <header class="section-head">
      <h1>${esc(title)}</h1>
      <p>${esc(lead)}</p>
      <p class="muted">${esc(lang === 'ru' ? 'Обновлено' : 'Updated')}: ${new Date().toISOString().slice(0, 10)} · ${esc(SITE.domain)}</p>
    </header>

    <div class="panel legal">
      ${rows.map(([q, a]) => `<h2 class="h-base">${esc(q)}</h2><p>${esc(a)}</p>`).join('')}
    </div>

    <div class="panel">
      <h2 class="h-lg">${esc(lang === 'ru' ? 'Ещё документы' : 'More documents')}</h2>
      <p class="muted">${esc(lang === 'ru'
        ? 'Как мы обращаемся с данными — в политике конфиденциальности. Как устроен подбор — в разделе «Как это работает».'
        : 'How we handle data is in the privacy policy. How matching works is explained on the How it works page.')}</p>
      <div class="panel-actions">
        <a class="btn btn-outline" href="#/privacy" data-action="nav">${esc(t('about.privacy.title'))}</a>
        <a class="btn btn-ghost" href="#/about" data-action="nav">${esc(t('nav.about'))}</a>
        ${FEATURES.affiliateLinks ? '<a class="btn btn-ghost" href="#/catalog" data-action="nav">' + esc(t('nav.catalog')) + '</a>' : ''}
      </div>
    </div>
  </section>`;
}

export const title = () => (getLang() === 'ru' ? 'Условия использования' : 'Terms of use') + ` — ${SITE.name}`;
export const description = () => (getLang() === 'ru'
  ? 'Условия использования GustoPlay: данные об играх, реклама, партнёрские ссылки, аккаунт и ответственность.'
  : 'GustoPlay terms of use: game data, ads, affiliate links, accounts and liability.');
